util-linux/util-linux

- sys-utils/hwclock.8.in
Signed-off-by: J William Piggott <elseifthen@gmx.com>
> hwclock: improve man-page language

- misc-utils/logger.c
Since 1d57503378bdcd838365d625f6d2d0a09da9c29d logger no longer uses
the syslog(3) call. The way the local timestamp is generated did not
match the syslog(3) format. Most importantly, the month name is
formatted based on the user's local. For example:
$ ./logger --stderr  test with logger 2.26.39-eb651-dirty
<5>Mär  5 14:17:47 logger: test with logger 2.26.39-eb651-dirty
"Mär" like in German "März" for "March".
previously:
$ logger --stderr  test with logger 2.25.2
rger: test with logger 2.25.2
In the system log file, this results to the following:
Mar  5 14:17:47 host Mär  5 14:17:47 logger: test with logger 2.26.39-eb651-dirty
Mar  5 14:18:01 host rger: test with logger 2.25.2
This local naming is invalid as of RFC3164. One may argue that
the local log socket traditionally does not have …
> logger: fix invalid timestamp regression in local format

- misc-utils/logger.c
see https://github.com/karelzak/util-linux/issues/163
> logger: fix problems with PRI handling

- misc-utils/logger.1
I was imprecise in https://github.com/karelzak/util-linux/issues/165, so not all occurrences could be fixed.
> logger  man page: nitfixes

- .travis-functions.sh
- .travis.yml
- tests/functions.sh
Just to simplify build setup for drone.io, another nice build system for github projects.
FYI
https://drone.io/github.com/rudimeier/util-linux
Drone build hosts are almost the same like on travis but drone has a few advantages (and disadvantages).
For exampe the build script lives outside util-linux and builds or manually invoked re-builds  usually start and finish much faster. Moreover you can "deploy" downloadable files. This makes it a lot easier to debug and fix bugs.
> tests: minor cosmetics for drone.io support

- disk-utils/fdisk.c
- libfdisk/src/dos.c
- libfdisk/src/table.c
- sys-utils/zramctl.c
Many thanks for reviewing the patch.
> Fix trivial typos

- .travis.yml
see https://github.com/travis-ci/travis-ci/issues/5301
> travis: workaround env pollution, PYTHON_CFLAGS

- AUTHORS
- libsmartcols/src/column.c
- libsmartcols/src/smartcolsP.h
- libsmartcols/src/table.c
Reference: https://github.com/karelzak/util-linux/issues/254
> libsmartcols: reflect changinging SCOLS_FL_TREE after adding to table

- libsmartcols/src/libsmartcols.h.in
- libsmartcols/src/libsmartcols.sym
- libsmartcols/src/smartcolsP.h
- libsmartcols/src/symbols.c
- libsmartcols/src/table.c
- libsmartcols/src/table_print.c
> libsmartcols: implement title of table

- libsmartcols/docs/libsmartcols-sections.txt
- libsmartcols/src/column.c
- libsmartcols/src/libsmartcols.h.in
- libsmartcols/src/libsmartcols.sym
- libsmartcols/src/table_print.c
Reference: https://github.com/karelzak/util-linux/issues/257
> libsmartcols: implement SCOLS_FL_WRAP

- disk-utils/fsck.c
- lib/at.c
- lib/blkdev.c
- lib/exec_shell.c
- lib/ismounted.c
- lib/pager.c
- lib/path.c
- lib/strutils.c
- lib/sysfs.c
- lib/timeutils.c
- libuuid/src/gen_uuid.c
- libuuid/src/uuid_time.c
- sys-utils/ipcutils.h
- term-utils/script.c
Some of these fixes may be too ugly ... you will see.
FYI I've enabled OSX travis build on my private ul clone. It builds already with some additional hacks:
https://travis-ci.org/rudimeier/util-linux/builds/108523108
> Fix some compiler warnings

- libsmartcols/src/table_print.c
> libsmartcols: fill wrapped lines with space instead of 'x'

- libsmartcols/docs/libsmartcols-docs.xml
- libsmartcols/docs/libsmartcols-sections.txt
- libsmartcols/src/libsmartcols.h.in
- libsmartcols/src/libsmartcols.sym
- libsmartcols/src/table_print.c
Reference: https://github.com/karelzak/util-linux/issues/283
> libsmartcols: implement scols_table_print_range_to_string

- configure.ac
- disk-utils/fdisk.c
- include/fileutils.h
- lib/blkdev.c
- lib/fileutils.c
- lib/mbsalign.c
- libblkid/src/save.c
- libfdisk/src/gpt.c
- libsmartcols/src/table_print.c
- login-utils/last.c
- login-utils/login.c
- login-utils/newgrp.c
- misc-utils/Makemodule.am
- misc-utils/logger.c
- misc-utils/test_uuidd.c
- sys-utils/ipcs.c
- sys-utils/lsipc.c
- sys-utils/rtcwake.c
- text-utils/pg.c
Some arbitrary mostly trivial issues.
> some fixes, cleanup and portability issues

- tests/functions.sh
- tests/ts/losetup/losetup-blkdev
- tests/ts/minix/mkfs
- tests/ts/mount/fstab-btrfs
- tests/ts/swapon/devname
- tests/ts/swapon/fixsig
- tests/ts/swapon/label
- tests/ts/swapon/uuid
These tests fixes are IMO good to have in 2.28-rc1. That's why I didn't fixed them as good as I should with more time but added some comments/todos.
> test fixes for 2.28-rc1

- include/namespace.h
- sys-utils/nsenter.1
- sys-utils/nsenter.c
- sys-utils/unshare.1
- sys-utils/unshare.c
Currently these are supported in #for-next.
Signed-off-by: Serge Hallyn <serge.hallyn@ubuntu.com>
> Implement support for cgroup namespaces

- libsmartcols/src/column.c
- libsmartcols/src/line.c
> libsmartcols: fix typos in docs

- tests/ts/libsmartcols/fromfile
> trivial: use tabs consistently

- configure.ac
- tools/git-version-gen
> build-sys: fix bashism, introduced in 85004b14

- term-utils/agetty.c
> agetty: fix ifdef typo

- login-utils/chfn.1
- login-utils/chsh.1
- login-utils/chsh.c
Not sure if these changes are really worth it, but these where some needless trivial differences I noticed while comparing shadow vs util-linux equivalent tools.
Please note that this is untested! You decide if it's worth merging. Feel free to just reject this otherwise.
More differences available in for anyone interested:
https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=833256;filename=shadow-comparison.txt;msg=35
> Shadow man

- misc-utils/findmnt.c
> findmnt: flush stdout after each (un)(re)mount event, when polling.

- libfdisk/src/gpt.c
- misc-utils/fincore.c
- sys-utils/lsmem.c
> Fix minor typos

- disk-utils/fdformat.c
Before:
Formatting ... done1
After:
Formatting ... done
> fdformat: clear progress message before printing "done"

- disk-utils/mkfs.cramfs.c
- login-utils/last.c
- login-utils/su-common.c
- login-utils/sulogin.c
- misc-utils/cal.c
- misc-utils/rename.c
- sys-utils/flock.c
- sys-utils/hwclock.c
- sys-utils/ipcrm.c
- sys-utils/nsenter.c
- sys-utils/unshare.c
- term-utils/agetty.c
- text-utils/hexdump-parse.c
- text-utils/more.c
- text-utils/pg.c
- text-utils/ul.c
As discussed by Sami, Karel and Rudi on mailing list.
> misc: fix ggc-7 fallthrough warnings

- lib/randutils.c
> misc: fix some printf format strings

- disk-utils/fdisk.c
- include/strutils.h
> fdisk: fixes for get_user_reply()

- po/it.po
See also https://translate.google.it/#en/it/end
> Fix italian "end" translation

- libblkid/src/superblocks/udf.c
LVIDIU is stored at the end of Logical Volume Integrity Descriptor (LVID),
after two variable length array of partitions. And number of partitions is
stored in LVID, not in Logical Volume Descriptor (LVD).
Length of LVIDIU is also stored in LVID, so add check that LVIDIU has
enough size.
Fixes commit db316767434c2c451ec1732861256d5729143e89.
___
From LVIDIU we use only Minimum UDF Read Revision which is set to ID_FS_VERSION and was introduced in above commit. So in worst case we reported only wrong field ID_FS_VERSION.
Apparently all tested images have number of partitions maps in LVD same as number of partitions in LVIDIU, so this problem was not detected by any tested image before :-(
> libblkid: udf: Fix reading Logical Volume Integrity Descriptor Implementation Use (LVIDIU)

- lib/mbsalign.c
- libfdisk/src/gpt.c
> GPT partition name

- sys-utils/renice.c
> Fix minor typo: priorty -> priority

- sys-utils/lsmem.1
- sys-utils/lsns.8
- sys-utils/rfkill.8
- sys-utils/unshare.1
Many thanks for fixing these typos.
> Fix minor typos on man pages

- .travis-functions.sh
- tests/functions.sh
- tests/ts/ipcs/limits
- tests/ts/ipcs/limits2
- tests/ts/libmount/loop
- tests/ts/libmount/loop-overlay
follow-up like mentioned in #588
> tests: re-introduce bash 3 compatibility (OSX)

- configure.ac
- misc-utils/rename.1
- misc-utils/rename.c
> rename: add option --interactive to ask before overwriting

- libblkid/src/superblocks/apfs.c
* More checking to avoid false positives
* Add UUID of Container to blkid
> libblkid: Add more APFS checking to avoid false positives

- text-utils/more.c
These 695 insertions and 781 deletions aims to improve readability of the more(1). The means achieving that goal include cleanups as well as renaming.
Assuming this pull request is someday merged the next thing to do with more(1) is to improve the code. For example longjmp's need to  go, there is better and less confusing way to do that. Anyway, these need to wait until this pull is processed.
> More more(1) updates

- bash-completion/fstrim
- bash-completion/hwclock
- bash-completion/mount
- bash-completion/rename
- bash-completion/script
- bash-completion/setpriv
- bash-completion/su
- bash-completion/umount
Check what has changed in usage functions in between v2.32..a77bd80d5 and
update bash-completion files accordingly.
> bash-completion: catch up with option changes

- login-utils/last.c
- sys-utils/readprofile.c
Addresses bugs https://github.com/karelzak/util-linux/issues/715 and https://github.com/karelzak/util-linux/issues/717.
> Asan fixes: last(1) and readprofile(8)

- sys-utils/swapon.8
Addresses: https://github.com/karelzak/util-linux/issues/768
> swapon.8: mention btrfs(5)

- disk-utils/sfdisk.c
- lib/colors.c
- lib/mangle.c
- libmount/src/monitor.c
- login-utils/sulogin.c
- misc-utils/wipefs.c
- sys-utils/lscpu.c
Hopefully most if not all of these cppcheck warning fixes are included to upstream before next release.
> 2019wk19 release preparation warning fixes

- bash-completion/script
- bash-completion/scriptlive
- bash-completion/scriptreplay
- term-utils/script-playutils.c
- term-utils/script.1
- term-utils/script.c
- term-utils/scriptreplay.1
- term-utils/scriptreplay.c
Upcoming release has major changes to script(1) and related commands, so I gave final polish to these before release. All three commits can be considered cosmetic.
> Release prep

- po/uk.po
My translation had been forgotten when 2.35 was prepared. Thanks for merging.
> po: update uk.po (from translationproject.org)

- Makefile.am
- include/pidfd-utils.h
- include/timeutils.h
- libfdisk/src/gpt.c
- login-utils/last.c
- login-utils/login.c
- misc-utils/.gitignore
- misc-utils/Makemodule.am
- misc-utils/cal.c
- misc-utils/getopt.1.in
- misc-utils/logger.c
- sys-utils/fstrim.timer
- sys-utils/hwclock-parse-date.y
- sys-utils/ipcs.c
- sys-utils/rtcwake.c
- term-utils/agetty.c
- term-utils/script-playutils.c
- term-utils/wall.c
- term-utils/write.c
Both commits are overly pedantic, and done to keep static analysis noise level low so that real issues are easy to notice.
> gcc potential overflow and various lgtm scan fixes

- misc-utils/kill.1
Requested-by: Ilia Baryshnikov <qwelias@gmail.com>
Reference: https://github.com/karelzak/util-linux/issues/991#issuecomment-602108648
> docs: kill.1 add note about shell-internal kill implementations

- bash-completion/lslogins
- libuuid/src/gen_uuid.c
- login-utils/login.c
- login-utils/lslogins.1
- login-utils/lslogins.c
- sys-utils/ctrlaltdel.c
I can admit the three first changes are not very exciting. But I am quite happy about realisation lslogins can be made better by looking into lastlog when wtmp does not have an entry. If I am not wrong wtmp is routinely rotated every now and then, but lastlog tends to hang around much longer so it is pretty decent fallback.
> 2020wk12 couple small fixes and a nice improvement to lslogins

- libmount/src/context_umount.c
Currently, umount /foo results in a statfs("/foo") call, which triggers
autofs. This can create another mountpoint on /foo, which is then unmounted
later instead of the actual /foo at the time umount was called.
This is especially an issue for umount -R /bar, which just fails with
-EBUSY as the accidental mountpoint is never accounted for and so it tries
to umount /bar before /bar/someautofs.
Replace the direct statfs call with open(path, O_PATH) + fstatfs, which sees
the autofs mount directly, without triggering it.
> libmount: Avoid triggering autofs in lookup_umount_fs_by_statfs

- misc-utils/rename.c
Since commit 5454df9c3110 ("rename: check source file access early")
rename fails early for symlinks with non-existing target (regression),
because `access()` dereferences the link.
From `access(2)`:
```
"access() checks whether the calling process can access the file pathname.
If pathname is a symbolic link, it is dereferenced."
```
Thus replace `access()` with `faccessat()` and `lstat()` as fallback,
(as in `do_symlink()`), that is equivalent for symlink and files.
From `fsaccess(2)` and `stat(2)`:
```
"The faccessat() system call operates in exactly the same way as access(),
except for the differences described here.
[...]
If pathname is relative and dirfd is the special value AT_FDCWD, then pathname
is interpreted relative to the current working directory of the calling process
(like …
```
> rename: fix regression for symlink with non-existing target

- term-utils/scriptreplay.c
glibc/sysdeps/posix/isatty.c suggests that isatty(3) is implemented using tcgetattr(3). This patch makes scriptreplay(1) avoid the use of isatty(3). Instead, tcgetattr(3) is directly called with more rigorous/fine-tuned error handling based on errno values. This seems much more elegant. Also, err(3) is not called upon tcsetattr(3) failure.
This follows #1108.
> [PATCH] script(1): Add more elegant error handling. Avoid isatty.

- include/loopdev.h
- lib/loopdev.c
- sys-utils/losetup.c
Prefer to use the new LOOP_CONFIGURE ioctl.
https://lwn.net/Articles/820408/
Signed-off-by: Sinan Kaya <sinan.kaya@microsoft.com>
> loopdev: use LOOP_CONFIGURE ioctl

- configure.ac
- disk-utils/fdisk-list.c
- disk-utils/fdisk-list.h
- lib/env.c
- lib/randutils.c
- libblkid/src/cache.c
- libblkid/src/devname.c
- libblkid/src/probe.c
- libmount/src/fs.c
- misc-utils/uuidgen.1
- tests/expected/fdisk/bsd_0_64.BE
- tests/expected/fdisk/bsd_0_64.LE
- tests/expected/fdisk/bsd_0_64_alpha.LE
- tests/expected/fdisk/bsd_1_0.BE
- tests/expected/fdisk/bsd_1_0.LE
- tests/expected/ul/basic
- tests/ts/fdisk/bsd
- tests/ts/ul/filter.input
- text-utils/column.c
Fixed some typos found by myself and with codespell.
> misc: fix typos

- libfdisk/src/script.c
Signed-off-by: Gaël PORTAY <gael.portay@collabora.com>
> libfdisk: (script) ignore empty values for start and size

- sys-utils/switch_root.c
In Gentoo's initramfs created by genkernel we sometimes need to unmount `/run` (because we don't have a proper SELinux support) to avoid unusable `/run` (due to missing labels).
This will throw the following non-fatal error
```
switch_root: Failed to mount moving /run to /newroot/run: Invalid argument
switch_root: forcing unmount of /run
```
If we check if mountpoint we want to move even exists before trying to move, we can avoid that message.
> switch_root: check if mountpoint to move even exists

- sys-utils/lsns.8.adoc
> man: add ioctl_ns(2) to SEE ALSO of lsns(2)

- bash-completion/lsblk
Signed-off-by: Ville Skyttä <ville.skytta@iki.fi>
> bash-completion: (lsblk) fix -E/-M arg (non-)completion

- sys-utils/lsns.c
Sorry for sending pull requests incrementally.
This will be the last one.
> lsns: fill UID and USER columns for interpolated namespaces 

- misc-utils/lsblk.8.adoc
> lsblk: fix formatting in -e option

- sys-utils/unshare.c
When using --mount-proc=/some/path then unshare fails if the path provided is not already mounted due to the mount(2) call to change the propagation of the mount.
In such a case mount(2) returns EINVAL, which however is used for a variety of other errors.
If this error is ignored mistakenly the effects however should be negligible since:
1. the mount of proc afterwards happens regardless, errors of which are not ignored
2. the propagation change of root uses MS_REC, which should already change the propagation of all mounts recursively
Furthermore /proc is not touched if --mount-proc specifies a different mount point.
This should not cause too much unexpected behaviour due to point 2 from above in any case.
Specifying --mount-proc with a different path also means that unshare(3) is not …
> fix #648 by ignoring EINVAL on-remount of proc

- lib/pwdutils.c
- misc-utils/Makemodule.am
- misc-utils/logger.c
- term-utils/wall.c
I ended up making several fixes, let me know if you'd like for them to be split into separate PRs.
> Fix things around pwdutils and getlogin usage.

- sys-utils/lscpu-arm.c
> fix error ft_part 0x662

- sys-utils/rfkill.c
`rfkill event` kept running ever after its stdout has been cut off. There's no reason to continue running if stdout is a pipe and the receiving end is closed.
> rfkill: quit when read end of stdout is closed

- libsmartcols/meson.build
- meson.build
various meson build fixes. build works after this except for #1442.
> Meson fixes

- libmount/src/fuzz.c
It should help to address https://github.com/google/oss-fuzz/issues/6703
Signed-off-by: Evgeny Vereshchagin <evvers@ya.ru>
> mount_fuzz: reject giant files early

- sys-utils/nsenter.c
This PR changes is_same_namespace() such that if a namespace file is missing
for the running PID, this namespace is considered nonexisting, and thus, it is the same.
As a side effect, we will no longer try to setns() into any namespace that is
the same (previously, this only applied to the user NS).
Signed-off-by: Yonatan Goldschmidt <yon.goldschmidt@gmail.com>
Closes: https://github.com/util-linux/util-linux/issues/1502
@karelzak , this is how I followed your suggestion. As I noted, it changes the behavior of `nsenter` (in ways that remain correct to my understanding, but are still more than required for my proposed fix); we might want to avoid making this large change?
> nsenter: Do not try to enter nonexisting namespaces when --all is used

- tests/helpers/test_mkfds.c
The oldfd argument of dup2 is not closed automatically.
It must be closed explicitly.
Close #1517.
> tests: (lsfd) fix file descriptor leaks reported by coverity

- sys-utils/lscpu-arm.c
See https://en.wikipedia.org/wiki/FeiTeng_(processor)#Future_processors .
> Add Earlier Phytium cores

- misc-utils/blkid.8.adoc
There is a minor grammatical mistake in the blkid manpage.
> blkid: minor typo in manpage

- misc-utils/look.1.adoc
Add mention of beeing a prefix search.
Thanks to @stoeckmann for tutorship.
> Fix difference between short description and longer description

- disk-utils/mkfs.c
- include/fileeq.h
- sys-utils/fsfreeze.8.adoc
- sys-utils/irqtop.1.adoc
- text-utils/rev.1.adoc
No functional change involved.
Signed-off-by: Tobias Stoeckmann <tobias@stoeckmann.org>
> Fix wording in comments and documentation

- sys-utils/unshare.c
In #1086, signal(3) is used along with SIG_IGN, and SIG_DFL, to prevent premature termination of the parent. The present approach causes the forked child to have different inherited signal handling behaviour than original behaviour inherited by the parent.
```
$ /usr/bin/unshare cat /proc/self/status | grep Sig
SigQ:   0/15523
SigPnd: 0000000000000000
SigBlk: 0000000000000000
SigIgn: 0000000000000000
SigCgt: 0000000000000000
$ /usr/bin/unshare --fork cat /proc/self/status | grep Sig
SigQ:   0/15523
SigPnd: 0000000000000000
SigBlk: 0000000000000000
SigIgn: 0000000000004002
SigCgt: 0000000000000000
```
As a consequence, if the underlying command is killed, the outcome is different if `--fork` is used:
```
$ /usr/bin/unshare sh -c 'kill $$' ; echo $?
Terminated
143
$ /usr/bin/unshare --fork …
```
> unshare: Propagate inherited signal handling to forked child

- libmount/src/mountP.h
- sys-utils/mount.8.adoc
> mount: Allow bind-mounting with "nosymfollow"

- tests/expected/lsfd/mkfds-directory
- tests/ts/lsfd/lsfd-functions.bash
- tests/ts/lsfd/mkfds-directory
See #1511.
This pull request may fix "FAILED" partially.
> tests: (lsfd) fix bugs in test cases

- misc-utils/lsfd.c
The original code scanning /proc/$PID/maps assumed two things; an entry
of the file contains a path started from '/' if a file is mapped, and
stat(2) works well with the path in the entry.
A mmap'ed socket breaks the former assumption.
tcpdump/lipcap does mmap an AF_PACKET socket to its address space!
A file is deleted after mapping breaks the latter assumption.
With this change, lsfd utilizes dentries under /proc/$PID/map_files
for gathering information of the mapped file in the case that the
assumptions are broken.
Private anonymous mappings are skipped to avoid wasting CPU time.
Example output:
```console
COMMAND     PID    USER ASSOC MODE TYPE SOURCE MNTID     INODE NAME
tcpdump 1541379 tcpdump   shm  rw- SOCK sockfs     0 114535087 PACKET:[114535087]
COMMAND             PID …
```
> lsfd: use /proc/$PID/map_files as the fallback information source

- libfdisk/meson.build
> libfdisk: meson.build fix typo

- libblkid/meson.build
- libfdisk/meson.build
- libmount/meson.build
- libsmartcols/meson.build
- libuuid/meson.build
- meson.build
- make dependencies work as meson subprojects
- avoid warnings on newer meson
- specify the minimum requirements for Meson itself
> meson fixes and improvements

- libfdisk/meson.build
- libmount/meson.build
- libsmartcols/meson.build
- libuuid/meson.build
- meson.build
- fix static builds creating conflicting targets
- pass the correct absolute path to config.h
> more meson fixes for building as a static subproject

- meson.build
- use version-gen script to match autotools
- fix .pc version number
> Meson fixups

- sys-utils/fstrim.c
When processing fstab entries, de-duplication is performed based on the
source before all tests on the target have been checked, resulting in
some entries being skipped when a removed duplicate with a different
target would not have been.
The fix is to move all the target checks before the source
de-duplication.
Addresses: #1686
Signed-off-by: Scott Shambarger <devel@shambarger.net>
> fstrim: Remove all skipped entries before de-duplication

- sys-utils/fstrim.timer
Minor clarity tweaks to help at-a-glance reading.
> minor: clarity in fstrim.timer

- libblkid/src/devname.c
The existing `is_dm_leaf()` function (added in fd5a4d7fc34273fab800bc96a7fc286b461b602c) determines if a given device is a 'leaf' node by reading all block devices to see if any have an entry in `/sys/block/%s/slaves/` that matches the given device. This introduces an O(n<sup>2</sup>) loop into `blkid` that causes extreme performance impact on systems with a large number of devmapper devices (thousands or more).
This PR improves the implementation by reading `/sys/block/%s/holders/` on the given device instead of `/slaves/` across all other devices to determine whether the device is a leaf node, eliminating the scan across all block devices in the system.
> libblkid: Improve performance of devname.c:is_dm_leaf()

- sys-utils/lsns.8.adoc
> lsns: (man) add ip-netns to "SEE ALSO" section

- meson.build
It didn't work properly.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
@eli-schwartz does this look sane?
> remove faulty boolean

- libblkid/src/superblocks/btrfs.c
> libblkid: btrfs: add checksum support

- libblkid/src/superblocks/exfat.c
> libblkid: exfat: add checksum support

- libblkid/src/superblocks/zonefs.c
> libblkid: zonefs: add checksum support

- bash-completion/fadvise
> fadvise: add bash-completion script

- .github/workflows/differential-shellcheck.yml
The new version of Differential ShellCheck GitHub Action brings many improvements:
- External sourcing by default (`shellcheck -x`)
- Improved shell script autodetection
- and more
> ci: Update Differential ShellCheck GitHub Action

- meson.build
See https://github.com/util-linux/util-linux/pull/1824#issuecomment-1295652344 .
Reported-by: Rosen Penev <rosenp@gmail.com>
> meson: build fadvise

- lib/meson.build
- libmount/meson.build
- libmount/python/meson.build
- libmount/python/pylibmount.c
- meson.build
- sys-utils/dmesg.c
Various fixes extracted from #1873 mostly to enable more unittests.
> meson: various fixes

- sys-utils/lsns.c
> lsns: add TIMENS to the map from CLONE_* to LSNS_ID_*

- tests/functions.sh
- tests/helpers/test_sysinfo.c
- tests/ts/colcrt/functional
- tests/ts/colcrt/regressions
- tests/ts/column/table
Instead of blindly disabling those test under qemu-user use proper feature-tests.
> tests: properly check for widestring functionality

- tests/functions.sh
- tests/ts/minix/fsck
Amend a typo in a comment, that was inaccurate.
> tests: fix typo in comment

- disk-utils/meson.build
- lib/meson.build
- libmount/meson.build
- login-utils/meson.build
- meson.build
- meson_options.txt
- misc-utils/meson.build
Hello Karel,
I have started experimenting building util-linux with meson for Debian.
Here is a first PR for the necessary patches. I think they should all be good for upstream.
Debian builds fdisk,sfdisk,blkid statically, there I still have some work to do.
Note that I started off 2.38.1, but these patches are for master.
Would appreciate a review, thoughts, comments, ...
I haven't really used meson before.
Thanks,
Chris
> Meson build fixes

- bash-completion/umount
> umount: properly handle special characters in completion

- .packit.yaml
> ci: run packit builds for commits on master and releases

- sys-utils/renice.1.adoc
Relates to issue #1892.
Signed-off-by: Jan Engelhardt <jengelh@inai.de>
> doc: update renice.1 for spelling and style

- .packit.yaml
- disk-utils/mkswap.c
- lib/Makemodule.am
- libblkid/src/topology/ioctl.c
- libblkid/src/topology/sysfs.c
- meson.build
- sys-utils/ipcutils.c
- sys-utils/wdctl.c
- tools/Makemodule.am
Also contains all of #2000, so best wait with merging after that one is done.
Cc @mrc0mmand
> ci: packit: use --enable-werror

- libmount/src/hook_idmap.c
When we create a new namespace in a child process to persist it we need to ensure that the child hangs around. During exit the child will drop all references to its namespaces and so by the time we call open we might already fail to open the namespace. Fix this.
Signed-off-by: Christian Brauner (Microsoft) <brauner@kernel.org>
> libmount: ensure child hangs around until we persisted namespace

- Makefile.am
- po-man/Makefile.am
- po-man/po4a.cfg
- po-man/sr.po
- tools/Makemodule.am
- tools/asciidoctor-unicodeconverter.rb
See single commits for more details.
> assorted fixes for po-man

- disk-utils/fsck.cramfs.c
On 32-bit systems the file length check does not handle files correctly which are larger than 4 GB. Use an unsigned long long which is already in place for blkdev_get_size.
Proof of Concept:
- Prepare a file containing a CramFS
```
mkdir owo
mkfs.cramfs owo owo.iso
dd if=/dev/zero of=owo.iso bs=1 seek=4294967296 count=1 conv=notrunc
fsck.cramfs owo.iso
```
- Check the file
```
fsck.cramfs owo.iso
```
You will see: `fsck.cramfs: file length too short` Better message is: `fsck.cramfs: file extends past end of filesystem`
Signed-off-by: Samanta Navarro <ferivoz@riseup.net>
> fsck.cramfs: print correct error on 32-bit systems

- misc-utils/lsfd.1.adoc
- misc-utils/lsfd.c
- tests/expected/lsfd/option-inet
- tests/ts/lsfd/option-inet
With the option, lsfd lists only IPv4 sockets and/or IPv6 sockets.
> lsfd: implement -i/--inet options

- libblkid/src/superblocks/nvidia_raid.c
Validate size and checksum fields.
> libblkid/nvidia_raid: reduce false-positives

- Documentation/TODO
It was implemented in 556925fe.
> TODO: drop agetty LOGIN_PLAIN_PROMPT todo

- term-utils/agetty.8.adoc
seeting → setting
aggety → agetty
> agetty: (man) fix typos

- sys-utils/hwclock-cmos.c
- sys-utils/hwclock-rtc.c
- sys-utils/hwclock.c
- sys-utils/hwclock.h
- tests/ts/hwclock/show
> some cleanups for hwclock

- tests/expected/lsfd/mkfds-netns
- tests/ts/lsfd/column-name
- tests/ts/lsfd/lsfd-functions.bash
- tests/ts/lsfd/mkfds-netns
- tests/ts/lsfd/mkfds-unix-dgram
- tests/ts/lsfd/mkfds-unix-in-netns
- tests/ts/lsfd/mkfds-unix-stream
(These are not urgent fixes.)
I run the test cases of lsfd on my Raspberry Pi.
I got some failures. Fortunately, lsfd itself works well.
Revising the test cases is enough to avoid the failures.
> Revise test cases of lsfd

- tests/helpers/test_mkfds.c
- tests/ts/lsfd/lsfd-functions.bash
- tests/ts/lsfd/mkfds-ping
- tests/ts/lsfd/mkfds-ro-block-device
This includes the revised version of the commit in #2179.
> tests: (lsfd) make the message for skipping the case more descriptive

- include/caputils.h
- lib/caputils.c
- sys-utils/Makemodule.am
- sys-utils/nsenter.c
- sys-utils/unshare.c
> Add --keep-caps option to nsenter, matching that in unshare

- tests/expected/fadvise/drop
- tests/ts/fadvise/drop
Fixes #2249
This should also go to 2.39
> fadvise: fix tests with 64k pagesize

- .github/workflows/cibuild-setup-ubuntu.sh
- .github/workflows/cibuild.sh
- .github/workflows/cibuild.yml
- .github/workflows/openwrt-sdk-env.sh
- disk-utils/mkfs.minix.c
- libsmartcols/samples/continuous.c
- misc-utils/Makemodule.am
- misc-utils/enosys.c
- misc-utils/test_uuidd.c
This allows testing some more exotic architectures and libcs.
> ci: add OpenWrt SDK based CI jobs

- configure.ac
- include/Makemodule.am
- include/audit-arch.h
- libmount/meson.build
- meson.build
- misc-utils/enosys.c
> enosys: only build if AUDIT_ARCH_NATIVE is defined

- .github/workflows/cibuild-setup-ubuntu.sh
- .github/workflows/cibuild.sh
- .github/workflows/cibuild.yml
- Makefile.am
- configure.ac
- disk-utils/blockdev.c
- po-man/Makefile.am
- sys-utils/blkzone.c
- tests/functions.sh
- tests/ts/hwclock/show
- tests/ts/lsfd/column-name
- tests/ts/lsfd/column-source-with-root
- tests/ts/lsfd/mkfds-mapped-packet-socket
- tests/ts/lsfd/mkfds-netns
- tests/ts/lsfd/mkfds-raw6
- tests/ts/lsfd/mkfds-ro-block-device
- tests/ts/lsfd/mkfds-tcp6
- tests/ts/lsfd/mkfds-udp6
- tests/ts/lsfd/option-inet
- tests/ts/misc/setarch
- tests/ts/mount/fstab-bind
- tests/ts/mount/fstab-broken
- tests/ts/mount/fstab-none
- tests/ts/mount/move
- tools/asciidoctor-includetracker.rb
- tools/asciidoctor-unicodeconverter.rb
This should help to catch build breaks
> ci: build on old distro

- disk-utils/partx.c
- libblkid/src/topology/sysfs.c
- libfdisk/src/bsd.c
- libmount/python/context.c
- libmount/python/fs.c
- libmount/python/tab.c
- login-utils/lslogins.c
- misc-utils/fincore.c
- misc-utils/findmnt.c
- misc-utils/lsblk.c
- misc-utils/lsfd-filter.c
- misc-utils/lslocks.c
- sys-utils/losetup.c
- sys-utils/lsipc.c
- sys-utils/prlimit.c
- sys-utils/swapon.c
- sys-utils/wdctl.c
> Constifications and struct simplifications

- include/timeutils.h
- misc-utils/lsfd-filter.c
- misc-utils/lsfd-unkn.c
> lsfd: minor refactoring

- meson.build
... as these commands requires elevated privileges.
> meson: install setuid/setgid

- libmount/src/optlist.c
- tests/expected/libmount/loop-explicit-rw
- tests/ts/libmount/loop
Fixes #2305
Cc @suiryc . Can you validate that this fixes your issue?
> libmount: (optlist) correctly detect ro status

- libmount/src/optlist.c
- tests/expected/libmount/loop-explicit-rw
- tests/ts/libmount/loop
> 2.39: libmount: (optlist) correctly detect ro status

- meson.build
> 2.39: meson: check for _NL_TIME_WEEK_1STDAY in langinfo.h

- libmount/Makemodule.am
- libmount/samples/Makemodule.am
- libmount/samples/overwrite.c
- libmount/src/context.c
- libmount/src/fs.c
bugfix for https://github.com/util-linux/util-linux/issues/2326
> libmount optstr sync

- lib/loopdev.c
- sys-utils/losetup.c
Replaces #2337 
@ambiamber does this work for you correctly?
It has the advantage that it show the actual error message.
> losetup: print correct errormessage when looking for unused devices

- misc-utils/cal.c
- tests/ts/cal/column
> cal -c: various fixes

- .github/workflows/codeql.yml
- schedutils/chrt.c
- tests/expected/schedutils/chrt-deadline
- tests/ts/schedutils/chrt
For details see commit messages
> chrt: various fixes

- libblkid/src/topology/topology.c
Reported-by: https://github.com/util-linux/util-linux/pull/2430
References: https://github.com/util-linux/util-linux/commit/3ab9e699a8d90f55e0447516b7e05a8686180467
> libblkid: fix topology chain types mismatch

- configure.ac
- include/fileutils.h
- include/mount-api-utils.h
- include/pidfd-utils.h
- libblkid/src/topology/topology.c
- libmount/python/meson.build
- libmount/src/context_mount.c
- libmount/src/hook_idmap.c
- libmount/src/hook_mount.c
- libmount/src/hook_mount_legacy.c
- libmount/src/hooks.c
- libmount/src/libmount.h.in
- libmount/src/optmap.c
- libmount/src/utils.c
- libmount/src/version.c
- m4/ax_compare_version.m4
- meson.build
- misc-utils/uuidd.8.adoc
- schedutils/chrt.1.adoc
- sys-utils/lscpu-arm.c
- sys-utils/mount.8.adoc
- sys-utils/setarch.c
- sys-utils/zramctl.8.adoc
- sys-utils/zramctl.c
- term-utils/ttymsg.c
- text-utils/column.c
This PR contains stuff for the new 2.39.2 release, based on the current stable/v2.39,  all new patches cherry-picked from the master branch.
> stable v2.39.2

- AUTHORS
- po-man/cs.po
- po-man/de.po
- po-man/es.po
- po-man/fr.po
- po-man/pt_BR.po
- po-man/sr.po
- po-man/uk.po
- po-man/util-linux-man.pot
- schedutils/uclampset.1.adoc
- schedutils/uclampset.c
Update my email address, update docs with a reference to latest kernel doc, and remove a duplicate validation that is better defferred to the kernel to check.
> Uclampset updates

- libblkid/src/superblocks/udf.c
OSTA UDF standard is "profile" of the ISO/IEC 13346 and ECMA-167 standard.
Fix UDF detection and check for "*OSTA UDF Compliant" domain id which
distinguish UDF from all other ISO/IEC 13346 and ECMA-167 filesystems.
> Fix detection of UDF filesystem

- libblkid/src/superblocks/bcache.c
Avoid signed shift out-of-bounds.
Also mark the constants explitly as unsigned instead of casting.
> libblkid: (bcachefs) fix size validation

- login-utils/lslogins.1.adoc
> lslogins: (man) fix -y option formatting

- sys-utils/lscpu-arm.c
> Add Phytium FTC862 cpu model.

- include/env.h
- lib/env.c
- libblkid/src/config.c
- libfdisk/src/partition.c
- libmount/src/cache.c
- libsmartcols/src/print.c
- login-utils/lslogins.c
- sys-utils/ldattach.c
- text-utils/more.c
Some details in the commits themselves.
> fix a bunch of bugs found by -fanalyzer

- libblkid/src/superblocks/bcache.c
> Stable 2.39/bcachefs fixes

- login-utils/login.c
Make sure that terminal and file mode operations are actually performed on an opened TTY, because stdin could be a redirected file. It's clearly an administrator's fault to call login this way, but yet it should not modify file ownership and modes by accident.
Also do not call ioctl or tcsetattr with undefined values. This can happen if the getter calls fail.
Proof of Concept (as root):
1. Create a temporary file with a mode different than TTYPERM.
```
install -m 700 /dev/null /tmp/test
ls -l /tmp/test
-rwx------ 1 root root 0 Sep 21 20:15 /tmp/test
```
2. Run login within a terminal with adjusted stdin.
```
login < /tmp/test
host login:
Hangup
```
3. Check permissions of input file.
```
ls -l /tmp/test
-rw------- 1 root root 0 Sep 21 20:15 /tmp/test
```
> login: Improve terminal handling

- lib/colors.c
- lib/idcache.c
- libblkid/src/probe.c
- libsmartcols/src/cell.c
- login-utils/lslogins.c
- misc-utils/logger.c
- term-utils/script-playutils.c
- text-utils/more.c
- text-utils/rev.c
Descriptions in the commit messages.
Note: I'm submitting these in small batches as they come up to get them out of my queue and make review easier.
> small batch of fixes found by -fanalyzer

- libblkid/src/blkidP.h
- libblkid/src/partitions/partitions.c
- libblkid/src/probe.c
- libblkid/src/superblocks/superblocks.c
- libblkid/src/topology/topology.c
- libfdisk/src/utils.c
- tests/ts/swapon/devname
This is an RFC, as I didn't yet test the impact on actually performed IO.
> libblkid: read data in chunks

- meson.build
- sys-utils/blkpr.c
> misc fixes

- sys-utils/wdctl.c
Also avoid opening device if nowayout is set.
Fixes #2543
> wdctl: use only sysfs if sufficient

- sys-utils/umount.c
- tests/expected/mount/umount-recursive
- tests/ts/mount/umount-recursive
> umount: handle bindmounts during --recursive

- libblkid/src/superblocks/squashfs.c
- libblkid/src/superblocks/superblocks.c
- libblkid/src/superblocks/superblocks.h
- libblkid/src/superblocks/swap.c
- libblkid/src/superblocks/vxfs.c
> libblkid: make enum libblkid_endianness lowercase

- tests/ts/fincore/count
Link: https://lore.kernel.org/util-linux/b8cafd0d89878949705782312dfe800ec2779035.camel@physik.fu-berlin.de/
> fincore: (tests) also use nosize error file

- libblkid/docs/libblkid-sections.txt
- libblkid/src/blkid.h.in
- libblkid/src/libblkid.sym
- libblkid/src/probe.c
- libfdisk/src/wipe.c
>  libblkid: introduce blkid_wipe_all 

- libmount/src/mountP.h
- libmount/src/optstr.c
- libmount/src/tab_update.c
- tests/expected/mount/special-missing-options
- tests/ts/mount/special
Fixes: https://github.com/util-linux/util-linux/issues/2554
Please take a look at the commit message of the second patch.
> fix utab after external update

- disk-utils/fdisk-menu.c
- disk-utils/fdisk.c
- disk-utils/fdisk.h
- tests/expected/fdisk/resize
- tests/ts/fdisk/resize
> fdisk: add support for partition resizing

- misc-utils/logger.c
this PR fix typo: octen should be octet
> Fix typo: octen -> octet

- sys-utils/wdctl.c
> wdctl: properyl test timeout conditions

- disk-utils/mkswap.8.adoc
- disk-utils/mkswap.c
- tests/ts/mkswap/mkswap
Addresses #2359
I don't really think this is a sufficient number of tests, but it seems like there already is a pretty lackluster number of tests for mkswap.
> mkswap: implement --file

- libblkid/src/superblocks/hfs.c
Fixes: https://github.com/util-linux/util-linux/issues/2692
> libblkid: (hfsplus) reduce false positive

- libfdisk/src/gpt.c
> libfdisk: add shortcut for Linux extended boot

- libblkid/src/superblocks/drbd.c
See https://github.com/util-linux/util-linux/issues/2701.
> libblkid: (drbd) reduce false-positive

- sys-utils/setpriv-landlock.c
> setpriv: apply landlock without configuration

- AUTHORS
Added myself to contributors since PR #2451 was approved
Signed-off-by: Cristian Zmole chiarel@tragdate.ninja
> Added Cristian Zmole

- sys-utils/lscpu-virt.c
> sys-utils/lscpu: Unblock SIGSEGV before vmware_bdoor

- sys-utils/lscpu-arm.c
https://lore.kernel.org/linux-arm-kernel/b99a7196-011e-4f08-83ec-e63a690ab919@linux.microsoft.com/T/
> Add Microsoft as vendor and Cobalt 100 core

- bash-completion/enosys
- bash-completion/setpriv
- include/Makemodule.am
- include/seccomp.h
- misc-utils/enosys.1.adoc
- misc-utils/enosys.c
- sys-utils/setpriv.1.adoc
- sys-utils/setpriv.c
- tests/expected/setpriv/seccomp
- tests/ts/setpriv/seccomp
Note: This is for after 2.40 has been released.
> enosys --dump and setpriv --seccomp

- configure.ac
- disk-utils/Makemodule.am
- meson.build
- meson_options.txt
You can now configure with `--enable-static-programs=partx`, this adds the following targets to the makefile: `addpart.static`, `delpart.static`, `resizepart.static`, `partx.static`
> add static partx

- libblkid/src/topology/ioctl.c
Commit 5d71d711d07a ("libblkid: topolicy/ioctl: use union for multiple data types") incorrectly assumed that set_ulong and set_int refer to the type returned by the kernel. Instead the different function pointer names refer to the types of the function pointers.
However all ioctls, except for the later added BLKGETDISKSEQ, return 32bit integers.
This made libblkid also interpret the upper 32bits too, leading to garbage values.
Introduce a new member 'kernel_size' to also handle the 64bit BLKGETDISKSEQ.
Drop data.ul as it is no actually used.
Closes #2904
> libblkid: topology/ioctl: correctly handle kernel types

- libblkid/meson.build
- libfdisk/meson.build
- libmount/meson.build
- libmount/python/meson.build
- meson.build
- meson_options.txt
Same as #2893 but for the `stable/v2.40` branch.
> meson: Only build libmount when required

- login-utils/sulogin.c
Make the root password prompt more technical/formal
> (minor) update sulogin.c

- configure.ac
- meson.build
- misc-utils/Makemodule.am
- tools/all_errnos
- tools/all_syscalls
See the commit message, https://lore.kernel.org/util-linux/31ccace2e5912ffc428e065cd66764088c625c4d.camel@physik.fu-berlin.de/ and #2949 (which this PR replaces)
>  all_errnos/all_syscalls: don't hardcode AWK invocation 

- meson.build
- meson_options.txt
Cherry-pick of #2973 to the `stable/v2.40` branch.
> meson: Add build-dmesg option

- include/strutils.h
- include/xalloc.h
- meson.build
- meson_options.txt
Cherry-pick of #2991 to the `stable/v2.40` branch.
> meson: Add missing build options to allow building on macOS

- disk-utils/fsck.minix.c
- libfdisk/src/dos.c
- libmount/src/context_mount.c
- login-utils/su-common.c
- misc-utils/cal.c
- misc-utils/getopt.c
- misc-utils/lsclocks.c
- sys-utils/hwclock-parse-date.y
- sys-utils/hwclock-rtc.c
- term-utils/agetty.c
- term-utils/ttymsg.c
- term-utils/wall.c
~~I'll add more patches here, so let's keep it as a draft for now.~~
> small fixes issues reported by static analyzers

- disk-utils/mkswap.8.adoc
Follow-up for 7377b0d99560460806eab9efa9d8224d084c2082 (the addition of --file option)
> mkswap.8.adoc: update note regarding swapfile creation

- include/path.h
- lib/path.c
- sys-utils/lsns.c
While inspecting #2982 and #2987, I found some areas where I could improve the readability of the source code.
Here is a figure I used during the inspection and refactoring.
> lsns: minor refactoring

- bash-completion/flock
- sys-utils/flock.1.adoc
- tests/expected/misc/flock
- tests/expected/misc/flock-fcntl
- tests/expected/misc/flock-fcntl-exclusive
- tests/expected/misc/flock-fcntl-fd
- tests/expected/misc/flock-fcntl-no-fork
- tests/expected/misc/flock-fcntl-non-block
- tests/expected/misc/flock-fcntl-shared
- tests/expected/misc/flock-fcntl-time-check
- tests/expected/misc/flock-fcntl-timeout
- tests/expected/misc/flock-fcntl-vs-flock
- tests/ts/misc/flock
Add documentation, bash completion and tests for the newly added `--fcntl` flock option.
> test and documentation for `flock --fcntl`

- include/path.h
- lib/path.c
ul_path_read_buffer() is doing it already.
> lib/path: simplify newline trimming and zero termination

- libmount/python/meson.build
- meson.build
Cherry-pick of #3020 to the `stable/v2.40` branch.
> meson: Fix handling of the Python dependency

- misc-utils/hardlink.1.adoc
- misc-utils/hardlink.c
Based on patch from discussion at https://github.com/util-linux/util-linux/issues/3016
> hardlink: add --prioritize-trees

- sys-utils/lscpu-arm.c
Adding core information for Oryon found in Qualcomm Snapdragon X series SoCs
> Add Qualcomm Oryon ARM core

- term-utils/wall.c
Wall(1) can be compiled with systemd support to read the names of ttys from the systemd session list. However, this may not work on all systems. In case of failure, the best option is to use the traditional utmp method as a fallback.
This commit uses strv (string vector) to collect tty names from both sources (systemd and utmp) and then sends a message to all ttys.
Addresses: https://bugzilla.redhat.com/show_bug.cgi?id=2283049
> wall: always use utmp as fallback

- .github/workflows/cibuild.yml
- tests/ts/lsfd/mkfds-directory
- tests/ts/lsfd/mkfds-symlink
Currently no tests are running on 32bit ARM.
> ci: test on armv7

- Makefile.am
- configure.ac
- pam_lastlog2/src/Makemodule.am
> stable/v2.40: autotools backports

- po/meson.build
Doesn't make much sense to build.
> meson: po: disable if nls is disabled

- libblkid/src/superblocks/apfs.c
The apfs superblock contains a checksum based on Fletcher-64. Validate the checksum to make the probing more robust.
> libblkid: apfs: validate checksums

- text-utils/more.c
more(1) uses more_poll() to monitor data on stdin, stderr, and signals. It is used before read_command(), but this function only reads from stderr. Therefore, if any other non-stderr event occurs, this function will wait on read(). In this case, more(1) will not react to signals anymore. We need to ensure that more(1) only waits in more_poll().
Try
 for x in {1..1000}; do echo "line $x"; done | more
to reproduce.
> more: make sure we have data on stderr

- configure.ac
- meson.build
lsfd (https://github.com/util-linux/util-linux/issues/2945) and enosys improvement
> v2.40 build-sys: check for bpf 

- configure.ac
- meson.build
See https://github.com/util-linux/util-linux/issues/2945
> build-sys: check for bpf

- Makefile.am
- configure.ac
- pam_lastlog2/src/Makemodule.am
Addresses: https://github.com/util-linux/util-linux/pull/3173
> autotools: fix securedir and pam_lastlog2 install

- sys-utils/hwclock-rtc.c
- sys-utils/hwclock.c
- sys-utils/hwclock.h
Addresses: https://github.com/util-linux/util-linux/issues/3180
> hwclock: add -param-index

- tests/helpers/test_mkfds.c
Some factories prints some extra values in addition to the pid of the process opening file descriptors.
Unlike parameters, test_mkfds didn't provide the way to explain the extra values. The new option --output-values/-O provies it.
Example output:
$ ./test_mkfds -O eventfd
NTH DESCRIPTION
0 the pid owning the file descriptor(s)
1 the pid of child process
$ ./test_mkfds -O cdev-tun
NTH DESCRIPTION
0 the pid owning the file descriptor(s)
1 the network device name
> test: (test_mkfds) add -O option for describing output values

- tests/expected/liblastlog2/write_read_user.err
- tests/ts/liblastlog2/write_read_user
Fixes https://github.com/util-linux/util-linux/issues/3234
> tests: (liblastlog2) don't write to stderr and stdout

- lib/fileeq.c
- misc-utils/hardlink.1.adoc
- misc-utils/hardlink.c
From mailing-list.
https://lore.kernel.org/util-linux/5acde6a911f086ab8d2314c5b76eb76075140941.1730139540.git.nabijaczleweli@nabijaczleweli.xyz/T/#t
> hardlink: --list-duplicates and fixes

- bash-completion/hardlink
- misc-utils/hardlink.1.adoc
- misc-utils/hardlink.c
Add --exclude-subtree and --mount command line options.
> hardlink: nftw imrovements

- libsmartcols/meson.build
- meson.build
- meson_options.txt
Sponsored by: Future Crew, LLC
> meson: fix using options

- sys-utils/zramctl.8.adoc
- sys-utils/zramctl.c
Refs: https://docs.kernel.org/admin-guide/blockdev/zram.html#set-compression-algorithm-parameters-optional
> zramctl: add support for `algorithm_params`

- libblkid/src/save.c
Addresses: https://github.com/util-linux/util-linux/pull/3356
> libblkid: fix potential memory leaks

- bash-completion/lsns
> bash-completion: updated lsns bash completion

- term-utils/scriptreplay.c
Addresses: https://github.com/util-linux/util-linux/discussions/3404
> scriptreplay: add key bindings info to --help

- misc-utils/lastlog2.8.adoc
- misc-utils/lastlog2.c
> misc-utils/lastlog2: Add option -a for listing active users only

- sys-utils/lscpu.c
> sys-utils/lscpu: Change object type to SCOLS_JSON_STRING if data == "-"

- bash-completion/irqtop
- bash-completion/lsirq
- sys-utils/irq-common.c
- sys-utils/irq-common.h
- sys-utils/irqtop.1.adoc
- sys-utils/irqtop.c
- sys-utils/lsirq.1.adoc
- sys-utils/lsirq.c
[**from mailing list**]
https://lore.kernel.org/util-linux/20250228161334.82987-1-joe.jin@oracle.com/
> irqtop,lsirq: Miscellaneous enhancements

- tests/helpers/test_sysinfo.c
Now the test checks if the kernel supports the NS_GET_NSTYPE ioctl, but it seems that on some platforms it's implemented but does not work as expected and returns ENOTTY.
> tests: improve test_sysinfo to check for NS_GET_NSTYPE usability

- misc-utils/exch.c
https://www.man7.org/linux/man-pages/man2/rename.2.html Available since Linux 3.15 or glibc 2.28,
add a fallback for older systems.
> exch: fix compile error if renameat2 is not present

- libsmartcols/docs/libsmartcols-sections.txt
- libsmartcols/src/filter-param.c
- libsmartcols/src/libsmartcols.h.in
- libsmartcols/src/libsmartcols.sym
- sys-utils/lsns.c
Let's make things like https://github.com/util-linux/util-linux/pull/3452 simple.
> libsmartcols: add scols_filter_has_holder()

- liblastlog2/src/tests/tst_write_read_user.c
- libmount/src/context.c
- libmount/src/hook_loopdev.c
- login-utils/lslogins.c
- lsfd-cmd/lsfd.c
- sys-utils/hwclock-rtc.c
- sys-utils/unshare.c
- tests/helpers/test_sysinfo.c
just nice-to-have bug fixes, things critical
> bug fixes based on coverity scan

- lib/fileeq.c
This patch fixes a spelling typo in a command message.
> lib/fileeq.c Fix a typo in message.

- meson.build
Fixes: https://github.com/util-linux/util-linux/issues/3475
> meson: fix manadocs for libsmartcols and libblkid

- libmount/src/context.c
- sys-utils/mount.8.adoc
Fixes: https://github.com/util-linux/util-linux/issues/3474
> libmount: fix --no-canonicalize regression

- sys-utils/blkdiscard.8.adoc
Only a minor thing. But if I can make it right, I feel I should.
> Fix minor typo in blkdiscard docs

- disk-utils/mkfs.bfs.c
- use size_t to store strlen() result
- init superblock with the default volume and fsname
- don't use strdup(), it's unnecessary as getopt_long() does not modify arguments
- don't use memcpy() as we need to check string sizes
- restrict verbose output 6 bytes
Addresses: https://github.com/util-linux/util-linux/pull/3488
> mkfs.bfs: fix memory leaks and weak code

- login-utils/last.c
- misc-utils/enosys.c
- misc-utils/findmnt.8.adoc
- misc-utils/hardlink.c
- misc-utils/lsblk.8.adoc
- schedutils/coresched.c
- schedutils/uclampset.1.adoc
- schedutils/uclampset.c
- sys-utils/irqtop.1.adoc
- sys-utils/irqtop.c
- tests/expected/schedutils/coresched-get-cookie-own-pid
- tests/expected/schedutils/coresched-get-cookie-parent-pid
- tests/ts/schedutils/coresched
> man pages and --help improvements

- misc-utils/logger.c
- misc-utils/lslocks.c
- schedutils/chrt.c
- schedutils/taskset.c
- schedutils/uclampset.c
- sys-utils/choom.c
- sys-utils/lsns.c
- sys-utils/prlimit.c
Addresses: https://github.com/util-linux/util-linux/pull/3486 
Suggested-by Thomas Weißschuh <thomas@t-8ch.de>
> treewide: use strtopid_or_err()

- sys-utils/hwclock.c
- sys-utils/lsipc.c
- sys-utils/setpriv.c
- sys-utils/zramctl.8.adoc
- sys-utils/zramctl.c
> textual, helps, etc.

- disk-utils/fsck.8.adoc
- disk-utils/sfdisk.8.adoc
- lsfd-cmd/lsfd.1.adoc
- man-common/in-bytes.adoc
- misc-utils/cal.1.adoc
- misc-utils/findmnt.8.adoc
- misc-utils/kill.1.adoc
- misc-utils/lastlog2.8.adoc
- misc-utils/lastlog2.c
- misc-utils/lsblk.8.adoc
- misc-utils/lslocks.8.adoc
- sys-utils/blkpr.8.adoc
- sys-utils/flock.1.adoc
- sys-utils/hwclock.8.adoc
- sys-utils/losetup.8.adoc
- sys-utils/lscpu.1.adoc
- sys-utils/lsns.8.adoc
- sys-utils/setpriv.1.adoc
- sys-utils/setsid.1.adoc
- sys-utils/tunelp.8.adoc
- term-utils/agetty.8.adoc
- term-utils/setterm.1.adoc
- text-utils/line.1.adoc
> text-fixes (14Apr)

- misc-utils/hardlink.c
The second patch should also be backported into stable/v2.41 and stable/v2.42.
> hardlink: logging and performance improvements

- lsfd-cmd/lsfd.1.adoc
- lsfd-cmd/lsfd.c
- man-common/Makemodule.am
- man-common/hyperlink.adoc
- man-common/meson.build
- misc-utils/findmnt.8.adoc
- misc-utils/findmnt.c
- misc-utils/lsblk.8.adoc
- misc-utils/lsblk.c
- misc-utils/pipesz.1.adoc
- misc-utils/pipesz.c
- misc-utils/uuidd.8.adoc
- misc-utils/uuidd.c
- po-man/po4a.cfg
- sys-utils/irqtop.c
- sys-utils/unshare.c
>  text-fixes (29Apr)

- sys-utils/mount.c
Fixes: https://github.com/util-linux/util-linux/issues/3558
> mount: check for stdout for fstab reload hint

- login-utils/login.1.adoc
- login-utils/login.c
> login: using an avaiable shell while logging in.

- text-utils/more.c
more waits for user commands on stderr, but at the same time, it monitors sigalfd and stdin (for data and POLLHUP|POLLNVAL). We need to temporarily ignore stdin if there is new data waiting for read() (e.g., dmesg | more); otherwise, more_key_command() will end in a busy loop.
Fixes: https://github.com/util-linux/util-linux/issues/3634
> more: temporarily ignore stdin when waiting for stderr

- include/Makemodule.am
- include/configs.h
- include/pathnames.h
- lib/Makemodule.am
- lib/configs.c
- lib/meson.build
- term-utils/agetty.c
This PR should solve:
https://github.com/util-linux/util-linux/issues/3669
and is a replacement for PR
https://github.com/util-linux/util-linux/pull/3749
> libcommon: added lib "configs" for parsing configuration files in the correct order; agetty: using this lib

- meson.build
> Fix meson "does not support the `+` operator" error.

- lib/netlink.c
I found several issues in the new netlink code. Here are fixes.
> Fix new netlink code issues
