misc-utils/Makemodule.am
Noticed on openSUSE 13.1:
util-linux-2.26/misc-utils/logger.c:735: undefined reference to `sd_booted'
Introduced in d77dc29e.
CC: Sami Kerola <kerolasa@iki.fi>
=> logger: link libsystemd-daemon.so

misc-utils/logger.c
The timestamp is written as
2015-03-04T15:02:02.566782+0100
unfortunately, this is not an RFC3339 timestamp as demanded by rfc5424.
The colon in the time offset field is missing. The correct timestamp is
2015-03-04T15:02:02.566782+01:00
(Note "+0100" vs. "+01:00")
closes https://github.com/karelzak/util-linux/issues/159
=> logger: fix invalid timestamp in rfc5425 format

libblkid/src/superblocks/zfs.c
Try to use all the possible uberblock locations.
Reviewed by @behlendorf 
My use case: seems that cryptsetup is trying to detect if opening the crypted device was successfull by examining the new block device with blkid. In my case this works for regular zfs vdevs but not for cache vdev, which has only four uberblocks total spread across all four labels. The current blkid zfs detection uses only first two labels. So I've changed the code to examine all four of them.
=> blkid: make zfs detection more robust

misc-utils/logger.c
The message format when writing to local sockets is inconsistent. Example:
```
$ ./logger --stderr test
<5>Mär  4 11:03:30 logger: test
$ ./logger -u /dev/log --stderr test
<5>1 2015-03-04T11:03:31.699841+0100 ubuntu1404esp rger - [timeQuality tzKnown="1" isSynced="1" syncAccuracy="29000"] test
```
The regression was introduced with 4de2e8a03859aaab2c25dc98f33409cd28de6acc
As far as the commit comments and man page indicates, this was meant to affect
remote system logging only, but it also affects local logging when the -u
option is given.
This causes problems with receivers who do not expect full-blown RFC format
on the log socket, like rsyslog. In consequence, this can also affect
log analysis programs and invalidate some of their results.
The patch corrects the behaviour so that the …
=> logger: fix inconsistent format regression when logging locally

misc-utils/logger.c
Please check commit 940a14a: I generate the proper framing with a compromise among different options. Please consider if that is appropriate for the util-linux project. If not, I would suggest using writev(2) and  add a writev_all() function to the framework. I would be willing to code that if desired. But so far, it looks like unnecessary complexity to me.
closes https://github.com/karelzak/util-linux/issues/166
=> logger: bugfix for invalid TCP framing

misc-utils/logger.1, misc-utils/logger.c
rfc5424 was seriously broken.
This patch set:
1. fixes the issues
2. introduces a new capability to set the RFC5424 MSGID
3. fixes an unrelated issue in the man page
I thought 2. is good to have for users of RFC5424, but you can leave it out without side effects if you want.
closes https://github.com/karelzak/util-linux/issues/170
=> fix issues in RFC5425 formatter

include/xalloc.h
Now that I got my CFLAGS fixed, I see some unncessary warnings.
This is primarily cosmetic, albeit it also provides an (only very slight) improvement in compile time error checking.
If you like this patch, I could check for some other occurences - I have seen some more when building all tools. Just don't wanted to waste time if you are not interested in that kind of patch...
=> silence compiler warning

.travis-functions.sh, misc-utils/logger.c, tests/expected/logger/errors-check_socket, tests/expected/logger/errors-invalid_socket, tests/expected/logger/formats-check_socket, tests/expected/logger/options-check_socket, tests/functions.sh, tests/ts/logger/errors, tests/ts/logger/formats, tests/ts/logger/journald, tests/ts/logger/options
Maybe later we could consolidate the socket initialization into a common function inclusive netcat fallback.
=> logger tests do not need /dev/log but socat

tests/ts/logger/errors, tests/ts/logger/formats, tests/ts/logger/options
$TS_OUTDIR may be too long for sockaddr_un.sun_path. Noticed on travis
in distcheck.
=> tests: fix logger device pathname too long

misc-utils/kill.1
kill adds a verbose option to print the pid(s) and the signal. It is
added to man page here.
=> kill: Add verbose to man page.

tests/ts/script/race
This reverts commit 8ba3f35e07f736a0165669ac787b016b4311eb29.
This test is not too slow anymore and BTW since last script refactoring
it does work now even on slow/heavy-loaded systems.
=> Revert "tests: start script/race test only when --force specified"

sys-utils/mount.8
According to https://lwn.net/Articles/245002/ and checking Linus' git master fs/inode.c it's obvious nodiratime is redundant when mounting with noatime. Clarify that in the man page.
=> mount.8: Clarify relation between noatime and nodiratime

autogen.sh, m4/ul.m4
I needed to use libmount/test_mount_monitor on a CentOS 6 system, ended up with these patches enabling the checked out sources to be built on CentOS 6. Please review.
=> built-sys: allow to build on RHEL6

misc-utils/cal.1, misc-utils/cal.c
The first commit makes `-n 3` distinct from `-3` such that the former starts with the current month and the latter shows the last, current, and next months, as intended.
The second commit allows date spanning to work with arbitrary ranges, e.g. `cal -n 5 --span` will show the previous two months, current month, and next two months.
=> Add --span and fix -n 3 behaviour

libsmartcols/src/table_print.c
Reference: https://github.com/karelzak/util-linux/issues/240
=> scols/table_print: restore old stream after printing to str

libsmartcols/src/libsmartcols.sym
In commit 6d6b6d185e7427e2b5590349edd76d019b0fe920 we forgot to
add this function to sym file and now we are getting
undefined symbol: scols_column_is_hidden
=> libsmartcols: add scols_column_is_hidden into sym file

configure.ac
This pull request is a new version of pull request #234 by Alexey Brodkin.
In case of uClibc librt depends on libpthread. In particular
timer_create() function uses pthread_XXX(). That means in case of static
builds it's required to link not librt alone but together with libpthread. So
if checking timer_create function in librt fails, it is necessary to check if
timer_create function successfully links with "-lpthread".
That issues was spotted in Buldroot autobuilder failures:
http://autobuild.buildroot.net/results/759/75960db671807091fe9155aee9e46a6245e32590/
http://autobuild.buildroot.org/results/112/112e8b85783f5aaba42a937a6eb064317615a21b/
Signed-off-by: Lada Trimasova <ltrimas@synopsys.com>
=> buildsys: fix static configuration and building

libmount/python/Makemodule.am
This fixes a failure of `make install DESTDIR=...` when trying to relink pylibmount against libmount.la.
libtool will look for libmount.so under ${DESTDIR}/${libdir} just fine, but if it is not yet present, it will assume it is a system installed library and use -lmount instead.
But this means it depends on the install order. And, considering that pylibmountexec < usrlib_exec (in lexicographic order), the Makefile will be generated to process pylibmountexec first, which will typically generate the failure below on the `make install` step:
```shell
libtool: install: warning: relinking `pylibmount.la'
libtool: install: (... libtool --mode=relink gcc -o pylibmount.la \
-rpath /usr/lib/python2.7/dist-packages/libmount \
libmount/python/*.lo libmount.la ... -lpython2.7 \
-inst-prefix-dir …
```
=> build-sys: Properly order install dependencies of pylibmount

sys-utils/hwclock.8.in, sys-utils/hwclock.c
Me and my colleguae were rather confused by the output of version 2.25.2 so I started looking at the code. The addition of microseconds or fractions of a second is undocumented until now. 
The proposed change in code, is an attempt to better conform to I18n of decimal separators. It usually gives I18n problems to assemble parts of a meaning in C code. Just my 2 € .
=> Change of output format and documentation.

Makefile.am, configure.ac, libmount/python/Makemodule.am
@karelzak @rudimeier 
This is possibly a better fix than the one introduced in #247 (so I'm reverting that one here since it's no longer necessary.)
It uses a workaround suggested in http://stackoverflow.com/a/8643550 to introduce the make rule without having automake try to interpret it.
I tested the issues that tripped me up before in https://github.com/filbranden/util-linux/commit/9aeb4952cce8495843f82895a279c202dcbdf778
=> Properly order install dependencies of pylibmount (take 2)

.travis-functions.sh
Commit 324330aca6443d ("build-sys: Properly order install dependencies of pylibmount") from PR #274 introduces a proper make dependency for the install rules, in a way that the workaround is no longer necessary.
Let's check that this PR commit passes Travis-CI, that means it should be good to submit...
@rudimeier @karelzak
=> travis: Remove workaround for libtool install of pylibmount

libsmartcols/src/table_print.c
Reference: https://github.com/karelzak/util-linux/issues/279
=> libsmartcols: print title only with SCOLS_FMT_HUMAN

.travis-functions.sh, tests/functions.sh, tests/run.sh, tests/ts/blkid/low-probe
Regarding the declined patches from pull request #244 I try it again without changing the default non-parallel case.
On 05 January 2016, karelzak wrote:
> Applied, but without:
> * tests: remove non-parallel case for result output
> * tests: print test name instead of description …
> 
> I really want to have human friendly structured non-parallel output where I have information what test is just running (so output in ts_init and ts_init_subtest).
Yes, it looks really good if nothing goes wrong. But it's a real mess if there is a mix with stdout/stderr from a test script. This happens usually very often if a test fails or if test progs produce warnings or if you add debugging output.  
Note that due to a (fixed) bug we have never seen the nice non-parallel output for some years. …
=> tests: parallel results output again

text-utils/hexdump.c
As documented in the manual and the usage info, the long options `--one-byte-char`, `--canonical`, and `--two-bytes-octal` should not accept any arguments.
=> hexdump: certain long options should not accept arguments

tests/ts/mount/fstab-btrfs
This one was missing in the other pull request.
=> tests: skip btrfs tests if version too old

.gitignore, sys-utils/setarch.c, tests/expected/misc/setarch, tests/expected/misc/setarch-options, tests/expected/misc/setarch-uname26, tests/expected/misc/setarch-uname26-version, tests/ts/misc/setarch
As discussed on mailing list this patch-set tries to fix tests if --uname-2.6 is not
supported.
=> setarch: test improvements

sys-utils/flock.1, sys-utils/flock.c
When guarding a command with flock it is sometimes preferable to not leave a flock process waiting around for the command to exit.
Karel,
Would you be prepared to accept a patch along the lines of this RFC?
If so, I'll work up the options handling and documentation updates.
Design decision: Would you prefer that we refer to this as "no-fork" or "exec-only" or something else. What options flag? Perhaps -F/--no-fork?
Thanks.
=> Introduce no-fork / exec-only option.

libmount/src/optstr.c, tests/expected/libmount/optstr-append-empty-value, tests/expected/libmount/optstr-deduplicate-empty, tests/expected/libmount/optstr-prepend-empty-value, tests/expected/libmount/optstr-remove-empty-value, tests/expected/libmount/optstr-set-empty, tests/expected/libmount/optstr-set-new-empty, tests/expected/libmount/optstr-set-new-end-empty, tests/functions.sh, tests/run.sh, tests/ts/libmount/optstr
Recent mount (since the switch to libmount in v2.22) drops the '=' in mount options that are set to an empty value.  For example, the command line below will be affected:
```
```
Fix that by preserving an empty string in the options passed to the mount(2) syscall when they are present on the command line.
Add test cases to ensure empty string handling is working as expected and in order to prevent regressions in the future.
Also tested manually by stracing mount commands (on a kernel which accepts a special extra option, for testing purposes.)
Before this commit:
```    
mount("tmpfs", "/mnt/tmp", "tmpfs", MS_MGC_VAL, "myarg") = -1 EINVAL (Invalid argument)
```
After this commit:
```
mount("tmpfs", "/mnt/tmp", "tmpfs", MS_MGC_VAL, "myopt=") = 0
```
All test cases pass, including newly …
=> libmount: Preserve empty string value in optstr parsing

lib/blkdev.c
DIOCGMEDIASIZE is supported and available since FreeBSD 5, it may
make sense to kill the backwards-glue completely instead.
=> blkdev: guard against missing DIOCGDINFO on FreeBSD 11

.travis-functions.sh
Since a few days travis OSX seems to have a bad libtool package:
$ glibtoolize --version
/usr/local/bin/glibtoolize: line 406: /usr/local/Library/ENV/4.3/sed: No such file or directory
Exporting SED is a simple fix. Otherwise we could have also re-installed libtool:
brew uninstall libtool
brew install libtool
=> travis: fix OSX, glibtoolize could not find sed

libsmartcols/src/symbols.c
Signed-off-by: Igor Gnatenko <ignatenko@redhat.com>
=> smartcols/symbols: free cell_padding in unref()

libsmartcols/src/table.c
"Automatical" is archaic form of "automatic".
=> trivial: s/automatical/automatic/g

libsmartcols/src/libsmartcols.h.in, libsmartcols/src/symbols.c
=> libsmartcols: be consistent, use 'sy' for symbols

tests/functions.sh, tests/ts/blkid/mbr-wholedisk, tests/ts/blkid/md-raid1-part, tests/ts/eject/umount, tests/ts/fdisk/align-512-4K, tests/ts/fdisk/align-512-4K-63, tests/ts/fdisk/align-512-4K-md, tests/ts/fdisk/align-512-512-topology, tests/ts/libmount/context, tests/ts/libmount/context-py, tests/ts/libmount/context-utab, tests/ts/libmount/context-utab-py, tests/ts/libmount/tabfiles-tags, tests/ts/libmount/tabfiles-tags-py, tests/ts/losetup/losetup-blkdev, tests/ts/minix/mkfs, tests/ts/mount/umount-alltargets, tests/ts/mount/umount-recursive, tests/ts/partx/partx, tests/ts/sfdisk/dos, tests/ts/sfdisk/gpt, tests/ts/sfdisk/movedata, tests/ts/sfdisk/resize, tests/ts/wipefs/wipefs
- auto cleanup on test exit
- Add smart timeout: Newer openSUSE systems on OBS failed to rmmod
almost always. udevadm settle does not seem to have any affect.
- now tests will fail if rmmod fails
=> tests: consolidate rmmod scsi_debug

tests/expected/blkid/md-raid1-whole, tests/ts/blkid/md-raid1-whole
I have not validated if this is just a temporary kernel bug or if kernel has really changed that on purpose.
=> test: fix raid1 minimum I/O size

libmount/python/Makemodule.am
Don't know why this was added in d78df0ac but it can't be right that
libmount/python removes these files in the toplevel builddir. Moreover
I've never seen such *.img files appearing during build at all.
=> build-sys: don't clean *.img files

disk-utils/mkfs.minix.c, tests/expected/minix/mkfs-v2i65535, tests/ts/minix/mkfs
ninodes in the superblock needs to be set after inodes is checked
against MINIX_MAX_INODES otherwise a value larger than MINIX_MAX_INODES
can be attempted to be stored in the superblock.
Without this change the command "mkfs.minix -2 -i 65530 <dev>" would
write a minix superblock with ninodes set to 0.
Signed-off-by: Nate Clark <nate@neworld.us>
=> disk-utils/mkfs.minix: Set ninodes after checking max

libblkid/src/superblocks/minix.c
Swap partitions with a uuid which contains a minix magic number can be mistaken by blockid as minix partitions. This causes blockid to error out with a message like "/dev/sdb3: ambivalent result (probably more filesystems on the device, use wipefs(8) to see more details)"
These patches try to make it less likely for a swap partition or other partition to be mistaken as a minix partition.
A v1 or v2 offending uuid will look like 35f1f264-<minix magic>-471a-bc85-acc9f4bc04a3 where minix magic is one of 137f, 7f13, 138f, 8f13, 2468, 6824, 2478 or 7824.
=> libblkid/minix: Swap partitions can be mistaken as minix

libsmartcols/src/table_print.c
=> libsmartcols: remove dead checks

term-utils/script.c
I suspect this syntax error isn't triggered much, looking at the date of its introduction. Actually found this through a build system misconfiguration :)
=> term-utils/script: fix typo leading to syntax error

term-utils/agetty.c
I found a small memory leak in agetty, when parsing an issue file which contains the \S{...} escape sequence. The string returned from read_os_release() is strdup()'ed but never freed by the caller.
On a system that uses an issue file containing this escape sequence one could in theory press/send an infinite number of newlines at the login prompt to continuously leak memory, because agetty reprints the issue file and prompts again for each empty input line and leaks said memory for each iteration.
=> agetty: fix a memory leak when parsing \S in issue files

sys-utils/ipcs.c, tests/ts/ipcs/functions.sh, tests/ts/ipcs/limits2
Still no large integer support but on overflow we print now
the largest possible value, maybe even the largest one which
makes sense at all.
So on x86_64 systems we'll see now:
$ echo "4503599627370496" > /proc/sys/kernel/shmall
$ ipcs -m -l | grep "max total"
max total shared memory (kbytes) = 18014398509481980
rather than this:
$ ipcs -m -l | grep "max total"
max total shared memory (kbytes) = 0
=> ipcs: make shmall overflow a bit less worse

term-utils/script.c
The -q switch of script command doesn't supress the prompt message for beginning in the file. This is the fix to that.
(Re-create to add sign-off. Was #426 )
Do I need to email the mailing list?
Signed-off-by: Rui Zhao (renyuneyun) <renyuneyun@gmail.com>
=> term-utils/script: fix start message showing in output file when -q is on

term-utils/script.c
- move '\n' to fprintf
- use `timeutils/strtime_iso()` instead of `strtime()`
Signed-off-by: Rui Zhao (renyuneyun) <renyuneyun@gmail.com>
The translations will need to update because of the position change of the `\n` character.
Not sure whether the includes (those related to time) will need to be optimized or not.
Close #427
=> [term-utils/script] fix the position of newline in the time output of 'script'

lib/timer.c
The first fixes a probably-harmless but rather confusing bug. The second may not be worth the complexity, so consider it an RFC.
=> two lib/timer.c fixes

include/colors.h
This affected cfdisk, fdisk, sfdisk, cal, dmesg and hexdump.
=> lib/colors: Fix bug where help text was not being translated.

sys-utils/hwclock.8.in, sys-utils/hwclock.c
For symmetry with --utc where a short form is already allowed, and to
make it easier to write scripts that will work with both util-linux'
and busybox' hwclock, make -l another spelling of
--localtime. (Busybox also understands --localtime, but only if it has
been compiled with long option support.)
=> hwclock: allow -l as alias for --localtime

misc-utils/rename.c
It has long bothered me that the rename command silently overrides existing files, and I believe that I have lost a number of files because of it. So I added the option -o that stops it from doing that. In my opinion this should be the default behavior (to be non-destructive), but it is probably too late for that.
=> Added --no-override option to rename.

libmount/python/context.c
Fixes a segfault observed with python3.6.
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  vgetargskeywords (args=0x7f61ed7ca048, keywords=0x7f61ec3bb630, format=<optimized out>, format@entry=0x7f61ebe13057 "|sssskssO!O!i", kwlist=kwlist@entry=0x7fffdb972770, p_va=p_va@entry=0x7fffdb9725e0, flags=flags@entry=0) at Python/getargs.c:1631
1631	        if (!*kwlist[len]) {
Backtrace
=========
#0  vgetargskeywords (args=0x7f61ed7ca048, keywords=0x7f61ec3bb630, format=<optimized out>, format@entry=0x7f61ebe13057 "|sssskssO!O!i", kwlist=kwlist@entry=0x7fffdb972770, p_va=p_va@entry=0x7fffdb9725e0, flags=flags@entry=0) at Python/getargs.c:1631
#1  0x00007f61ed25010b in PyArg_ParseTupleAndKeywords (args=<optimized out>, keywords=<optimized out>, format=format@entry=0x7f61ebe13057 …
```
=> pylibmount: NULL terminate kwlist in Context_init

disk-utils/fsck.8, disk-utils/fsck.c, disk-utils/mkfs.cramfs.8, disk-utils/mkfs.cramfs.c, include/c.h, login-utils/chsh.c, login-utils/login.1, login-utils/login.c, login-utils/lslogins.c, misc-utils/blkid.c, misc-utils/test_uuidd.c, misc-utils/uuidd.c, misc-utils/whereis.1, misc-utils/whereis.c, sys-utils/dmesg.c, sys-utils/setarch.c, text-utils/hexdump.c, text-utils/more.1, text-utils/more.c
The major goal is to avoid printing usage/help messages on stderr.
This is the preparing first part of a bigger patch-set. There are some minor bug fixes and finally we add --help options to all our commands (just 5 commands were missing it).  
The next completing patch-set (part 2) will be more invasive but even more trivial.
=> usage cleanup part 1 

disk-utils/fsck.c, disk-utils/fsck.cramfs.c, disk-utils/fsck.minix.c, disk-utils/mkfs.cramfs.c, disk-utils/mkfs.minix.c, include/strutils.h, lib/strutils.c, misc-utils/blkid.c, misc-utils/findfs.c, sys-utils/flock.c, sys-utils/hwclock.c, sys-utils/mount.c, sys-utils/tunelp.c, sys-utils/umount.c
As discussed on the mailing list, most importantly we remove the non-working define STRTOXX_EXIT_CODE.
=> Fix some exit codes (strutils.h and friends)

.travis-functions.sh, Makefile.am, tools/Makemodule.am
OMG don't know why I removed --disable-makeinstall-chown. Took me a lot of time to figure out why travis was broken.
=> tools: fix chown mistake add checkusage.sh to the dist

lib/randutils.c
1) Use the previous “read from /dev/urandom” codepath on kernels which don't support the getrandom() syscall.
2) Check that getrandom() read the number of bytes requested.
=> lib/randutils.c: Improvements for getrandom usage

misc-utils/rename.1
Command for renaming foo? should add 2 zeros to make all the file names have 3 digits as described in the example results.
=> Example for renaming foo? does not work as described

libmount/python/fs.c
The current implementation would return always 0, as it is the return
code of mnt_fs_get_propagation.  Change the implementation to raise an
exception on an error and return the propagation flags otherwise.
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
=> libmount: fix Python get_propagation

sys-utils/mount.8
Fixes https://bugs.launchpad.net/ubuntu/+source/util-linux/+bug/1712433 
Signed-off-by: Liam Ryan <liamryandev@gmail.com>
=> Fixed typo in mount.8

bash-completion/unshare, include/Makemodule.am, include/signames.h, lib/Makemodule.am, lib/signames.c, misc-utils/kill.c, sys-utils/unshare.1, sys-utils/unshare.c
This allows to conveniently kill the entire process tree
below the forked program, a common problem when scripting
tasks that need to reliably fully terminate without leaving
reparented subprocesses behind.
The example added to the man page shows the most common use.
Implemented using `prctl(PR_SET_PDEATHSIG, ...)`.
=> unshare: Add --kill-child option

include/carefulputc.h
Signed-off-by: Nik Nyby <nikolas@gnu.org>
=> Fix typo in carefulputc.h

bash-completion/fsck
When the bash-completion for fsck runs `find -L /dev/ -type b` it descends into `/dev/fd` after opening `.` as file descriptor 3.  This causes find to search through `/dev/fd/3/` which includes everything below
the current directory, which can take a very long time.
To avoid this, prune `/dev/fd` in the find expression.
Thanks for considering,
Kevin
P.S.  If you'd like strace information to see exactly how `find` descends into `/dev/fd` let me know.
=> bash-completion: Exclude /dev/fd from fsck find

libfdisk/src/script.c
Without this, 'sfdisk -d' with certain filenames would lead to
reading an 's' from the 'type' field in fdisk_reset_labelitem
and cause a crash due to prematurely freeing the 'data.str' field.
Signed-off-by: Roddy Shuler <roddy@endlessm.com>
=> libfdisk: Fix uninitialized structure

sys-utils/lscpu.c
At least on the Sydney Amazon EC2 region this file doesn't show up,
and the fatal exit code causes the rest of the useful information
to not show up.
=> lscpu: Treat read failure on Xen Hypervisor properties as non-fatal

libblkid/src/superblocks/udf.c
libblkid: udf: Stop scanning Volume Descriptors after we found Terminating Descriptor
Terminating Descriptor is the last descriptor in Volume Descriptor
Sequence. After it there can be unrecorded or empty sectors which we do not
have to scan.
___
libblkid: udf: Really try to read only first LVID
We do not want to scan whole LVID sequence.
=> libblkid: udf: Do not read more sectors as needed

sys-utils/Makemodule.am, sys-utils/lscpu-arm.h, sys-utils/lscpu.c, tests/expected/lscpu/lscpu-armv7
Since the kernel developers have refused to make /proc/cpuinfo user
understandable, implement mapping in userspace. lscpu is available for
most users via util-linux, so store the information here.
Signed-off-by: Riku Voipio <riku.voipio@iki.fi>
=> lscpu: Decode ARM CPUs

configure.ac, include/nls.h, misc-utils/cal.c
cal: use ```ALTMON_*``` and ```_NL_ABALTMON_*``` constants to display
months in a standalone form correctly.  These constants have just
been newly added to glibc.  ```ALTMON_x``` has been used in BSD family
since 1990s and has been accepted as the future POSIX extension.
```_NL_ABALTMON_*``` is exclusively a GNU extension but it is expected
to be added to POSIX in future.
More info: https://sourceware.org/bugzilla/show_bug.cgi?id=10871
=> cal: Use ALTMON_* correctly

sys-utils/mount.8
The closest I can get is with `mount`, so refer to that instead.
mount: /proc: none already mounted or mount point busy.
umount: /proc: target is busy.
umount: /proc: target is busy.
Signed-off-by: Alan Jenkins <alan.christopher.jenkins@gmail.com>
=>  mount(8): umount does not (anymore?) say `none busy'

sys-utils/zramctl.8, sys-utils/zramctl.c
The changes add the support for new compression algorithms in zramctl utility. Namely, lz4hc, deflate, and 842 are supported compared to the previous state.
=> New compression algorithms in zramctl utility.

misc-utils/findmnt.8
The option list was unevenly aligned, which mildly annoyed the pedant in me.
=> findmnt.8: remove spurious spaces before "--tree" and "--verbose"

sys-utils/lscpu-arm.c
Add a handful of more rare cores. Broadcom Brahma cores are
used in Access Points and Faraday was used on some Network
Storage Devices.
Signed-off-by: Riku Voipio <riku.voipio@iki.fi>
=> lscpu-arm: add Faraday And Brahma cores

sys-utils/setpriv.1
The example given in the man page didn't work. Judging by commit
db663995bd93e170a43b1a7050c7a738782dabfb, --inh-caps= used to be called
--caps= but the man page was not updated after the change was made.
=> setpriv: fix manpage typo

.travis-functions.sh, .travis.yml, tests/functions.sh, tests/run.sh, tests/ts/libmount/context, tests/ts/minix/mkfs, tests/ts/mount/label, tests/ts/mount/umount-alltargets, tests/ts/mount/umount-recursive, tests/ts/swapon/label
To begin with, the parallel checks for user root still seem a bit unstable before and after this patch-set, at least on my personal devel machine. Most issues doesn't seem to be flock related but slow kernel/udev events or whatever it is.  Adding "udevadm settle" does not help for all cases. The issues get worse when machines are under heavy load. --parallel is just an amplifier here.
Anyways, this pull request should make things a bit better and more portable.
The major Linux bugfix here is patch 4 "tests: don't use unlocked resources". Though the bug would be shadowed by the next patch as well.
Finally we are enabling parallel root tests on travis, Let's see.
=> Test locks improvements

sys-utils/setpriv.1
Having read [Don't abuse su for dropping user privileges](https://jdebp.eu/FGA/dont-abuse-su-for-dropping-privileges.html), I've been wondering how to correctly use su/runuser in init scripts, cron jobs and so on. I've found almost no use of setpriv on Debian code search nor across GitHub. Perhaps some examples might help potential users feel a bit more confident using the command?
Note that I've not copied the example of using --inh-caps=-all from elsewhere in the man page. My testing indicates that it's not necessary to include this option to mimic su's behaviour...
uid: 1000
euid: 1000
gid: 1000
egid: 1000
Supplementary groups: 4,27,115,1000
no_new_privs: 0
Inheritable capabilities: chown,dac_override,dac_read_search,fowner,fsetid,kill,setgid,setuid,setpcap,linux_immutable,net_bind_serv …
=> Flesh out setpriv man page a bit

sys-utils/lscpu.c
When cpu#0 is offline, atof(NULL) is called which causes
a segfault or endless loop depending on implementation
circumstances. So instead of implicitely assumping that the
first cpu is always available, do the presence checks for
all including the first one.
=> Avoid crash in min/max caculation when cpu#0 being offline

misc-utils/rename.1, misc-utils/rename.c
Backport of #607 (with one less unnecessary commit).
=> Backport of "rename: fix/reverse the semantics of --no-overwrite in --symlink mode"

misc-utils/rename.1, misc-utils/rename.c
The previous behaviour was to overwrite a symlink only when the new
destination did not exist, i.e. to avoid creating a symlink to an
existing file!  It had not been documented and it seems
counter-intuitive to me.  So the new behavior protects symlinks pointing
to existing targets from being changed.
=> rename: fix/reverse the semantics of --no-overwrite in --symlink mode

misc-utils/rename.1, misc-utils/rename.c
This fixes a bug introduced by commit fabb90676 ("Added --no-override
option to rename.", 2017-05-27) where the fallthrough meant to let
--no-act set --verbose was changed to set --no-override (the previous
code was too smart).                                        
Do not let --no-act set --verbose anymore but update the manual to
recommend adding option --verbose.  This is to be able to make --no-act
detect only non existing file arguments (in a future commit).
=> rename: fix --no-act to not set --no-overwrite

misc-utils/rename.c
This change makes rename detect inexisting files given on the command
line and consider them faliures.  This is particularly useful with
--no-act (to detect extraneous arguments).
It also prevents skipping non existing files (when the modified name
happens to exist).  This makes --verbose not print skipping messages of
false positives (the access error is printed instead).
This pull request is based on top of #610.
=> rename: check source file existence early

po/pt_BR.po
Translation was using '-n' instead of '-l'
Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>
=> po: pt_BR: fix fallocate '-l' help msg

misc-utils/findmnt.8, misc-utils/findmnt.c, misc-utils/findmnt.h
While looking for a way to show only non-pseudo filesystems with findmnt I came across [this thread](https://marc.info/?l=util-linux-ng&m=144975017926320&w=2). As far as I can tell no similar options have been implemented, so I went ahead and added `--pseduo` and `--real` flags. I can probably add a `--net` flag, too, but haven't investigated what all that would require yet; I also thought I'd see what the feedback for these two was before really digging into it.
Regarding whitespace: I fixed a couple of places that had spaces instead of tabs and a trailing tab that I assumed to be whitespace errors. If that is intentional let me know and I can drop that commit. I'm also curious about what to do with the ugly addition to `excl[]`.
=> Add options to filter by pseudo, real filesystems

term-utils/script.c
Noticed on 32bit builds. Types changed in 0da73643.
=> script: fix printf format specifiers

disk-utils/cfdisk.c
Seen on OSX 10.13, xcode 9.3.
```C
disk-utils/cfdisk.c:1860:45: error: format specifies type 'uintmax_t' (aka 'unsigned long') but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
DBG(UI, ul_debug("get_size (default=%ju)", *res));
~~~    ^~~~
%llu
disk-utils/cfdisk.c:267:60: note: expanded from macro 'DBG'
#define DBG(m, x)       __UL_DBG(cfdisk, CFDISK_DEBUG_, m, x)
^
./include/debug.h:67:4: note: expanded from macro '__UL_DBG'
x; \
^
disk-utils/cfdisk.c:1889:25: error: incompatible pointer types passing 'uint64_t *' (aka 'unsigned long long *') to parameter of type 'uintmax_t *' (aka 'unsigned long *') [-Werror,-Wincompatible-pointer-types]
rc = parse_size(buf, &user, &pwr);      /* parse */
^~~~~
./include/strutils.h:15:51: note: passing argument to …
```
=> cfdisk: fix compiler warnings, follow-up 7085f1e4 (#636)

lib/exec_shell.c
When SHELL env is not set, it cause `xstrdup(NULL)` be executed, and result in weird error message `
.: applet not found` instead of DEFAULT_SHELL being used.
=> exec_shell: prevent ".: applet not found" error when SHELL env is NULL

libblkid/src/Makemodule.am, libblkid/src/superblocks/apfs.c, libblkid/src/superblocks/superblocks.c, libblkid/src/superblocks/superblocks.h
Does not support anything to do with APFS volumes or similar. Just reports when it sees an APFS container on a disk.
=> libblkid: Add very basic APFS recognition

misc-utils/logger.c
The normal journald functions add the location in the C source code files to
the log messages. This is nice for a big C based project, but logger is used in
scripts so it would be more useful to let users specify the location in the
script by adding the CODE_FUNC, CODE_FILE and CODE_FILE fields to the log
message.
It is already possible to do this, but it will result in two versions of these
fields: one for the location in logger.c and one for the location in the
script.
=> logger: Define SD_JOURNAL_SUPPRESS_LOCATION.

libmount/python/fs.c
Quick-and-dirty fix for tabfiles-py-parse-mtab failure (issue #489 ).  PySys_WriteStdout() will automatically truncate any '%s' format token longer than 1000 bytes (like the tab sequence in our prefabbed mtab), at least as far back as 2.7.15.
=> * break up large strings for PySys_WriteStdout()

sys-utils/lscpu-arm.c
Looks like a typo in the original commit.  Documentation showing actual ID here: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0646b/CIHCAGHH.html
=> lscpu: fixed part ID for ARM Cortex-M7

include/pathnames.h
Use several locations for built in default for motd to allow for
e.g. run time generated motd without having to modify config files.
login.c already splits by colon.
/usr/share/misc/motd
- chould be shipped by distributions
/run/motd
- potentially run time created file with dynamic information
/etc/motd
- for the admin fill with local information
Signed-off-by: Ludwig Nussel <ludwig.nussel@suse.de>
=> Add built in fallbacks for motd file

sys-utils/fallocate.c
This broke compilation when `HAVE_POSIX_FALLOCATE` was undefined. The typo dates to the original `posix_fallocate` support added in commit 833f9a7aae713278eec5f85266597482f18c7370.
=> fallocate: add missing semicolon

tests/ts/uuid/oids
oids test did not check if uuidgen was available.
oids test was also calling uuidgen from PATH which could result
in wrong results if uuidgen from a previous util-linux installation
was used.
With this commit we will check if uuidgen was built and make sure
that we only call the uuidgen binary we just built. If uuidgen is
not available we will skip this test.
=> tests: run oids test only when uuidgen tool was built

include/c.h, include/xalloc.h
Let the compiler optimize based on the knowledge that the return value will
never be null.
Reference: https://patchwork.ozlabs.org/patch/281112/#631159
=> include/c: use returns_nonnull function attribute in xalloc.h

sys-utils/switch_root.c
before this change, switch_root would try to parse all arguments, including `initargs`, using getopt, which would lead to an 'unrecognized option' error when trying to pass a flag to the init program
=> fix a bug where switch_root would erroneously try to parse initargs

include/c.h
Karel pointed out previous commit could have been better in github feedback,
so lets use the version check macro instead of compare versions directly.
Previous-commit: f1b327f8d5c8de7bf7fae99e85765d0954a25bac
Reference: https://github.com/karelzak/util-linux/pull/704#issuecomment-432605211
=> include/c: check returns_nonnull function attribute with __GNUC_PREREQ

libsmartcols/src/grouping.c, login-utils/lslogins.c, misc-utils/lsblk-devtree.c, misc-utils/lsblk.c, text-utils/hexdump-parse.c
Nothing special, just compiler warning fixes. Well, maybe e361253 has some importance. I guess the ternary operator typo could have caused genuine problem.
=> Fix couple compiler warnings

libblkid/src/Makemodule.am, libblkid/src/superblocks/bluestore.c, libblkid/src/superblocks/superblocks.c, libblkid/src/superblocks/superblocks.h
Hey folks, I recently came across a need to detect block devices that back Ceph OSDs running BlueStore (as opposed to FileStore).  I wrote this up in a few minutes and it meets my needs.  Submitting it as a PR in case this interests anyone else.  I can modify as needed if there is interest in this being included upstream.
=> Add support for detecting Ceph BlueStore Block Devices

sys-utils/setpriv.c
I assume the second entry was not desired in the original commit. Line 153-154 would appear to be a duplicate
=> Remove duplicate entry for reset-env from usage

sys-utils/ldattach.c
in glibc 2.29+ checking for just existence of _HAVE_STRUCT_TERMIOS_C_ISPEED
won't be enough, the value has to be checked
see
https://sourceware.org/git/?p=glibc.git;a=commit;h=e5a50db36eaa6e8c6427b3a971563240b633ca85
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> ldattach: Check for value of _HAVE_STRUCT_TERMIOS_C_ISPEED

bash-completion/umount
Should address https://github.com/karelzak/util-linux/issues/703. The way I did the string transformations feels a bit clunky, but that should work.
=> bash-completion: umount support relative path and ~ as home shorthands

disk-utils/fsck.cramfs.c, include/monotonic.h, include/timeutils.h, lib/monotonic.c, lib/timeutils.c, sys-utils/Makemodule.am, sys-utils/hwclock-rtc.c
This started as check if there is suspicious use of gettimeofday() function. In lib one was found from timeutils, and use in hwclock felt a bit wrong at spot that needs monotonic time difference measurement. But to make the monotonic time to work nice way I realized it would be good to have project local define to avoid calling CLOCK_MONOTONIC_RAW if it does not exist.  Last commit is vaguely related to time stuff, it replaces obsolete function call with one does the same thing and isn't obsolete yet.
=> Four time related fixes

sys-utils/mount.8
Clarify that the nosuid option also affects file capabilities and that
it only limits execution of programs. (setgid on directories still
inherit the group regardless of the nosuid option.) The new text is
taken from the mount(2) manual page from the man-pages project.
Addresses: https://github.com/karelzak/util-linux/issues/482
Signed-off-by: Peter Wu <peter@lekensteyn.nl>
=> mount.8: clarify (no)suid behavior on file capabilities

configure.ac
Released version 2.33.1 has the same typo in a ./configure file, but I don't find it in this tree, so I will just assume it is generated from the configure.ac file.
=> Typo in configuration help

text-utils/column.1
Hopefully this isn't too nit-picky:
Historical versions of `column` have described the default fill order as rows-then-columns and the `-x` order as columns-then-rows. This was misleading at best, and the util-linux implementation was updated to clarify the actual behaviour in 3e094e5fe2 (March 2017).
However, the other implementations (used by *BSD, macOS, Debian, &al.) continue to use the previous wording, and a user comparing them could easily get the false impression that util-linux `column` has exactly the opposite fill behaviour from BSD `column`.
To address this, a note is added to the man page explaining the change and clarifying that, despite what the BSD documentation says, the two implementations behave identically in this regard.
=> column: Address fill-order confusion in documentation

lib/loopdev.c
loopcxt_has_device is a one liner, so adding inline statement does not
hurt.
Signed-off-by: Marcos Paulo de Souza <marcos.souza.org@gmail.com>
=> lib/loopdev.c: Inline loopcxt_has_device

sys-utils/mount.8
Unfortunate use of 'e.g.', somebody noticed it is not actual and reported a bug.
=> Minor update of mount.8

sys-utils/fstrim.c
Commit f663b5b38f ("fat: add FITRIM ioctl for FAT file system") in
linux kernel added support for using fstrim with vfat filesystem.
Signed-off-by: Marcos Paulo de Souza <marcos.souza.org@gmail.com>
=> fstrim.c: Remove comment about vfat not supporting fstrim

misc-utils/hardlink.c
Usual variable scope tidy up, accompanied with a compiler warning fix.
=> hardlink: move global variables to control structure

sys-utils/fstrim.8, sys-utils/fstrim.c, sys-utils/fstrim.service.in
When fstrim interacts with NTFS it result can be error reporting bad file
descriptor.  That seems to be a bug in NTFS.  While waiting driver to get on
top of the issue and be commonly available lets add to fstrim option to make
it be more silent about errno 9 aka EBADF, Bad file descriptor.
Reported-by: https://github.com/moviuro
Proposed-by: Dave Reisner <dreisner@archlinux.org>
Reference: https://bugs.archlinux.org/task/62288
Addresses: https://github.com/karelzak/util-linux/issues/789
=> fstrim: add --quiet option to suppress error messages

include/strutils.h, tests/expected/lscpu/lscpu-x86_64-epyc_7451
From the test input string ':' characters are removed:
cat x86_64-epyc_7451/sys/devices/system/cpu/vulnerabilities/spectre_v2
Mitigation: Full AMD retpoline, IBPB: conditional, STIBP: disabled, RSB filling
=> lscpu: move trailing null after removing characters from a string

sys-utils/lscpu-arm.c
ARM has released docs for Cortex-A76, Neoverse-N1 and Neoverse-E1.
That means we know the midr partnums, so we can add them to the
human readable model name table.
Signed-off-by: Jeremy Linton <lintonrjeremy@gmail.com>
=> lscpu: Add additional aarch64 models

bash-completion/blkid, bash-completion/hardlink, bash-completion/lsblk, bash-completion/lscpu
Usual check what has changed in usage() in between previous release and latest commit resulting updates to to bash completions. That said manuals had all the options found in these commits.
=> Bash completion updates

libfdisk/src/dos.c
The self_pte() can return NULL if partitions array is not large enough,
but that should also be impossible and definitely a bug.
libfdisk/src/dos.c:984:8: warning: potential null pointer dereference [-Wnull-dereference]
libfdisk/src/dos.c:1031:8: warning: potential null pointer dereference [-Wnull-dereference]
=> libfdisk: assert if self_pte() returns NULL

login-utils/su-common.c
With users coming from LDAP, it is often the case that the entry in LDAP
does not contain one or more attributes required by su or, because of
misconfigured access control rights, the attribute might not be readable
by the LDAP client. In that case, su just tells the user that the user
does not exist.
It might be more user-friendly to tell the user to check the user entry
for all required fields.
=> su: More descriptive error message on malformed user entry

Documentation/TODO
The description is of hwclock whereas the title consists of hwlock. Since the title doesn't match with description, this seems to be a typo
=> TODO: fix typo

include/xalloc.h, lib/ttyutils.c, libblkid/src/save.c, libblkid/src/superblocks/drbd.c, libblkid/src/superblocks/zfs.c, libfdisk/src/context.c, libmount/src/optstr.c, misc-utils/lsblk.c
Apart the ttyutils code streamlining these changes are warning and error fixes. The last one of the changes that takes care of ASAN error might actually be somewhat important, as zfs bit operations may have resulted to incorrect computation.
Adding asset() to xstrdup() and xstrndup() might be a bit controversial. I see it did not cause test system to fail, but as we know tests do not cover all code lines. Threat is of course that assert starts to break stuff and we only know after release. So I understand if this commit should be changed to warn if there is buggy code path, but not crash.
=> 2019wk27 mostly warning fixes

libfdisk/src/partition.c
__copy_partition doesn't duplicate these strings which leads to
occasional double free.
Signed-off-by: Vojtech Trefny <vtrefny@redhat.com>
=> libfdisk: Fix double free of *_chs strings in fdisk_partition

sys-utils/lscpu-dmi.c
With pointer arithmetic clang address sanitizer gives following error this
change addresses.  Notice the following happens only when running as root.
sys-utils/lscpu-dmi.c:83:14: runtime error: load of misaligned address
0x55a1d62f3d1d for type 'const uint16_t' (aka 'const unsigned short'), which
requires 2 byte alignment
=> lscpu: prefer memcpy() to manual pointer arithmetic

bash-completion/mountpoint, sys-utils/mountpoint.1, sys-utils/mountpoint.c, tests/expected/misc/mountpoint, tests/ts/misc/mountpoint
The no follow option will allow user to distinct mount points from symbolic
links pointing to them.  Arguably this is pretty pedantic option, mounting a
device or bind mount to a directory via symlink does not have or cause any
issues.
Addresses: https://github.com/karelzak/util-linux/issues/832
=> mountpoint: add --nofollow option

disk-utils/fsck.cramfs.c, include/carefulputc.h, term-utils/agetty.c, term-utils/wall.c
There is a c_isascii function that can be used.
isascii is deprecated and not available with some libcs like uClibc-ng
where it can be compile time disabled.
=> Remove isascii usage

sys-utils/fstrim.service.in, sys-utils/fstrim.timer
Container type implies the following products:
openvz	OpenVZ/Virtuozzo
lxc	Linux container implementation by LXC
lxc-libvirt	Linux container implementation by libvirt
systemd-nspawn	systemd's minimal container implementation, see systemd-nspawn(1)
docker	Docker container manager
podman	Podman container manager
rkt	rkt app container runtime
wsl	Windows Subsystem for Linux
References:
https://www.freedesktop.org/software/systemd/man/systemd.unit.html
https://www.freedesktop.org/software/systemd/man/systemd-detect-virt.html#
Fix: #840
Signed-off-by: Eric Desrochers <eric.desrochers@canonical.com>
=> fstrim shouldn't run inside a container

po/de.po
I just reported the Mistake to Mario, which did the translation, via email. This is the PR to fix the (now) obvious mistake.
=> Fix -n to -b in German help message

disk-utils/cfdisk.c, disk-utils/fdisk.8, disk-utils/fdisk.c, disk-utils/fsck.8, disk-utils/mkfs.cramfs.c, disk-utils/sfdisk.8, disk-utils/sfdisk.c, login-utils/su.1, misc-utils/cal.c, misc-utils/fincore.1, misc-utils/mcookie.1, sys-utils/adjtime_config.5, sys-utils/dmesg.c, sys-utils/fstab.5, sys-utils/hwclock.8.in, sys-utils/mount.8, sys-utils/prlimit.1, sys-utils/renice.1, sys-utils/setarch.8, sys-utils/swapon.8, term-utils/script.1, term-utils/setterm.1, text-utils/colrm.1, text-utils/line.1, text-utils/pg.1, text-utils/ul.1
I found couple easy to fix debian bugs to fix that first two commits address. The bug 929677 aka runuser reference fix made me wonder if there are more broken man page references, so I grep through  util-linux and found couple.
As mentioned in commit message the process to find broken references is not reproducible. A grep + what ever happens to be installed on a developer laptop + cross reference by googling for man pages that aren't installed is pretty hard scripting exercise. If someone wants to automate that: good luck. My thinking is that these references do not need constant monitoring, sweeping through them manually very occasionally is good enough.
=> 2019wk33 debian bug fixes and manual references

sys-utils/unshare.1, sys-utils/unshare.c
Add the --map-current-user option to unshare. This option maps the
current effective UID and GID in the new user namespace so that the
inner and outer credentials match.
Signed-off-by: James Peach <jpeach@apache.org>
=> unshare: add --map-current-user option

tests/run.sh
Don't use `nproc --all` for getting cpu number. For example below, sparc64 is reporting 128 as a total, but only 32 is online. So, use only online cpus for tests parallel run.
```
$ nproc
32
$ nproc --all
128
$ lscpu
Architecture:        sparc64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Big Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  8
Core(s) per socket:  4
Socket(s):           1
Model name:          UltraSparc T5 (Niagara5)
Flags:               sun4v
```
Signed-off-by: Anatoly Pugachev <matorola@gmail.com>
=> [tests] don't use `nproc --all` for getting cpu number

bash-completion/addpart, bash-completion/blkdiscard, bash-completion/blkid, bash-completion/blkzone, bash-completion/blockdev, bash-completion/cfdisk, bash-completion/delpart, bash-completion/eject, bash-completion/fdisk, bash-completion/fsck, bash-completion/fsck.cramfs, bash-completion/fsck.minix, bash-completion/lsblk, bash-completion/mkfs, bash-completion/mkfs.bfs, bash-completion/mkfs.cramfs, bash-completion/mkfs.minix, bash-completion/mkswap, bash-completion/partx, bash-completion/resizepart, bash-completion/sfdisk, bash-completion/wipefs
This pull request is intended to address #842 as outlined in https://github.com/karelzak/util-linux/issues/842#issuecomment-523450243.
It makes one change to the requested behavior:  If it is unable to complete any of the canonical device names, it falls back to the default Bash matching for all files immediately, rather than special-casing `/dev/disk`.  The reason is that completing all links under `/dev/disk` immediately causes scrolling/paging or a "Display all X possibilities? (y or n)" prompt depending on how many disks are connected, which makes the Bash default of completing one level at a time seem preferable.  The default completion lists `by-id  by-label  by-partlabel  by-partuuid  by-path  by-uuid` when completing `/dev/disk/` then all symlinks in the directory when completing …
=> bash-completion: Match non-canonical device names or files

po/update-potfiles
It allows to run po/update-potfiles not only in tarballs and git repositories, but in git snapshots as well.
=> po/update-potfiles: fallback to `find` when `git ls-files` doesn't work

libmount/src/utils.c
General info about these filesystems:
* fuse.avfsd: https://sourceforge.net/projects/avf/
* fuse.lxcfs: https://linuxcontainers.org/lxcfs/
* fuse.vmware-vmblock: https://github.com/vmware/open-vm-tools
Signed-off-by: Darsey Litzenberger <dlitz@dlitz.net>
=> libmount: Recognize more FUSE pseudofs (avfsd, lxcfs, vmware-vmblock)

configure.ac
Currently if `--disable-all-packages` is set, there is no configure
option for re-enabling `wipefs`.
As the current default for `wipefs` is "enabled", add `--disable-` flag
to maintain backward compatibility.
Signed-off-by: Sam Voss <sam.voss@gmail.com>
=> wipefs: Allow explicit enable/disablement

misc-utils/lsblk.8
The docs (man page) currently do not list correct columns for the -f/--fs option. This fixes the doc to reflect the source.
(Found in - https://github.com/rhinstaller/anaconda/pull/2172 where --fs was replaced with -o (...) and the columns did not match.)
=> lsblk: update man description of -f / --fs for current columns

tests/expected/blkid/md-raid0-whole, tests/expected/blkid/md-raid1-whole, tests/ts/blkid/md-raid0-whole, tests/ts/blkid/md-raid1-whole
Since SPARC is using 'sun' partition table by default, make test not to assume that disk has 'dos' partition table, so write 'dos' partition table on disk, before proceeding any further.
Signed-off-by: Anatoly Pugachev <matorola@gmail.com>
before:
```
util-linux/tests# ./run.sh blkid
...
... OK (all 7 sub-tests PASSED)
blkid: mbr-wholedisk                  ... SKIPPED (cannot remove scsi_debug module (rmmod))
blkid: MD raid0 (whole-disks)         ... FAILED (blkid/md-raid0-whole)
blkid: MD raid1 (last partition)      ... SKIPPED (cannot remove scsi_debug module (rmmod))
blkid: MD raid1 (whole-disks)         ... FAILED (blkid/md-raid1-whole)
---------------------------------------------------------------------
2 tests of 8 FAILED
------------------------------------------------------------- …
```
=> tests: fixes blkid/md-raidX-whole on Sparc

libfdisk/src/table.c
libfdisk chooses a grain of 1MB fairly arbitrarily, and this granule
may not be honored by other utilities. GPT disks formatted elsewhere
may have space before the first partition, AND a partition that exists
solely below 1MB. If this occurs, cfdisk ends up adding a free space
region where end < start, resulting in a 16 Exabyte free region.
That's too many exabytes.
This happens because the start gets rounded up to the granule size in
new_freespace() but the end is left alone. The logs show it best:
23274: libfdisk:      CXT: [0x572d878]: initialized:  last=34, grain=2048
23274: libfdisk:      CXT: [0x572d878]: partno=10, start=64
23274: libfdisk:      CXT: [0x572d878]: freespace analyze: partno=10, start=64, end=64
23274: libfdisk:      CXT: [0x572d878]: LBA           34 aligned-up …
=> libfdisk: Space before first partition may not be aligned

login-utils/nologin.8, login-utils/nologin.c
nologin is typically used in /etc/passwd as a shell replacement.  Hence
ignore all unknown options and arguments silently to avoid unwanted ugly
error messages.
Addresses: https://github.com/karelzak/util-linux/issues/895
Requested-by: Lennart Poettering <lennart@poettering.net>
=> nologin: silently ignore all option arguments

configure.ac, include/pidfd-utils.h, m4/ul.m4, misc-utils/kill.1, misc-utils/kill.c
It is fairly common case for various system admin script to run kill, wait a
bit and send another signal.  This can be used for example when trying to first
gently ask for a program to terminate before sending a SIGKILL.  Another use
case is nginx that needs multiple signals to perform upgrade.  In short having
a way to send another signal after a bit makes scripting nicer and less racy.
=> kill: use pidfd system calls to implement --timeout option

login-utils/su.1
In the manpage of `su`, the synopsis implies the existence of arguments `user` and `argument`(s). However, how they are handled isn't noted at all.
I made a slight change to `su.1` to make it clearer.
=> Make manpage of su clearer

sys-utils/unshare.c
'c' was missing from the optstring, causing the error:
$ unshare --user -c
unshare: invalid option -- 'c'
Try 'unshare --help' for more information.
Fixes: 4175f29e62 ("unshare: add --map-current-user option")
=> unshare: fix --map-current-user short option (-c)

libblkid/src/superblocks/xfs.c
The xfs external log probe only checks for regular xfs on sector zero,
but then checks for valid log record headers on all first 512 sectors.
This can incorrectly detect an xfs external log if a regular xfs (i.e.
with internal log) is shifted by up to 512 sectors; it may happen with
bcache and LVM1 for example, as the regular xfs is found later in disk.
This results in ambivalent filesystem detection, thus no UUID for udev.
Fix this problem by checking for regular xfs on all sectors considered
by the xfs external log probe.
Test-case with bcache:
---
```
$ IMG=bcache-backing-device.img
$ dd if=/dev/zero of=$IMG bs=1G count=0 seek=1
$ DEV=$(sudo losetup --find --show $IMG)
$ sudo make-bcache -B $DEV
$ sudo mkfs.xfs -d agsize=16m -l agnum=0 -f /dev/bcache0
$ sudo LD_LIBRARY_PATH=./.libs …
```
=> libblkid: (xfs) external log: check for regular xfs on more sectors

sys-utils/flock.1
This quick patch shows an easy way to lock a file in the current shell process without having to spawn any new processes or using subshells.
As a disclaimer: I have no experience writing man pages.
=> flock: Add new example using shell IO redirection

libblkid/src/superblocks/exfat.c
According to released exfat specification, label is only 22 bytes long.
=> exfat: Fix parsing exfat label

lib/mbsalign.c, libblkid/src/read.c, libsmartcols/src/calculate.c, misc-utils/logger.c, sys-utils/rtcwake.c, tests/expected/fdisk/bsd_0_64.BE, tests/expected/fdisk/bsd_0_64.LE, tests/expected/fdisk/bsd_0_64_alpha.LE, tests/expected/fdisk/bsd_1_0.BE, tests/expected/fdisk/bsd_1_0.LE
The logger and rtwake time function changes continue the same fixes as
previous commit - use thread safe functions.  The libsmartcols condition
removal is possible because width must be greater than tb->termwidth that is
size_t and cannot be smaller than zero.  And remove couple FIXME's that are
old and unlikely ever to get fixed.
Reference: 3160589d86470ce7d20c81090fb7f211b3822053
=> various: fix more lgtm scan warnings

libuuid/src/parse.c, libuuid/src/uuid.h
We have a use case to construct a uuid from subset of a string. Currently, we have to create a temporary NULL-terminated buffer, copy the uuid, and call `uuid_parse()`:
```c++
uuid::uuid(std::string_view s)
{
if(s.size() != string_length)
throw std::runtime_error("malformed uuid");
uuid_string_type buf;
strncpy(buf, s.data(), std::min(s.size(), string_length));
buf[string_length] = '\0';
if(uuid_parse(buf, m_uuid) < 0)
throw std::runtime_error("malformed uuid");
}
```
This patch adds `uuid_parse_range()` which takes a pointer "range". This allows us to simplify the above down to:
```c++
uuid::uuid(std::string_view s)
{
if(uuid_parse_range(s.begin(), s.end(), m_uuid) < 0)
throw std::runtime_error("malformed uuid");
}
```
I send this to the mailing list previously, but received no response.
=> libuuid: add uuid_parse_range()

sys-utils/irqtop.c
Excess white spaces were easiest to see in json output.
$ irqtop --once --json
{
"interrupts": [
{"irq":"LOC", "total":7425148, "name":"Local timer interrupts "},
{"irq":"51", "total":1848384, "name":"IR-PCI-MSI 32768-edge i915 "},
{"irq":"RES", "total":1176665, "name":"Rescheduling interrupts "},
...
=> irqtop: trim whilte spaces

sys-utils/lsns.8, sys-utils/lsns.c
``` 
NS TYPE  NPROCS   PID USER COMMAND
4026531834 time     102     1 root /usr/lib/systemd/systemd --switched-root --system --deserialize 29
4026532246 time       1 54797 root sleep 100
```
Time namespace support in `lsns`. Also see #974
=> lsns: add time namespace support

sys-utils/nsenter.1, sys-utils/nsenter.c
Just as with unshare and lsns this adds time namespace support to
nsenter.
In contrast to unshare nsenter does not have the options '--boottime'
and '--monotonic' as that offset can only be set as long as there have
no processes being started in the corresponding time namespace.
=> nsenter: add support for the time namespace

sys-utils/unshare.1, sys-utils/unshare.c
While working on getting time namespace support into 'nsenter' it was
not possible to use '-t' to enter a time namespace as '-t' is the short
option for '--target'. Fortunately '-T' is still available in 'nsenter'
and 'unshare' and therefore let's change 'unshare' to use the same flag
for the time namespace as 'nsenter'.
See #974
=> unshare: use '-T' for time namespace instead of '-t'

include/mangle.h, libfdisk/src/script.c
Hello,
This PR fixes a segmentation fault that occurs if the name value is empty (i.e. `name=`).
The first patch fixes the issue in the fdisk library by calling the function `unhexmangle_string()` if the call to function `next_string()` succeeds.
The second patch makes the function `unhexmangle_string()` more robust by testing the nullity of the string argument before calling `strlen()` that crashes if the string pointer is `NULL`.
Here is how to produce the bug:
```
$ fallocate --length 1G disk.img
$ cat <<EOF | sfdisk disk.img
label: gpt
type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B uuid=8052084B-E1EF-4A16-A959-803D4E6C4427 name=
EOF
label: gpt
type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B uuid=8052084B-E1EF-4A16-A959-803D4E6C4427 name=
EOF
Checking that no-one is using this disk right now ... …
```
=> Libfdisk script fix segmentation fault

sys-utils/mount.8
In a section about mounting a directory `/foo`, it uses `/foox` once.  I believe this is a typo.
=> Fix typo in the mount (8) man page

tests/ts/eject/umount, tests/ts/libmount/context, tests/ts/libmount/context-py, tests/ts/libmount/context-utab, tests/ts/libmount/context-utab-py, tests/ts/mount/fstab-all, tests/ts/mount/umount-alltargets, tests/ts/mount/umount-recursive
Since SPARC is using 'sun' partition table by default, make tests not to assume that disk has 'dos' partition table, so write 'dos' partition table on disk, before proceeding any further.
Besides, this change allows next tests to execute, which depend on `scsi_debug` module as well, since `eject/umount` test does not dismount properly scsi debug block device partitions.
```
root@ttip:/1/mator/util-linux/tests# uname -a
Linux ttip 5.6.0-rc5 #29 SMP Mon Mar 9 12:15:59 MSK 2020 sparc64 GNU/Linux
```
Before changes:
```
eject: umount                         ...
: by-disk                     ... OK
: by-disk-mounted             ... OK
: by-disk-mounted-partition   ...Found a sun partition table in /dev/sda1
Proceed anyway? (y,N)
mount: …
```
=> tests: fixes eject, libmount, mount (root) tests on SPARC

tests/expected/fdisk/align-512-4K, tests/expected/fdisk/align-512-4K-63, tests/expected/fdisk/align-512-512, tests/expected/fdisk/align-512-512-topology, tests/ts/fdisk/align-512-4K, tests/ts/fdisk/align-512-4K-63, tests/ts/fdisk/align-512-512, tests/ts/fdisk/align-512-512-topology
Fixes fdisk/align-512-* tests
Before:
```
-------------------- util-linux regression tests --------------------
For development purpose only.
Don't execute on production system!
kernel: 5.6.0-rc7
options: --srcdir=/1/mator/util-linux/tests/.. \
--builddir=/1/mator/util-linux/tests/..
fdisk: align 512/4K                   ... FAILED (fdisk/align-512-4K)
fdisk: align 512/4K +alignment_offset ... FAILED (fdisk/align-512-4K-63)
fdisk: align 512/4K +MD               ... KNOWN FAILED (fdisk/align-512-4K-md)
fdisk: align 512/512                  ... FAILED (fdisk/align-512-512)
fdisk: align 512/512 +topology        ... FAILED (fdisk/align-512-512-topology)
fdisk: nested BSD                     ... OK
fdisk: GPT                            ... OK
fdisk: gpt-resize                     ... OK
fdisk: …
```
=> tests: fixes fdisk/align-512-* tests

sys-utils/lscpu.c
MIPS have slightly different layout of cpuinfo.
Btw:
MIPS's cpuinfo looks like this:
```
system type             : Generic Loongson64 System
machine                 : loongson,loongson3-8core-rs780e
processor               : 0
cpu model               : ICT Loongson-3 V0.7  FPU V0.1
BogoMIPS                : 1063.98
wait instruction        : no
microsecond timers      : yes
tlb_entries             : 64
extra interrupt vector  : no
hardware watchpoint     : yes, count: 0, address/irw mask: []
isa                     : mips1 mips2 mips3 mips4 mips5 mips32r1 mips32r2 mips64r1 mips64r2
ASEs implemented        : loongson-mmi loongson-cam loongson-ext
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VCED exceptions         : not …
```
=> lscpu: Adapt MIPS cpuinfo

configure.ac, text-utils/more.c
This is a resubmission of https://github.com/karelzak/util-linux/pull/694 with a 'fix' to mac build that is marking more(1) to be linux only.
While looking again into this I chose to slightly improve 'more: replace siglongjmp() and signal() calls with signalfd()' commit. The improvement is removal of 'stop_searching' and fiddling with signal handler and adding more_poll() that can be called from both more_key_command() and search() functions. The rest of the change set is kept the same as some months ago when these changes were first submitted to review.
=> more(1) re-engineering resubmission

libblkid/src/devname.c
This PR fixes an off by one in `strncmp(dev->bid_name, "/dev/mapper/", 11)` check. The `"/dev/mapper/"` string literal has a length of 12 and without this fix paths like `"/dev/mapperSOMETHING"` would also be accepted.
=> Fix off by one when checking "/dev/mapper/" path

bash-completion/more, include/env.h, lib/Makemodule.am, lib/env.c, text-utils/Makemodule.am, text-utils/more.1, text-utils/more.c
Continuation to series of more(1) changes. Notable changes in this change set  are use of libmagic to identify non-textual files, removal of underlining handling that is not needed on a modern linux terminals that will handle underlining just fine, and addition of long options.
=> 2020wk13 more more(1) changes

include/pwdutils.h, lib/pwdutils.c, sys-utils/unshare.1, sys-utils/unshare.c
Two new options are added: `--map-user=<uid>` and `--map-group=<gid>` for custom user and group mappings respectively. These are just generalizations of the existing `--map-root-user` and `--map-current-user` options.
As a side effect of this commit, specifying both `--map-root-user` and `--map-current-user` no longer causes an error. Instead, the last occurrence takes precedence.
=> unshare: allow custom uid/gid mappings in userns

sys-utils/fstrim.service.in, sys-utils/fstrim.timer
The timer and service units run `fstrim --fstab`, which strictly
depends on `/etc/fstab` being present in the OS. This adds relevant
condition statements to the units, in order to skip them and avoid
runtime failures.
Ref: https://github.com/karelzak/util-linux/issues/673#issuecomment-409246816
Ref: https://github.com/coreos/bugs/issues/2591
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/468
Signed-off-by: Luca BRUNO <luca.bruno@coreos.com>
=> fstrim: run service and timer only if /etc/fstab is present

libmount/src/utils.c
I was bothered by tracefs appearing in `findmnt --real`, then added detection for a few more pseudo filesystems.
=> Add to the list of pseudo-filesystem types

bash-completion/umount
Good day,
This patch brings support for automatic dangerous shell characters
escape in umount autocompletion.  Due to the very peculiar way for
bash to handle autocompletion routines, proper escaping of the shell
sequences only worked properly inside a function: _umount_point_list,
which will add to the user's namespace at the next umount attempt of
autocompleting mount point.
It also translates calls of gensub to the portable alternatives sub
and gsub, in order to allow the use of various awk implementations
(mawk, Gnu, Busybox, etc), and as such kind of undoes a recent change
to enforce the use of Gnu awk. The whole story landed into the Debian
BTS initially:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933934
PS: It's been a few months since the patch is available, sorry for the …
=> bash-completion/umount: shell charaters escape

configure.ac, login-utils/Makemodule.am, login-utils/logindefs.c, login-utils/su-common.c
openSUSE plans to split the distribution provided configuration files from the changes the user makes. We will, similar to systemd, have a vendor directory below /usr with the distribution configuration files and applications will merge the configs at start. For this, we developed libeconf to make that easier.
This pull request implements libeconf support for util-linux and adds a configure option to specify the vendor directory below /usr. If none is specified, libeconf will read /etc/login.defs and merge possible overrides from /etc/login.defs.d. Else libeconf will read /usr/<vendor>/login.defs{.d} if /etc/login.defs does not exist and merge all overrides from /etc/login.defs.d.
=> Add support for libeconf

disk-utils/fdisk.8
It seems that "--wipe-partitions" is correct, not "--wipe-partition".
Signed-off-by: Shigeki Morishima <s.morishima@jp.fujitsu.com>
=> Manual page: fdisk.8: fix typo

tests/ts/cramfs/mkfs
Fix cramfs/mkfs test warning on sparc64 / big-endian arch with pagesize 8192 by adding checksum for `BE:8192`
before the patch:
```
tests/ts/cramfs# ./mkfs 
cramfs: mkfs checksums                 ...warning cramfs/mkfs: unknown checksum for BE:8192
OK
```
after the patch:
```
tests/ts/cramfs# ./mkfs
cramfs: mkfs checksums                 ... OK
```
=> tests: add BE:8192 checksum to cramfs/mkfs, fixing the warning

tests/expected/col/newlines, tests/ts/col/newlines, text-utils/col.c
Commit I made while back and has been part of util-linux v2.30 to v2.35 made
col(1) not to output anything when first line did not have newline character.
printf "gone from output" | col
This commit fixes the issue.  Admittedly the col source code is unnecessarily
hard to work with.  It could be a good idea to refactor the col(1) as low
priority task, Assuming refactoring is done the first commit to get that done
should add tests that exhaust all possible input handling including all command
line option directives.
Addresses: https://github.com/karelzak/util-linux/issues/422
Fixes: b6b5272b03ea9d3fa15601801d4d0f76ea4440f1
=> col: fix output when first line does not have newline character

.travis-functions.sh, .travis.yml
To judge from fc412fe4cee960, back in 2016 it was the latest version
of Ubuntu available on Travis CI. Now build tools there are too old
for testing purposes.
Other than that, Ubuntu Trusty hasn't been supported at https://apt.llvm.org/
since August 2019, which makes it kind of hard at this point to bring the latest clang
along with ASan, UBsan, Msan and libFuzzer to Travis CI.
=> travis: switch to Bionic

sys-utils/unshare.c
Fixes #1086.
Tested by running [mkosi](https://github.com/systemd/mkosi.git) with a modified version of pacstrap that uses the unshare command with the changes from this PR. Before, sending SIGINT to the pacstrap process group caused mkosi's cleanup to fail with EBUSY when unmounting because pacman (started by pacstrap via unshare --fork --pid) was still running after unshare exited.
With these changes, the mkosi cleanup succeeds because unshare waits for pacman to exit. A side effect is that pacman receives the SIGINT signal twice (once via SIGINT sent to the process group and once via unshare itself). We could not forward signals but then sending SIGINT/SIGTERM to unshare only wouldn't work because the child process wouldn't receive the signal.
=> unshare --fork: Ignore SIGINT and SIGTERM in parent

tests/functions.sh, tests/ts/blkid/dm-err
Signed-off-by: Evgeny Vereshchagin <evvers@ya.ru>
=> tests: skip "blkid/dm-err" when `mknod` doesn't work

Makefile.am, configure.ac, libmount/mount.pc.in, libmount/src/Makemodule.am, libmount/src/context_veritydev.c, sys-utils/mount.8
Enabling libcrypsetup in libmount had several unintended side
effects.
First of all, it increases the Debian minimal image size by
~2.5% (5.6MB worth of new libraries).
Then, due to libcryptsetup linkage to OpenSSL and libjansson,
it causes incompatibilities with external programs linking
against both libmount and a private, static, old version of
OpenSSL, or external programs linking against libjson-c,
which has one symbol in common with libjansson.
Instead of linking to libcrypsetup, use dlopen to resolve
the symbols at runtime only when the verity feature is
used, thus avoiding clashes and keeping images size down.
Fixes #1081
Signed-off-by: Luca Boccassi <luca.boccassi@microsoft.com>
=> cryptsetup: add configure-time option use via dlopen in libmount

.travis-functions.sh, .travis.yml, Documentation/howto-tests.txt
For this to work, a daily cron job running on the master branch should be added: https://docs.travis-ci.com/user/cron-jobs/
The report can be found at https://scan.coverity.com/projects/karelzak-util-linux
=> travis: integrate util-linux with Coverity Scan

tests/expected/rename/symlink, tests/expected/rename/symlink.err, tests/ts/rename/symlink
Add a few checks to the symlink test, including for the fix
in commit 477239ce0d60 ("rename: fix regression for symlink
with non-existing target").
Tested with `./tests/run.sh rename/symlink` before/after that
commit with FAILED/OK results (and `--show-diff`) as expected:
After:
`       rename: symlink check                  ... OK`
Before:
`       rename: symlink check                  ... FAILED (rename/symlink)`
With `--show-diff`:
```
diff-{{{
--- /home/mfo/git/util-linux/tests/expected/rename/symlink	2020-07-14 15:21:06.412792160 -0300
+++ /home/mfo/git/util-linux/tests/output/rename/symlink	2020-07-14 15:45:10.980927233 -0300
@@ -3,5 +3,3 @@
rename_slink.3: `old' -> `new'
`rename_slink.1' -> `rename_symlink.1'
target
-`rename_slink.2' -> `rename_symlink.2'
-target
}}}-diff
diff-{{{ …
```
=> rename: tests: add more symlink checks

Documentation/howto-pull-request.txt
Changes
git push yourbranch textual:textual
to
git push yourgit textual:textual
in root/Documentation/howto-pull-request.txt
Reason: The remote was defined as "yourgit", but one command uses the expression "yourbranch".
The latter expression was not used anywhere else in the document.
=> fix minor typo: yourbranch -> yourgit

term-utils/scriptreplay.c
Making scriptreplay call cfmakeraw fixed the output thereof, but it disabled terminal special character handling. For example, Ctrl-C does not send SIGINT to scriptreplay anymore; this is inconvenient. The following fixes this.
tattr.c_lflag |= ISIG;
where tattr is the struct termios with which we are working.
=> Fix terminal special character handling in scriptreplay

.github/workflows/cifuzz.yml, .travis-functions.sh, configure.ac, include/c.h
Looks like those specifiers haven't been used since 6c9ab254aefb6ce7e0e
(where sscanf was removed) was merged. This should help to get
util-linux to compile with MSan. Currently it's failing with
```
...
configure: error: libmount selected, but required scanf string alloc modifier not available
...
configure:20240: ./conftest
==116617==WARNING: MemorySanitizer: use-of-uninitialized-value
#0 0x496fd6 in main /home/vagrant/util-linux/conftest.c:171:6
#1 0x7f5eb85ea1a2 in __libc_start_main (/lib64/libc.so.6+0x271a2)
#2 0x41c2cd in _start (/home/vagrant/util-linux/conftest+0x41c2cd)
SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/vagrant/util-linux/conftest.c:171:6 in main
Exiting
configure:20240: $? = 77
...
configure:20265: $? = 0
configure:20265: ./conftest
MemorySanitizer: bad …
```
=> build-system: stop looking for %ms and %as

term-utils/scriptreplay.c
Upon more testing, it was found that the way tcgetattr is called in "setterm()", it cannot fail with errno == EBADF under normal circumstances (*): scriptreplay(1) of course does not close its own stdout voluntarily mid execution.
(*) The only way I was able to force an EBADF was by using [ p close(1) ] in gdb. Therefore, the EBADF error handling is not removed by this patch, it is only changed to errno != ENOTTY.
=> [PATCH] scriptreplay(1): Minor modification to tcgetattr error handling.

lib/pty-session.c
terminall -> terminal
redurected -> redirected
SIGCHILD -> SIGCHLD
Other minor things like putting a comma before "and" separated by independent clauses.
=> Fix minor typos

libmount/src/fuzz.c
It seems to be failing with
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==13==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00000055f428 bp 0x7ffc3743a170 sp 0x7ffc3743a080 T0)
==13==The signal is caused by a WRITE memory access.
==13==Hint: address points to the zero page.
SCARINESS: 10 (null-deref)
#0 0x55f428 in mnt_table_parse_next /src/util-linux/libmount/src/tab_parse.c:587:6
#1 0x55c200 in __table_parse_stream /src/util-linux/libmount/src/tab_parse.c:737:8
#2 0x55be38 in mnt_table_parse_stream /src/util-linux/libmount/src/tab_parse.c:809:8
#3 0x5511ff in LLVMFuzzerTestOneInput /src/util-linux/libmount/src/fuzz.c:21:16
#4 0x458a31 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) …
```
=> tests: cover the code parsing comments

include/pt-gpt-partnames.h
See https://systemd.io/HOME_DIRECTORY/ .
Additionally update the URL of [the Boot Loader Specification](https://systemd.io/BOOT_LOADER_SPECIFICATION/).
=> libfdisk: add systemd-homed user's home GPT partition type

libfdisk/src/script.c
When the partition table is present **but** empty, the existing code would output fields followed by a `,` , on the assumption that the list of partitions would follow. But if the list of partitions is empty, it is skipped, leading to output like this:
```
{
"partitiontable": {
"label":"gpt",
"id":"1F9E80D9-DD78-024F-94A3-B61EC82B18C8",
"device":"/dev/sdb",
"unit":"sectors",
"firstlba":2048,
"lastlba":30949342,
"sectorsize":512,
}
}
```
Note the `512,` on the *sectorsize* line.
This is invalid JSON for some parsers, which choke on it.
Avoid this, by checking when outputting the last separator: if there's no table, or there is a table but it is empty, then just put a newline, otherwise use the old path of comma-newline and assume there's going to be a list of partitions after.
=> Generate valid JSON if partition table is empty

sys-utils/hwclock.c
turns out this is subtly broken. musl 1.2.x for 64-bit architectures defines __NR_settimeofday but not
for 32-bit ones. For 32-bit, it defines a _time32 variant.
=> hwclock: fix SYS_settimeofday fallback

libmount/src/context_mount.c, libmount/src/libmount.h.in, libmount/src/optmap.c, sys-utils/mount.8
This adds support for the "nosymfollow" mount option, which indicates
that symlinks should not be traversed on the mount this option is
applied to.  Also update the mount(8) man page with information about
this option.
Signed-off-by: Mattias Nissler <mnissler@chromium.org>
Signed-off-by: Ross Zwisler <zwisler@google.com>
=> mount: Add support for "nosymfollow" mount option.

sys-utils/lscpu-arm.c
=> add Carmel from NVIDIA

lib/randutils.c
In order to build util-linux on other platforms (such as IBM i), do not require the linux-specific sys/syscall.h.
=> do not require sys/syscall.h on non-linux platforms

sys-utils/fstrim.timer
In 9995da0 we added support to fstrim to be able to fall back to
`/proc/self/mountinfo` if `/etc/fstab` didn't exist, but we forgot
to remove the `/etc/fstab` condition from the timer. Let's remove
that condition from the timer so we can go back to periodically
running `fstrim.service`.
=> fstrim: remove fstab condition from fstrim.timer

lib/exec_shell.c, lib/pty-session.c, login-utils/newgrp.c, login-utils/sulogin.c, login-utils/vipw.c, sys-utils/eject.c, sys-utils/setarch.c, term-utils/script.c, term-utils/scriptlive.c, text-utils/pg.c
When calling variadic functions, NULL must be explicitly cast to a desired type.
This is noted in the [exec(3)](https://man7.org/linux/man-pages/man3/exec.3.html) manpage.
The call in newgrp.c was changed for consistency.
=> cast NULL to char * when using execl

disk-utils/sfdisk.c
`--json` implies `--dump`, thus `--json --dump` must be
allowed. `--list-free` is incompatible with `--dump`, and thus also
with `--json`. Currently `--json --dump` is prohibited, even though
`--list-free` is not specified at all.
Regression introduced in 03154d2cf25c1d5ce908da9e72d324004b8d5722.
Signed-off-by: Dimitri John Ledkov <xnox@ubuntu.com>
=> sfdisk: correct --json --dump false exclusive

configure.ac, misc-utils/whereis.1, misc-utils/whereis.c, tests/expected/misc/whereis, tests/ts/misc/whereis
I have improved whereis in various ways for modern Linux distributions. Please see the last commit which adds a test case for all changes.
The changes are separated into single commits, from least controversial to most. It should help to cherry pick single ones if you do not agree with all of them.
The tool whereis will be optional but activated by default when configure is called.
See this example:
```
$ whereis python3 diff fsck.ext4
python3: /usr/bin/python3 /usr/bin/python3.8-config /usr/bin/python3.8 /usr/lib/python3.8 /usr/include/python3.8 /usr/share/man/man1/python3.1.gz
diff: /usr/bin/diff /usr/share/man/man1/diff.1p.gz /usr/share/man/man1/diff3.1 /usr/share/man/man1/diff.1.gz
fsck: /usr/bin/fsck.ext4 /usr/bin/fsck.ext3 /usr/bin/fsck /usr/bin/fsck.minix /usr/bin/fsck.cramfs …
```
=> whereis: various fixes and improvements

configure.ac, include/all-io.h, include/fileutils.h, lib/fileutils.c, login-utils/Makemodule.am, login-utils/login.c, login-utils/nologin.c, login-utils/vipw.c
Since `off` and `nr` approach each other, the for-loop ends prematurely when at least half of the buffer was written. I think under certain conditions this could cause the copy to be incomplete.
=> vipw: fix short write handling in copyfile

include/randutils.h, lib/randutils.c, libuuid/man/uuid_generate.3, libuuid/src/gen_uuid.c, libuuid/src/uuidd.h
If a libuuid application is unable to access /dev/random or /dev/urandom
then uuid generation by uuid_generate falls back to uuid_generate_time.
This could happen in chroot or container environments.
The function ul_random_get_bytes from lib/randutils.c uses getrandom if
it is available. This could either mean that the libuuid application
skips good random bytes because the character special files do not exist
or the application trusts in good random bytes just because these files
are accessible but not necessarily usable, e.g. limit of open file
descriptors reached, lack of data, kernel without getrandom, etc.
This commit modifies ul_random_get_bytes to return an integer which
indicates if random bytes are of good quality (0) or not (1). Callers
can decide based on this information if …
=> libuuid: check quality of random bytes

libblkid/src/config.c, libblkid/src/dev.c, libblkid/src/devname.c, libblkid/src/partitions/atari.c, libblkid/src/partitions/mac.c, libblkid/src/save.c, libblkid/src/verify.c
This pull request fixes some issues in corner cases:
- A blkid.conf with multiple CACHE_FILE lines leads to memory leaks
- A weird mac partition layout cannot be parsed
- A 32 bit time_t system can trigger signed integer overflows
The second issue (mac partition) should receive a bit more refactoring. I think that it makes sense to have an upper limit of partitions allowed. The same is true for atari. Otherwise such a disk could consume a lot of memory which eventually leads to out of memory conditions on pretty much every system.
I lack proper documentation of old macOS and atari systems though. Do you know where real partition limits are?
=> libblkid: fix corner case issues

sys-utils/lscpu-virt.c
An alternate fix is `#ifdefing` around the block that uses the value, but that would be a more intrusive code change.
=> lscpu-virt: fix return type of read_hypervisor_cpuid for non x86.

sys-utils/hwclock.c
Check that `__NR_settimeofday_time32` exists before trying to use it as
syscall number.
Signed-off-by: Pino Toscano <toscano.pino@tiscali.it>
=> hwclock: do not assume __NR_settimeofday_time32

login-utils/Makemodule.am, term-utils/Makemodule.am
Do not build plymouth-ctrl.c in agetty and sulogin in case the plymouth
support is disabled.
Signed-off-by: Pino Toscano <toscano.pino@tiscali.it>
=> build-sys: do not build plymouth-ctrl.c w/ disabled plymouth

include/procutils.h, lib/caputils.c, lib/procutils.c
First step for #1179, should make any usage of the value returned by `cap_last_cap` completely safe.
I can remove the caching, but thought it would be nice to have. Alternatively, applications that use `caps_last_cap`  multiple times can cache it themselves.
=> Find last caps through prctl instead of procfs or guess

sys-utils/setpriv.c
The initial change to lib/caputils that allowed this was commit
5d95818757941bc609e5aeec5e2218f7d35a6e19, which made it possible to
trust the value returned by cap_last_cap().
The error message was also somewhat misleading, since cap_last_cap()
being smaller than CAP_LAST_CAP happens when setpriv itself is built
with kernel headers older than the currently running kernel, not due to
libcap-ng.
=> setpriv: allow using [-+]all for capabilities.

sys-utils/setpriv.c
- Add _() calls for some strings which were missing it.
- In print_caps(), use the same error checking done in
list_known_caps(); it is expected that libcap-ng will always return a
string, even if it's only "cap_%d".
---
Should I regenerate the .pot files somehow for this?
=> setpriv: small clean-up.

libblkid/src/superblocks/drbdmanage.c
Function blkid_probe_strncpy_uuid() is better suitable for setting UUID
than function blkid_probe_set_id_label().
=> libblkid: drbdmanage: use blkid_probe_strncpy_uuid instead of blkid_probe_set_id_label

misc-utils/uuidd.c
As mentioned in https://github.com/karelzak/util-linux/pull/1186#issuecomment-731111712 the uuidd changes were needed in smaller chunks that are easier to review. So here we are, and as I started to look uuidd more there was more small things that could be done. So the change set grew since the last time. As a whole this is still pretty large change, but when viewed each commit one at a time they hopefully make sense.
=> uuidd cleanups and clarifications

configure.ac, include/fileutils.h, lib/fileutils.c, login-utils/login.1, login-utils/login.c
This change set was originally inspired the recent uuidd(8) work I did where I thought it would be quite good idea to keep memory allocations of an executable that stays running minimal. There are not many such commands in util-linux, but login definitely is one of them. Most of the changes in this pull are about the objective of making login smaller. 
While looking into the source couple other things seemed like good ideas to fix so they were added as well, such as use  of close_range() that hopefully will speed up getting onto a system. And I went through the manual page that is hopefully a tiny bit better, though I am sure it could still be made better.
This is obviously not an urgent change, as no bugs (apart maybe ad3ad51be6fc1c3dcc13ed8a77e703d97c72ff3d) were fixed. Everything …
=> login(1) maintenance changes

sys-utils/losetup.c
Since the range of the ino_t data type is platform-specific (depending on the wordsize), a usage of the fixed format specifier `%PRIu64` is not correct for ino_t on some 32-bit architectures, eg. ARM (Raspberry Pi 1). This issue may lead to undefinied output and is not reported by gcc (in version 10.2.0 and 8.3.0-6+rpi1) even though `-Wformat` is enabled by `-Wall`. Therefore it is most likely that it seems to be a false negative error in gcc's format specifier check, so that this issue was never detected before.
This change fixes the issue by the use of a cast, since there is no platform-independent format specifier for ino_t available. The wrong format specifier `%PRIu64` is replaced by `%ju`, where its corresponding variable of type ino_t is casted to uintmax_t. The type uintmax_t …
=> losetup: fix wrong printf() format specifier for ino_t data type

configure.ac
I faced `test: too many arguments` when building Linux-PAM using [sbase](https://core.suckless.org/sbase/).
This is due to a non-POSIX syntax `test ... -a ...` and `test … -o …`.
> The XSI extensions specifying the -a and -o binary primaries and the '(' and ')' operators have been marked obsolescent.
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html
Related, https://github.com/linux-pam/linux-pam/pull/311
=> configure: test -a|o is not POSIX

libfdisk/src/alignment.c
A 33553920 byte optimal I/O size arises from badly-implemented USB SATA
adapters reporting 0xffff 512 byte sectors (32 MiB - 512).  Commit
acb7651f8897ae73d0f45dd75bc87630001c61b9 indirectly addresses this by
ignoring the optimal I/O size if it's not a multiple of the physical
sector size.  That works if the physical sector size is 4096, but
33553920 optimal is allowed for 512 physical.
This commit explicitly ignores 33553920, as there is no legitimate
situation where this number would be the real optimal I/O size.
Signed-off-by: Ryan Finnie <ryan@finnie.org>
Closes: https://github.com/karelzak/util-linux/issues/1221
=> libfdisk: ignore 33553920 byte optimal I/O size

disk-utils/cfdisk.8, disk-utils/cfdisk.c
Reported in https://bugs.debian.org/906918, https://bugs.debian.org/915971.
Signed-off-by: Vincent McIntyre <vincent.mcintyre@csiro.au>
=> Document the cfdisk 'resize' command

misc-utils/Makemodule.am, misc-utils/getopt.1.in, misc-utils/getopt.c
GNU libc's getopt_long(3) have the tradition of not shuffling arguments
to find options when either POSIXLY_CORRECT is defined in environment
variables or '+' prepended in short options. Hence, the current code
base is fine as is fine as is for util-linux built with GNU libc.
However, musl libc only honour POSIX convention when short options
prepended with '+'. musl libc doesn't care about POSIXLY_CORRECT.
Thus, the behaviour of util-linux's getopt(1) that linked with musl-libc
doesn't match with its own documentation.
Let's make sure a '+' is always prepended to short options if
POSIXLY_CORRECT is defined.
Signed-off-by: Đoàn Trần Công Danh <congdanhqx@gmail.com>
---
There's also test failure for `col(1)` on musl libc. `getwchar(3p)` refers to `getwc(3p)`
which in turn refers to …
=> getopt: explicitly ask for POSIX mode on POSIXLY_CORRECT

configure.ac
Merry Christmas. A while back autoconf got new release, and when my laptop received the update I decided to test if util-linux work fine which it did not. This pull request fixes the autoconf upgrade related issues, and has additional small change to suppress a make(1) warning.
=> Make autoconf 2.70 work without issues

libmount/src/utils.c
Filesystems provided by a hypervisor for guest kernels:
* vboxsf: Linux 5.6
* virtiofs: Linux 5.4
Signed-off-by: Shahid Laher <govellius@gmail.com>
=> libmount: add vboxsf, virtiofs to pseudo filesystems

term-utils/agetty.c
This option has valid use cases on virtual consoles. Example:
enabling screen blanking in the same way as `setterm --blank ...`
does.
=> agetty: Allow --init-string on a virtual console

.github/workflows/cibuild.sh, .github/workflows/cibuild.yml, include/c.h, include/closestream.h, libfdisk/src/Makemodule.am, libmount/src/Makemodule.am, login-utils/Makemodule.am, tests/functions.sh, tests/ts/eject/umount, tests/ts/fuzzers/test_fdisk_script_fuzz, tests/ts/fuzzers/test_last_fuzz, tests/ts/fuzzers/test_mount_fuzz, text-utils/col.c
Since the current Ubuntu Focal image in GH Actions is missing the
`kernel-modules-extra` package with the `scsi_debug` module[0], let's
change the distro flag from `ubuntu-20.04` (Focal) to `ubuntu-latest`
(currently Bionic, as Focal is still in the beta phase).
[0] https://github.community/t/missing-scsi-debug-linux-kernel-module-on-gh-actions/157698
=> ci: 'downgrade' Ubuntu version to Bionic

include/procutils.h, lib/caputils.c, lib/procutils.c, sys-utils/setpriv.c
This MR contains a few cherry-picks of the capability fixes from master.
In particular, without these setpriv will fail when the CAP_LAST_CAP isn't greater than the procfs entry.
This can happen, as one is using a kernel newer than the one providing the UAPI headers. After all, can have more than one kernel installed on their system.
Hope I didn't miss anything from the instructions at Documentation/howto-pull-request.txt. Please shout otherwise ;-)
Note: For some reason `make check` fails on "column: invalid multibyte" test. The failure happens even without this MR.
=> stable/2.36: cherry-picking capability fixes

.github/workflows/cifuzz.yml
CIFuzz and OSS-Fuzz are in sync with the master branch so it would
probably make sense to avoid running it for long-lived branches.
Inspired by https://github.com/karelzak/util-linux/pull/1248#issuecomment-776342252
Signed-off-by: Evgeny Vereshchagin <evvers@ya.ru>
=> ci: trigger CiFuzz for the master branch only

Makefile.am, bash-completion/Makemodule.am, lib/Makemodule.am
Saves some build time when configure to build only a small set of libraries.
=> Avoid building libcommon and libtcolors unless needed

text-utils/more.c
Attached two patches for more:
1) Currently 'f' behaves like 's', which is not correct according to man page.
Bug was introduced with 1f86193.
2) Currently ARROW_DOWN and PAGE_DOWN is bound to command 's' (skip lines).
But this behaviour is not what the user expects, since at least one line
is always missing! Furthermore at the end of the file there is typically
this skipping lines message, if the remainder does not fit in a
complete screen. This conflicts also with e.g. less and man PAGE_DOWN
behaviour. The 'natural' behaviour is binding to
more_kc_jump_lines_per_screen.
If more is extended to also jump only a specific number of lines forward,
this would be even a better binding for ARROW_DOWN.
=> more: fixes (screen forward command) and ARROW_DOWN, PAGE_DOWN binding

libfdisk/src/gpt.c
Otherwise, sfdisk would error out on its own dump, as first-lba would be
earlier than "plausible" assuming the default table size.
This is because it did not look for `table-length` when using an sfdisk
script. This means that using `--dump` on a valid image, could not be
unserialized back into a valid image.
This is helpful in exotic situations, where a partition has to be
created earlier than the conventional "first-lba" (2048). For example,
on Allwinner A64 boards, where a firmware is stored at LBA16. With this
it is possible to ask for `first-lba` at or earlier than 16, by reducing
the number of entries to e.g. 48.
=> libfdisk: Include table-length in first-lba checks

sys-utils/swapon.c
Because the headings are aligned with tabs the fields must
always be a multiple of 8 characters. Moreover if the field
values are shorter than 8 characters, extra tabs must be
inserted before the succeding field to keep alignment.
swapon parses /proc/swaps, generated by the Linux kernel in
mm/swapfile.c. Its function swap_show() and its recent fix in
commit 6f7939405f61de7d0da7f6c90182e96c4f5ff6c1 were used as
inspiration for this commit.
Additionally inform the translators about the requirements of
formatting and relationship between the heading and entry strings.
=> swapon: Keep headings and fields aligned in summary output.

libfdisk/src/dos.c, man-common/manpage-stub.adoc, meson.build, misc-utils/lsblk-mnt.c, schedutils/uclampset.c, sys-utils/hwclock.c
Not  much to explain, but just to mention two things:
- I'm not sure regarding the change on `libfdisk/src/dos.c`
- The e-mail from `sys-utils/hwclock.c` I found the fix 'comnets' on the web
=> Fix misspellings

Documentation/TODO
Hello Karel,
now the initial Asciidoc import of the man pages is done, I've changed the TODO list and fixed a typo.
Until v2.38, I hope to figure out how to improve the line breaks to get a view similar to the old man pages. Example from findfs.8, old appearance:
```
EXIT STATUS
0      success
1      label or uuid cannot be found
2      usage error, wrong number of arguments or unknown option
```
And here the new appearance:
```
EXIT STATUS
0
success
1
label or uuid cannot be found
2
usage error, wrong number of arguments or unknown option
```
The old version is better readable. Well, the Asciidoc code is similar to the asciidoctor(1) man page, and such listings appear there the same as here, but this is not yet what I really want.
=> Documentation/TODO: Minor update and fix typo

sys-utils/lsns.8.adoc, sys-utils/lsns.c
lsns: interpolate missing namespaces for converting forests to a tree
The tree of *parent* and *owner* could be forests because *lsns*
cannot track a namespace having no process.
This change tries interpolating the missing namespaces by calling
ioctl(NS_GET_PARENT) and ioctl(NS_GET_USERNS) recursively.
The original output for -Tparent:
NS             TYPE   NPROCS   PID USER   COMMAND
4026531837     user      404     1 root   /usr/lib/systemd/sy
├─4026532508   user        1 29376 yamato /usr/lib64/firefox/
...
└─4026533513   user        1 24245 yamato /usr/lib64/firefox/
...
4026533733     user        1 30839 yamato /opt/google/chrome-
4026533734     user       15 10076 yamato /opt/google/chrome-
user namespaces 4026533733 and 4026533734 are orphans.
lsns could not find their parents. …
=> lsns: interpolate missing namespaces for converting forests to a tree

configure.ac
Upstream patches being used in LibreELEC to configure.ac
- https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/sysutils/util-linux/patches/util-linux-0100-enable-lscpu.patch
- https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/sysutils/util-linux/patches/util-linux-blkid_swapon_mkfs_uuidgen.patch
=> build-sys: add configure options to disable/enable individual utils

lib/timeutils.c, sys-utils/hwclock.c
=> Fixed format strings and type casts in hwclock to work with 64-bit time_t on 32-bit linux

sys-utils/unshare.c
The mount() command associated with this error message is not about
unmounting the proc fs, but rather about changing the propagation
of mount events for the proc fs. Rewrite the error message to
reflect this.
=> unshare: Fix error message when setting proc mount propagation

text-utils/more.c
Make the code avoid divided by zero.  This can happen when file has content
but is zero in size.  Such files can be found from procfs, possibly some
other pseudo-filesystems.  To reproduce the issue run the following.
$ more /proc/crypto
...
Floating point exception (core dumped)
=> more: fix floating point exception core dump

sys-utils/fstrim.timer
I'm working on building initramfs images directly from normal
packages, which means that the pristine system rpms should behave
correctly as much as possible also in the initrd. There usually isn't
enough time for the timer to actually fire, but starting it gives a
line on the console and generally looks confusing and sloppy. So let's
skip the timer if it ever ends up being enabled in the initrd.
Checking for /etc/initrd-release is the standard condition that
systemd's initrd units use.
=> fstrim: do not start the timer in initrd

sys-utils/lscpu-cputype.c
fails with error: label at end of compound statement
and fix typo as bonus.
Signed-off-by: Georgy Yakovlev <gyakovlev@gentoo.org>
=> lscpu: fix build on powerpc

text-utils/hexdump-display.c
When using the format string '/1 "%d"', the byte did not display as a
signed integer as expected, it was interpreted as unsigned.
Mainly inspired by https://unix.stackexchange.com/questions/304446/print-one-byte-signed-number-with-hexdump
=> hexdump: correctly display signed single byte integers

sys-utils/dmesg.1.adoc
Double-semicolon at the end of the option line results in description
being indented extra tab to the right. Replacing them with double-colons
allows all options to be displayed at the same indent level.
=> dmesg: fix indentation in man page

sys-utils/mount.8.adoc
Using mount flag `nosuid` also affects SELinux domain transitions but
this has not been documented well.
Signed-off-by: Topi Miettinen <toiwoton@gmail.com>
=> mount.8.adoc: document SELinux use of nosuid mount flag

sys-utils/mount.8.adoc
The section in man (8) mount for overlay is missing nine options which
aren't documented elsewhere either and are useful features to be aware
of and use.
Fixes #1350.
=> mount: man-page; add all overlayfs options

sys-utils/mount.8.adoc
The exclusivity between the {fscontext, defcontext} and context options
was removed in kernel 2.6.25[1]. No specific verification on these
options is done in mount(8)[2].
[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c9180a57a9ab2d5525faf8815a332364ee9e89b7
[2] https://github.com/karelzak/util-linux/blob/master/libmount/src/context_mount.c#L202
@pcmoore FYI
=> mount.8.adoc: Remove context options exclusion

tests/ts/blkdiscard/offsets, tests/ts/kill/all_processes, tests/ts/kill/name_to_number, tests/ts/kill/options, tests/ts/kill/print_pid, tests/ts/kill/queue
If the 'kill' test is executed with --use-system-commands, it calls
/bin/kill to avoid the shell's own kill command being invoked.
However, this doesn't work if the kill we want to test isn't in fact in
/bin.  Instead, use $(which kill) to find a kill on the PATH and call
that directly.
Signed-off-by: Ross Burton <ross.burton@arm.com>
=> Fix running the test suite with system commands

tests/ts/ul/ul
As with ul/basic, this test produces different output when ran under
different terminals, which isn't very useful.
Set TS_KNOWN_FAIL so that these problems don't cause the test to fail.
Signed-off-by: Ross Burton <ross.burton@arm.com>
=> tests: mark ul/ul as a known failure

tests/ts/eject/umount
This test tries to add asan to LD_PRELOAD because the just-built eject
will call the host /bin/umount, and apparently asan doesn't like this.
However, if ldd isn't present, this fails as the path to asan is the
error message saying that ldd isn't present.
As the asan workaround is only needed when executing the binaries that
have just been built and not the system binaries, only use it if the
test is on the built binaries.
Closes #1373.
Signed-off-by: Ross Burton <ross.burton@arm.com>
=> test/eject: guard asan LD_PRELOAD with use-system-commands check

configure.ac, libmount/src/context_veritydev.c, libmount/src/libmount.h.in, libmount/src/optmap.c, sys-utils/mount.8.adoc
Add verity.oncorruption= to let users override the default kernel
behaviour, using libcrypsetup's relevant flags.
=> verity: add support for corruption action flag and fix roothashsig parsing

sys-utils/mount.8.adoc
The PKCS7 RFC recommends to use .p7s for detached signatures file extensions,
so use that in the example.
https://datatracker.ietf.org/doc/html/rfc5751#section-3.2.1
=> mount: fix roothash signature extension in manpage

disk-utils/fdisk-menu.c, libfdisk/src/dos.c, libfdisk/src/gpt.c, libfdisk/src/label.c
Option 'f' currently prints following RED error message:
Nothing to do. Ordering is correct already.
Failed to fix partitions order.
This change removes RED error message when ordering is already correct.
=> fdisk: do not print error message when partition reordering is not needed

libblkid/src/superblocks/vfat.c
Older FAT16 variants do not have to contain boot label or serial id. Boot
sign 0x28 indicates that only serial id is present and boot sign 0x29
indicates that both boot label and serial id is present. Other boot sign
values (e.g. zero) indicates older FAT16 variant without boot label and
boot sign.
FAT32 can be formatted with boot sign 0x28 to indicate that only serial id
is present or with boot sign 0x29 which indicates that both boot label and
serial id is present.
=> libblkid: vfat: Fix reading boot label and serial id

sys-utils/mount.8.adoc
It has been around for a year and a half, and 3 releases.
@karelzak what do you think? It seems stable enough to me by now, and I will try to get it enabled by default for Debian 12, if we can unmark it as experimental.
=> verity: remove experimental tag from mount manpage

disk-utils/blockdev.c
commit 9147d2ad8a ("blockdev: Don't fail on missing start sector") limits
the size of the start sector to 10 digits.
Multi-terrabyte devices can have partitions with a start sector larger than
10 digits, which will cause an sprintf() to abort due to overflowing the buffer.
It causes:
RO    RA   SSZ   BSZ   StartSec            Size   Device
*** buffer overflow detected ***: terminated
Aborted (core dumped)
=> blockdev: allow for larger values for start sector

bash-completion/rename, misc-utils/rename.1.adoc, misc-utils/rename.c, tests/expected/rename/basic, tests/ts/rename/basic
Renaming files with rename often involves multiple passes in order
to, say, replace all spaces with underscores because traditionally
rename only replaces the first occurrence of the expression. The
--all parameter makes this task simple.
With the addition of --last, rename becomes much safer to use when
replacing file extensions, whereas before it would mangle a file
which had its extension also embedded elsewhere in its name.
The implied --first, together with --all and --last, round out the
common cases for renaming files.
=> rename: add --all and --last parameters

disk-utils/fdisk-menu.c, include/pt-mbr.h, libfdisk/docs/libfdisk-sections.txt, libfdisk/src/dos.c, libfdisk/src/libfdisk.h.in, libfdisk/src/libfdisk.sym
Add a new extended option 'F' to fdisk which recalculates and fixes CHS
values for each partition in MBR table according to current fdisk settings
for number of heads and sectors per track.
This allows in interactive mode to repair existing partitions to be
compatible with CHS addressing after changing extended option 'h' (number
of heads) or 's' (sectors per track) as these options do not modify content
of existing partitions.
=> fdisk: Add support for fixing MBR partitions CHS values

bash-completion/whereis
Currently, the Bash completions for `whereis <TAB>` gives `whereis file` ("file" is not a placeholder here, it literally expands to that). This fixes that by passing the `-c` flag to `compgen` to request completions for command names.
=> whereis: use commands for Bash completions

sys-utils/lscpu-arm.c
hi，
I found two Phytium Cpupart，so add them
=> lscpu:Add Phytium FT-2000+ & S2500 support

sys-utils/zramctl.8.adoc, sys-utils/zramctl.c
Add information about the possible value 'zstd' for the 'zramctl --algorithm'
option to 'zramctl --help' and zramctl (8) manpage. The kernel supports zram
with zstd compression starting with 4.15 (see
https://lore.kernel.org/lkml/20170912050005.3247-1-sergey.senozhatsky@gmail.com/#r).
Signed-off-by: Jan Samek <samekh@email.cz>
=> zramctl: add zstd compression algorithm option

disk-utils/fsck.minix.8.adoc
The printed message is `FILE SYSTEM HAS BEEN CHANGED`, according to [disk-utils/fsck.minix.c line 1418](https://github.com/karelzak/util-linux/blob/master/disk-utils/fsck.minix.c#L1418)
=> asciidoc: fix quoted message in fsck.minix

disk-utils/fdisk.8.adoc
Not using unconstrained will result in showing asterisk instead, which is unwanted.
```
... is for example '*-u=*cylinders'.
```
=> asciidoc: unconstrained formatting pair in fdisk

text-utils/more.c
Erase the line on screen before writing the filename.
=> more: Missing erase_line for option --print-over

lib/loopdev.c, sys-utils/losetup.c
This avoids an extra syscall, and allows the kernel to automatically set
block size [0], avoiding unnecessary failure with 4096-byte devices.
This changes the observable behavior of losetup --direct-io in the case
where DIO is not supported to fully fail, instead of creating a
non-direct-io device. If the user explicitly specifies --direct-io, then
they should get either a DIO loopdev or no loopdev, not a non-DIO
loopdev and a misleading error.
Additionally, loopcxt_setup_device now uses O_CLOEXEC in the read-only
fallback.
[0] https://github.com/torvalds/linux/commit/85560117d00f5d528e928918b8f61cadcefff98b
=> losetup: directly set dio instead of afterwards

text-utils/more.c
Closes #1448 
it was the following line which was actually sending shell_line to `stdout` instead of `stderr`
https://github.com/karelzak/util-linux/blob/78001b7af36f685265e21feaf384a4be12118c64/text-utils/more.c#L1288
Credits - @Aulonsal
Previous Behaviour
New Behaviour
=> more - Bug Resolve - new line separated command re execution

login-utils/login.c
If login receives the tty to work on via stdin, stdout and stderr,
login might end up closing the remaining open file descriptors to
the tty just before it calls vhangup(). When the last open file
descriptors to a tty are closed, it's configured size is reset to
0x0. To avoid this from happening, save the size before closing
the stdin, stdout and stderr file descriptors and reapply the size
after the tty is re-opened.
Fixes #1484
=> login: Restore tty size after calling vhangup()

.github/workflows/cibuild-setup-ubuntu.sh, .github/workflows/cibuild.sh, .github/workflows/coverity.yml, Documentation/howto-tests.txt
To get it to work a secret named COVERITY_SCAN_TOKEN should
be added to the util-linux repository:
https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository
It has to match the util-linux project token, which
can be found at
https://scan.coverity.com/projects/karelzak-util-linux?tab=project_settings
Signed-off-by: Evgeny Vereshchagin <evvers@ya.ru>
=> ci: add a GHAction sending data to Coverity

misc-utils/lsfd.1.adoc
The OWNER option in lsfd.1.adoc has single underscores (_string_) which appear literally in the rendered man page. Changed to double underscores.
=> lsfd.1.adoc: Add missing underscores

lib/sysfs.c
Because of the commit [libblkid: use /sys to read all block devices](https://github.com/util-linux/util-linux/commit/8d3f9430c59416e4c1eddc899578158a7a1ed414#diff-2376ac4742ecca128eea0f972266b72b02d8730bf7169dc67988f6444f357fc4R511-R512) tools like `fsck` are broken on systems not including the parent name in partition name. This happen on embedded devices what are using eMMC.
Like the parent name is `mmcblk0` and the partition is named in Android style like `system` or `data`.
This PR will check if the parent name is included in partition name at all, if not it fall back to the "old" method and the tools using function `sysfs_blkdev_is_partition_dirent` are working again.
=> sysfs: fallback for partitions not including parent name

login-utils/vipw.c
Always set SIGCHLD handler to default, even if the caller of vipw has
set SIGCHLD to ignore. If SIGCHLD is ignored no zombie processes would
be created, which in turn could mean that kill is called with an already
recycled pid.
Also improved error message if child process fails.
Proof of Concept:
1. Compile nochld:
--
#include <signal.h>
#include <unistd.h>
int main(void) {
char *argv[] = { "vipw", NULL };
signal(SIGCHLD, SIG_IGN);
execvp("vipw", argv);
return 1;
}
--
2. Run nochld
3. Suspend child vi, which suspends vipw too:
`kill -STOP childpid`
4. Kill vi:
`kill -9 childpid`
5. You can see with ps that childpid is no zombie but disappeared
6. Bring vipw back into foreground
`fg`
7. See misleading warning message
You will get an improperly formatted warning message. Also the wake up …
=> vipw: improve child error handling

include/fileutils.h, include/pidfd-utils.h, lib/cpuset.c, lib/randutils.c, schedutils/ionice.c, schedutils/sched_attr.h, sys-utils/hwclock.c
Some platforms do not provide sys/syscall.h. The configure script already
checks for the existance of the file. Include sys/syscall.h only in case
HAVE_SYS_SYSCALL_H has been set.
=> Do not include sys/syscall.h if not available

lib/loopdev.c
qemu returns this if it doesn't understand the ioctl. according to ioctl(2) it should actually return EINVAL, but considering that it's been doing this for at least 20 years already, I doubt there's much appetite for change, considering that it has a slightly better error message if propagated back to the user and changing it to EINVAL may break other programs.
=> loopdev: accept ENOSYS for LOOP_CONFIGURE

disk-utils/sfdisk.8.adoc, misc-utils/wipefs.8.adoc
In AsciiDoc, double parentheses are used to mark flow index terms, but in this document, their use is intended to be interpreted by the shell's arithmetic expansion.  By escaping them with a backslash in the AsciiDoc, they pass through as-is to the manpage and other targets.
So, instead of a rendered result of `dd if=~/wipefs-sdb-0x00000438.bak of=/dev/sdb seek=$0x00000438 bs=1 conv=notrunc`, we get `dd if=~/wipefs-sdb-0x00000438.bak of=/dev/sdb seek=$((0x00000438)) bs=1 conv=notrunc`.  
Seperately, when interpreted by a shell's arithmetic expansion, the $((0x00000438)) hex is converted to decimal 1080 `dd if=~/wipefs-sdb-0x00000438.bak of=/dev/sdb seek=1080 bs=1 conv=notrunc`
=> wipefs, sfdisk man: Escape ((…)) in AsciiDoc

configure.ac
check for required kernel header file `kcmp.h` and add configure options to disable `lsfd`
see as well #1511
=> lsfd: check for required header file and add configure option to disable lsfd

tests/ts/lsfd/mkfds-socketpair
The protoname for a socket can be get from its xattr slot of
/proc/$PID/fd/$FD.
The protoname for (AF_UNIX, SOCK_STREAM) sockets was changed
from "UNIX" to "UNIX-STREAM" in
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=94531cfcbe79c3598acf96806627b2137ca32eb9
As the result, the test case, mkfds-socketpair doesn't work well on a
newer kernel.
To mitigate the impact of the change in the kernel, use (AF_UNIX, SOCK_DGRAM)
for making a socket pair.
In the commit, the protoname of (AF_UNIX, SOCK_DGRAM) sockets was also changed
to "UNIX-DGRAM". However, it was renamed back to "UNIX" in
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0edf0824e0dc359ed76bf96af986e6570ca2c0b9
Partially close #1511.
Signed-off-by: Masatake YAMATO …
=> tests: (lsfd) make DGRAM socketpair to mitigate the change of protoname

login-utils/login.c, login-utils/su-common.c
As documented here:
http://www.linux-pam.org/Linux-PAM-html/adg-interface-by-app-expected.html#adg-pam_end
The child that is about to exec*() the user shell is supposed to pam_end()
with PAM_DATA_SILENT. This gives the modules a last chance to do a minor
cleanup of the module state before the user's shell is launched.
Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
=> Complete Linux-PAM compliance for forked child in su and login.

sys-utils/lscpu-arm.c
See https://www.spinics.net/lists/arm-kernel/msg879381.html and https://en.wikipedia.org/wiki/FeiTeng_(processor)#Future_processors (S2500 and D2000 are SoCs and contain 4 or 8 FTC663 cores).
=> Add Apple cores, fix Phytium core names

tests/ts/lsfd/mkfds-socketpair
This is a follow-up commit to a60ac11fe0087584f37329b4733edfade3452c64.
>    In the commit, the protoname of (AF_UNIX, SOCK_DGRAM) sockets was also
>    changed to "UNIX-DGRAM". However, it was renamed back to "UNIX" in
>    https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0edf0824e0dc359ed76bf96af986e6570ca2c0b9
To make this test case more portable, this change makes the test case
accept "UINX-DGRAM" in addition to "UINX", too.
=> tests: (lsfd) normalize protoname before comparing

term-utils/script.1.adoc
=> script.1.adoc: correct socond as second

sys-utils/swapon.c
For alpha linux, the `struct stat` is a little different with other 64 bits architecture.
https://github.com/bminor/glibc/blob/bada2e312a8b94c5fc2f5571b249c71cb466a640/sysdeps/unix/sysv/linux/alpha/bits/struct_stat.h#L36-L42
https://github.com/bminor/glibc/blob/bada2e312a8b94c5fc2f5571b249c71cb466a640/sysdeps/unix/sysv/linux/alpha/bits/typesizes.h#L41-L42
The `st_blocks` is a `__U32_TYPE` member, which causes a integer overflow for swapon's file holes checking.
https://github.com/util-linux/util-linux/blob/2401078c9cf9ddec105e44af074cf2fcbd4ef153/sys-utils/swapon.c#L546
This PR should fix it.
=> Fix integer overflow for alpha like linux

misc-utils/uuidgen.1.adoc
Hi
This indication mirrors the one found in uuidparse.1.adoc, pointing back to uuidgen.1.adoc
Having this mention is particularly useful in man systems that automatically add hypertext links to ease navigation between related command documentations.
Thanks.
=> uuidgen.1.adoc: mention uuidparse in SEE ALSO

disk-utils/fdisk-list.c, lib/ismounted.c
When autoclose is set (kernel default) opening a CD-rom
device causes the tray to close.
The fdisk command is also used extensively in scripts, so
it may also interfere with the user's operation of the CD-rom hardware.
Signed-off-by: changlianzhi <changlianzhi@uniontech.com>
=> fdisk: open device in nonblock mode

misc-utils/look.c
Co-authored by: khaleesi <contact@khaleesicodes.com>
Co-authored by: stoeckmann <tobias@stoeckmann.org>
=> Remove duplicate 'setlocale' call in look.c

disk-utils/fdisk.c
When autoclose is set (kernel default) opening a CD-rom
device causes the tray to close.
Signed-off-by: lishengyu <lishengyu@uniontech.com>
=> fdisk: when use fdisk -l, open device in nonblock mode

disk-utils/sfdisk.8.adoc, misc-utils/findmnt.8.adoc, misc-utils/hardlink.1.adoc, misc-utils/lsfd.1.adoc, sys-utils/adjtime_config.5.adoc, sys-utils/blkzone.8.adoc, sys-utils/fstrim.8.adoc, sys-utils/hwclock.8.adoc, sys-utils/irqtop.1.adoc, sys-utils/lsns.8.adoc, sys-utils/mount.8.adoc, sys-utils/nsenter.1.adoc
With the latest man page changes and additions, some wrong punctuation, markup, wording and typos need to be fixed again.
From mount.8.adoc:
```
*exec*::
Permit execution of binaries.
```
I think it doesn't refer to binaries only; merely it also includes other types of executable files (scripts etc.). Then we should write something like:
*exec*::
Permit execution of binaries and other executable files like scripts.
=> man pages: Fix punctuation, wording and markup

sys-utils/losetup.8.adoc
"-f" and "loopdev" cannot be used together, the pipe was lost
when converting the man pages to asciidoc.
=> losetup: Add missing pipe to man example for setting up loop device

login-utils/sulogin.c
If some error happens during password input, 
all kinds of errno will be displayed for investigation of the problem.
=> sulogin: Display all kinds of errno during password input.

login-utils/su-common.c
Enable PID in syslog lines for `su`.
In Gentoo Linux, we recently switched `su` providers from
shadow to util-linux.
It was notiiced that syslog output differs slightly
with util-linux (no PID):
```
Jan  7 20:00:50 localhost su: (to root) root on pts/5
Jan  7 20:00:50 localhost su: pam_unix(su:session): session opened for user root(uid=0) by sam(uid=0)
```
... whereas shadow's `su` gave (with PID):
```
Jan  7 20:52:50 localhost su[22245]: Successful su for root by root
Jan  7 20:52:50 localhost su[22245]: + /dev/pts/5 root:root
```
This change enables PID logging to give shadow-like syslog
output for `su`:
```
Jan  7 20:54:32 localhost su[10827]: (to root) root on pts/6
Jan  7 20:54:32 localhost su[10827]: pam_unix(su:session): session opened for user root(uid=0) by sam(uid=0)
``` …
=> su: use LOG_PID for syslog

sys-utils/unshare.c
Kill the child explicitly should the parent terminate just before the child invokes prctl(PR_SET_PDEATHSIG).
The underlying issue can be reproduced as follows:
```
#!/bin/bash
rm -f /tmp/unshare.log.*
strace -ff -tt -o /tmp/unshare.log /usr/bin/unshare --kill-child --fork true
head -1 /tmp/unshare.log.*
while : ; do
PARENT=$(
/usr/bin/unshare --kill-child --fork bash -c 'echo $PPID' &
sleep 0 # sleep 0.00$RANDOM
kill -9 $! 2>/dev/null
)
[ "$PARENT" != 1 ] || { echo "$PARENT" ; break ; }
done
```
This scenario is also described in https://stackoverflow.com/a/36945270:
> Note that storing the parent process id before the fork and testing it in the child after prctl() eliminates a race condition between prctl() and the exit of the process that called the child.
=> unshare: Fix PDEATHSIG race for --kill-child

text-utils/more.c
When a quit character is seen, immediately return that command, as it is the correct operation to perform in this case.
A bigger fix is needed here, in that we need to have a *queue* of operations to perform, rather than a single one
=> Return immediately when quit is seen

sys-utils/lscpu.c
The logic in print_summary_cputype() starts a new hierarchy level under
the CPUs "Model name" entry. If the model is unknown the hierarchy level
will be skipped. This is visually confusing in the human-readable
version and changes the schema of the JSON tree.
=> lspcu: Print dummy modelname if none present

sys-utils/meson.build
When systemd is disabled, the variable `systemdsystemunitdir` is
missing, and thus we cannot install fstrim.service to it.
This commit simply disables installing this service if systemd is not
found or disabled.
Signed-off-by: Martin Roukala (né Peres) <martin.roukala@mupuf.org>
=> meson: do not generate fstrim.service if we do not have systemd

text-utils/more.c
Sami Kerola pointed out that /proc contains files with zero size but
content in ec4153cc28c718e064a1992a76a63ec7696d33a6.
Eventually fixes for better type handling have been committed with
ba105bb5eb0052ee7d85d0903ad4ae9e87114930 and error handling when "more"
is called with directories in 32a4efc5675ca238d382a0027f7f4723b8b3af28.
This commit fixes a regression and wrong file size handling:
checkf ends execution prematurely if st.st_size is 0. The idea was to
skip the check_magic call which would otherwise claim that a text file
would not be one, e.g. /proc/self/wchan would fail otherwise. This has
two consequences:
1. The last check in checkf is never true, because if st_size is 0 we
already left the function (file_size and st_size are both off_t).
Proof of Concept (use a window with …
=> more: improve zero size handling

misc-utils/findmnt.c
Previously columns excluded from --output-all where in fact stored as
column index 0. This however is COL_ACTION which is a polled column
leading to the following error:
findmnt --output-all
findmnt: ACTION column is requested, but --poll is not enabled
=> findmnt: properly exclude poll columns from --output-all

misc-utils/lsfd-file.c
The type used for casting the member was too small; for the
"%ju" format spec, we should use uintmax_t for the purpose.
This change may fix the bug reported in
https://github.com/util-linux/util-linux/issues/1511#issuecomment-1033697617
in GitHub#1511 by Anatoly Pugachev <matorola@gmail.com>.
=> lsfd: fix the way to print stat.st_nlink

sys-utils/dmesg.c
This improves colouring when certain message levels are configured to
display a background colour using terminal-colors.d. Previously the
background colour starts at ":" on messages with a subsystem present,
which looks pretty odd. Now it starts from the remaining message after
the subsys (if there is one).
If one only uses foreground colours, this largely makes no difference:
the colon is now coloured with the same subsys colour, but there's no
difference for the blank.
Signed-off-by: Chris Down <chris@chrisdown.name>
=> dmesg: Start colouring subsys delimiter only after trailing blank

libuuid/src/parse.c
It attempts to access in_start[36], despite 35 being the maximum
allowed index.
=> libuuid: fix buffer overrun in uuid_parse_range()

lib/ismounted.c
Following snippet proves that the program crashes on BSD systems:
```c
#include <stdio.h>
extern int check_mount_point(const char *device, int *mount_flags,
char *mtpt, int mtlen);
int
main(void)
{
char buf[4096];
int x;
check_mount_point("not_mounted", &x, buf, sizeof(buf));
return 0;
}
```
You might compile it with following instructions:
```console
user@host:util-linux$ cc -c poc.c
user@host:util-linux$ cc -o poc poc.o lib/is_mounted.o
user@host:util-linux$ MALLOC_OPTIONS=JJ ./poc
```
Shoutout to [c3h2-ctf](https://twitter.com/c3h2_ctf)!
=> Fix crash, when mount was not found on BSD systems

sys-utils/blkzone.c
If `blkzone` is built against kernel headers that do not define
`BLK_ZONE_REP_CAPACITY`, `blkzone report` will use zone size when printing zone
capacity. This patch changes the behavior of `blockzone report` in this case to
omit the capacity field instead of using the potentially wrong value.
=> blkzone: Do not print zone capacity if not supported

tests/helpers/test_mkfds.c
Close #1637.
The test cases assumed the file descriptor #3 was not occupied. As
reported in #1637, the assumption was wrong. This new code assigns
the file descriptor #3 explicitly with dup2 as the other test cases
did.
=> tests: (lsfd) add missing dup2 calls to assign proper file descriptors

misc-utils/lsfd-filter.c
The original code cannot convert "" in filter expression to
a token correctly. The following command line exposes the
bug this change fixes:
```console
zsh: IOT instruction  sudo ./lsfd -Q '(TYPE == "")'
```
=> lsfd: (filter): parse "" in filter expression correctly 

tests/ts/misc/setarch
`setarch` fails if run in a docker container, so exclude (ts_skip) misc/setarch from running in a docker.
Fixes: #601
=> tests: fix misc/setarch run in a docker environment

tests/helpers/Makemodule.am
macos is missing linux only `sys/prctl.h` header, so exclude `tests/helpers/test_mkfds.c`
on macos from `make check-programs` target
fixes fd81d3a558
```
util-linux$ make check-programs
CC       tests/helpers/test_mkfds.o
tests/helpers/test_mkfds.c:29:10: fatal error: 'sys/prctl.h' file not found
#include <sys/prctl.h>
^~~~~~~~~~~~~
1 error generated.
make: *** [tests/helpers/test_mkfds.o] Error 1
util-linux$ uname -a
Darwin puga.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
```
=> tests: don't compile lsfd/mkfds helper on macos

misc-utils/meson.build
I'm a Devuan user (with runit) and I had a problem building util-linux in Devuan.
=> Don't install uuidd service if systemd isn't present

lib/env.c
This allows users to override settings like BLKID_FILE, as is done in
the e2fsprogs test suite.
Bug: https://bugs.gentoo.org/839825
Fixes: 035507c84b53bceb143d0923e65916cbf90979c7
Signed-off-by: Mike Gilbert <floppym@gentoo.org>
=> lib: allow safe_getenv to work for non-root users

meson.build
I could be wrong, but 'have' should be used instead of 'have_dirfd' when HAVE_CLOCK_GETTIME is set.
Nicolas Caramelli
=> meson: fix when HAVE_CLOCK_GETTIME is set

include/bitops.h
Newer versions of FreeBSD will have a glibc compatible
byteswap.h. Currently, this file assumes that FreeBSD requires
bswap{16,32,64} to always be defined. This isn't the case when we're
using the byteswap.h file (which is enabled by HAVE_BYTESWAP_H
define). Assume that if byteswap.h and endian.h are present, then the
proper macros are defined.  Otherwise, assume that sys/endian.h is
present and paper over the small differences between the BSDs for this
file.
Signed-off-by: Warner Losh <imp@bsdimp.com>
=> BSD: Use byteswap.h and endian.h defined macos when present

sys-utils/fstrim.c
Some filesystems like bindfs report ENOSYS (Function not implemented) for the trim ioctl, which should be caught by --quiet-unsupported.
=> fstrim: check for ENOSYS when using --quiet-unsupported

schedutils/taskset.c
The err_affinity() function outputs error information when sched_getaffinity() or sched_setaffinity() executes abnormally.
After calling sched_getaffinity(), we should call err_affinity() as err_affinity(ts->pid, 0) to output "failed to get pid %d's affinity" in the case sched_getaffinity() is failed.
=> A little mistake in do_taskset() function in taskset.c.

misc-utils/hardlink.c
=> hardlink: change the default comparison method on Mac OS

configure.ac, meson.build, misc-utils/Makemodule.am, misc-utils/lsfd-decode-file-flags.c, misc-utils/lsfd-file.c, misc-utils/meson.build, tests/expected/lsfd/mkfds-directory
Close #1709.
The original code decoded the field using constants defined in
/usr/include/fcntl.h. The constants defined in /usr/include/fcntl.h
was suitable for passing to the kernel as a part of arguments of
system calls like open(2). However, they were not suitable for
decoding the field.
Let's think about decoding 0300000 in
$ cat /proc/157067/fdinfo/3
pos:	0
flags:	0300000
$ lsfd -p 157067 -o+flags -Q -Q 'ASSOC == "3"'
COMMAND       PID USER ASSOC MODE TYPE SOURCE MNTID INODE NAME               FLAGS
test_mkfds 125128  jet     3  r--  DIR   dm-0    96    96 /    ???????????????????
The decoded string is printed at ???????????????????.
Quoted from /usr/include/bits/fcntl-linux.h:
#ifndef __O_LARGEFILE
#endif
#ifndef __O_DIRECTORY
#endif
#ifndef __O_TMPFILE
#endif
...
#ifdef …
=> lsfd: use constants defined in asm/fctl.h flags field of a fdinfo

misc-utils/lsfd-decode-file-flags.c
Close #1720.
The original code tried including asm-generic/fcntl.h before trying
including asm/fcntl.h. This caused a bug in decoding flag of fdinfo
on Linux running on armv7l.
=> lsfd: try including asm/fcntl.h first for decoding flags of fdinfo

misc-utils/lsfd-decode-file-flags.c
The definition of O_FOLLOW was checked. However, it was
a typo of O_NOFOLLOW.
The definition of O_FASYNC was checked. However, it was
a typo of FASYNC.
Test cases are under development.
=> lsfd: fix wrongly checked flag constants

tests/ts/lsfd/mkfds-directory
Close #1717.
If the file system where the target directory is is mounted with
"noatime" flag, Linux kernel may set O_NOATIME to the fd associated
with the target directory. As a result, mkfds-directory test failed.
With this change, mkfds-directory deletes "noatime" from the output
of lsfd before verifying the output if "noatime" mount flag is set
to the file system where the directory opened by mkfds-directory is.
=> test: (lsfd) ignore noatime mnt flag when testing a fd opening / directory

tests/expected/lsfd/mkfds-symlink
Though the code of lsfd was changed in 4b496e50ee4f6bd8256d082a85fc027a7eaa45cb,
the expected output of the test case was not updated.
=> tests: (lsfd) update the expected output for "test_mkfds symlink"

misc-utils/lsfd.c
`struct ipc' is the data structure used behind ENDPOINTS field.
The objects of the data structure and its hash table were not
freed.
=> lsfd: fix memory leak related to ENDPOINTS field

sys-utils/lsns.c
==28129== 96 bytes in 3 blocks are possibly lost in loss record 1 of 4
==28129==    at 0x4837B65: calloc (vg_replace_malloc.c:752)
==28129==    by 0x405C83: xcalloc (xalloc.h:60)
==28129==    by 0x405C83: netnsid_cache_add (lsns.c:389)
==28129==    by 0x405C83: get_netnsid (lsns.c:486)
==28129==    by 0x405C83: read_process (lsns.c:549)
==28129==    by 0x403FB4: read_processes (lsns.c:586)
==28129==    by 0x403FB4: main (lsns.c:1417)
==28129==
==28129== 119,664 (384 direct, 119,280 indirect) bytes in 1 blocks are definitely lost in loss record 4 of 4
==28129==    at 0x4837B65: calloc (vg_replace_malloc.c:752)
==28129==    by 0x4055F5: xcalloc (xalloc.h:60)
==28129==    by 0x4055F5: read_process (lsns.c:516)
==28129==    by 0x403FB4: read_processes (lsns.c:586)
==28129==    by 0x403FB4: …
=> lsns: fix the memory leak.

term-utils/agetty.c
My issue file looks like this:
```
oooooo   oooooo     oooo           oooo
`888.    `888.     .8'            `888
`888.   .8888.   .8'    .ooooo.   888   .ooooo.   .ooooo.  ooo. .oo.  .oo.    .ooooo.
`888  .8'`888. .8'    d88' `88b  888  d88' `"Y8 d88' `88b `888P"Y88bP"Y88b  d88' `88b
`888.8'  `888.8'     888ooo888  888  888       888   888  888   888   888  888ooo888
`888'    `888'      888    .o  888  888   .o8 888   888  888   888   888  888    .o
`8'      `8'       `Y8bod8P' o888o `Y8bod8P' `Y8bod8P' o888o o888o o888o `Y8bod8P'
You're running                                                Today is: \d
\s \r                                                              Time: \t
```
It's just a cutesy message that prints your kernel version on the left and time and date on the right. …
=> add padding to dates in issue file

sys-utils/lscpu-arm.c
ARM revealed recently that [their cores formerly known as Makalu/Makalu-ELP are A715 and X3 respectively](https://forums.anandtech.com/threads/arm-cortex-x3-cortex-a715-announcement.2605032/).
Also there are no Cortex-510/Cortex-710 but they still have an A in their name: https://review.trustedfirmware.org/plugins/gitiles/TF-A/trusted-firmware-a/+/refs/heads/master/include/lib/cpus/aarch64/
=> Add ARM Makalu/Makalu-ELP cores (A715/X3)

sys-utils/lscpu-arm.c
Adding Apple core names, distinguish by SoC/SiP name [as suggested](https://github.com/util-linux/util-linux/pull/1737#issuecomment-1172068860).
=> Adding Apple core names, distinguish by SoC/SiP name

misc-utils/rename.c, tests/expected/rename/basic, tests/expected/rename/subdir, tests/ts/rename/basic, tests/ts/rename/subdir
This fixes two bugs when the `from` argument is the empty string.
* When the `to` argument doesn't contain a `/`, but the file path does, the `from` should be put at the beginning of the filename. Instead it was being put immediately before the final `/`:
rename '' _ ./foo.txt 
* Given `-a`, an empty `from` argument would hang, looping indefinitely in `string_replace`. It now places `to` in between every character of the filename, or every character of the full path if `to` contains a `/`.
rename -a '' _ foo.txt
I also replaced some `2> $TS_ERRLOG` with `2>> $TS_ERRLOG` in the rename tests, because that seemed correct. Fortunately there doesn't seem to have been any previous error output to clobber.
I could split these into three PRs if that's preferred, but they seemed related enough …
=> Rename: improve handling of empty `from` argument

sys-utils/unshare.c
This problem affected the --map-auto and --map-groups=auto command-line switches.
The root cause is that /etc/subgid is indexed by user or uid, not by group or gid;
therefore, we should be using the effective uid to find entries in this file, just
as we do for /etc/subuid.
Signed-off-by: Sol Boucher <sboucher@cmu.edu>
=> unshare: Fix "you (user xxxx) don't exist" error when uid differs from primary gid

sys-utils/lscpu-arm.c
Just to remove the leftovers from previous attempt :)
=> Remove closing braces in Apple cores names

misc-utils/lsfd-filter.c, tests/expected/lsfd/option-filter-broken-exp, tests/ts/lsfd/option-filter-broken-exp
$ lsfd -Q ''
or
$ lsfd --filter ''
made lsfd process crash.
=> lsfd: fix crash triggered by an empty filter expression

libblkid/libblkid.3.adoc
Sorry for a long silence, finally got to that point on my todo. As discussed at the end of the May I added tags description to man pages of libblkid. Mostly it the same information as in `superblocks.c` but structured and with more detailed description of FSSIZE. I hope that this is what you thought of :)
The better place for this would be man page for `blkid_probe_set_superblocks_flags()` but I think it's not the best idea to have man page only for one function of the whole interface :)
=> libblkid: add tags list to the man

sys-utils/blkzone.c
The zone offset and length alignment checks are based on a power-of-2(po2)
zone size assumption.
Make that calculation generic as there are ongoing efforts[1] to support
zoned devices with non-po2 zone sizes.
[1]
https://lore.kernel.org/all/20220803094801.177490-1-p.raghav@samsung.com/
Signed-off-by: Pankaj Raghav <p.raghav@samsung.com>
=> blkzone: make alignment check for zone size generic

configure.ac, include/pidfd-utils.h
This header in newer glibc defines the signatures of functions
pidfd_send_signal() and pidfd_open() and when these functions are
defined by libc then we need to include the relevant header to get
the definitions. Clang 15+ has started to error out when function
signatures are missing.
Fixes errors like
misc-utils/kill.c:402:6: error: call to undeclared function 'pidfd_send_signal'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
if (pidfd_send_signal(pfd, ctl->numsig, &info, 0) < 0)
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> check for sys/pidfd.h

misc-utils/lsfd-unkn.c, misc-utils/lsfd.1.adoc, misc-utils/lsfd.c, misc-utils/lsfd.h, tests/expected/lsfd/mkfds-pidfd, tests/helpers/test_mkfds.c, tests/ts/lsfd/mkfds-pidfd
Example output:
```
$ sudo ./lsfd -Q '(NAME =~ "pidfd: .*")'
COMMAND           PID  ... TYPE       SOURCE ... NAME
dbus-broker-lau  1010  ... UNKN anon_inodefs ... pidfd: pid=1015 comm=dbus-broker nspid=1015
dbus-broker-lau 14786  ... UNKN anon_inodefs ... pidfd: pid=14788 comm=dbus-broker nspid=14788
dbus-broker-lau 15051  ... UNKN anon_inodefs ... pidfd: pid=15053 comm=dbus-broker nspid=15053
```
=> lsfd: show pids targeted by pidfds in NAME column

meson.build
84732a8849a introduced this check for autotools.
=> meson: check for sys/pidfd.h

libblkid/src/topology/dm.c
=> libblkid/src/topology/dm: close redundant write file description for pipe before reading data.

configure.ac
Check whether magic.h header exists before defining HAVE_MAGIC.
Despite library availability there still can be missing header.
Current test doesn't cover that possibility which will lead compilation
to fail in case of separate sysroot.
Signed-off-by: Mateusz Marciniec <mateuszmar2@gmail.com>
Signed-off-by: Tomasz Dziendzielski <tomasz.dziendzielski@gmail.com>
=> configure.ac: Improve check for magic

tests/functions.sh, tests/ts/look/separator, tests/ts/mount/remount
The `egrep` command has been deprecated since GNU grep 2.5.3 (released in 2007).
In GNU grep 3.8, it issues an obsolescence warning:
https://git.savannah.gnu.org/cgit/grep.git/commit/?id=a9515624709865d4
Use portable `grep -E` instead.
=> Use "grep -E" instead of "egrep"

libblkid/src/superblocks/bcache.c
Split out from #1274 because that one seems to take longer.
=> libblkid: bcache: cleanups and wiper

misc-utils/lsfd.c
In be019f664db6eef7f2df38d31f1627d74a82fe65, I changed the counter expression used in --summary output unexpectedly.
=> lsfd: fix wrong counter expression used in --summary output

libblkid/src/superblocks/f2fs.c
* Make sure dynamic checksum offset is within superblock
* Correctly initialize checksum on big-endian
Fixes #1813
=> f2fs fixes

lib/path.c
Kernel 5.15 returns empty content for topology/thread_siblings on aarch64 platform, which in conjunction of uninitialized `buf` memory buffer results in the garbage:
```
(gdb) p buf
$14 = " @\377\367\177\000\000\000\275\000\347j\032\236"
```
This garbage is then being later consumed by underlying helper functions like for example cpumask_parse() and this leads to the following crash later:
```
in __libc_free (p=0x7ff7f67c00) at src/malloc/mallocng/free.c:105
in free (p=<optimized out>) at src/malloc/free.c:5
in add_cpuset_to_array (setsize=<optimized out>, set=<optimized out>, items=<optimized out>, ary=<optimized out>) at ../sys-utils/lscpu-topology.c:29
in cputype_read_topology (cxt=cxt@entry=0x7ff7fffe70, ct=0x4298a0) at ../sys-utils/lscpu-topology.c:153
in lscpu_read_topology …
```
=> lib/path: ul_path_cpuparse: fix parsing of empty sysfs files

.github/workflows/cibuild.yml, .github/workflows/cifuzz.yml, .github/workflows/coverity.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

configure.ac, misc-utils/Makemodule.am, misc-utils/fadvise.1.adoc, misc-utils/fadvise.c, misc-utils/meson.build, tests/commands.sh, tests/expected/fadvise/drop, tests/ts/fadvise/drop
For measuring and monitoring the performance aspect of a command, people may want to drop the page caches related to specified files.
In some cases, writing 1 to /proc/sys/vm/drop_caches is overkill.  The fadvise command can be used for dropping page caches related to specified files; the impact on a system is much smaller than /proc/sys/vm/drop_caches.
=> fadvise: new command wrapping posix_fadvise

.gitignore
The fadvise binary was missing from the .gitignore, so it's been added.
At the same time I also sorted the binaries for those nice eye candy
points :)
=> build-sys: sort the gitignore and add fadvise

configure.ac, disk-utils/cramfs.h, include/bitops.h, lib/md5.c, lib/sha1.c, libblkid/src/superblocks/minix.c, sys-utils/lscpu.c, tests/helpers/test_sysinfo.c
This define is specific to autotools. Not defining the macro will lead to silently miscompiled code as has happened with the meson build.
Instead use macros provided by the compiler itself. It does not need any support from the buildsystem and is supported by both gcc and clang.
If a compiler does not support this feature we will get a loud error instead of silent miscompilation.
Furthermore it probably better supports universal binaries on macOS which compiles multiple architectures in a single build.
=> autotools: stop using AC_C_BIGENDIAN / WORDS_BIGENDIAN

misc-utils/fadvise.c
I forgot deleting the struct definition in the last pull request.
=> fadvice: delete a unused struct definition

libblkid/src/superblocks/exfat.c
Exfat filesystem probe can use undefined shift if block_bits or bpc_bits is a bogus value. Avoid this by limiting shift size.
Reproducer found with OSS-Fuzz (issue 52571) running over cryptsetup project (blkid is used in header init).
=> libblkid: exfat - avoid undefined shift

misc-utils/lsfd-sock-xinfo.c
=> lsfd: make the logic for verifying the initial line of /proc/net/{tcp,udp} more flexible

libblkid/src/superblocks/jfs.c
JFS probe can use undefined shift if stored log2 of block size is a bogus value. Avoid this by limiting shift size.
Reproducer found with OSS-Fuzz (issue 52643) running over cryptsetup project (blkid is used in header init).
Signed-off-by: Milan Broz <gmazyland@gmail.com>
=> libblkid: jfs - avoid undefined shift

misc-utils/kill.1.adoc, misc-utils/kill.c
In production we've had several incidents over the years where a process has a signal handler registered for SIGHUP or one of the SIGUSR signals which can be used to signal a request to reload configs, rotate log files, and the like. While this may seem harmless enough, what we've seen happen repeatedly is something like the following:
1. A process is using SIGHUP/SIGUSR[12] to request some application-handled state change -- reloading configs, rotating a log file, etc;
2. This kind of request is deprecated and removed, so the signal handler is removed. However, a site where the signal might be sent from is missed (often logrotate or a service manager);
3. Because the default disposition of these signals is terminal, sooner or later these applications are going to be sent SIGHUP or …
=> kill: Support mandating the presence of a userspace signal handler

sys-utils/lscpu.c
Otherwise the "Address sizes" and "Byte Order" end up on unexpected hierarchy levels.
=> lscpu: always create Architecture section

term-utils/agetty.c
I know it doesn't matter much in practice because nobody should create user names with leading hyphens anyway, but shouldn't `agetty` *always* pass the user name to `login` with a preceding `--`? To omit it with `-f` would make sense if `-f` took the user name as an optarg, but neither [util-linux](https://github.com/util-linux/util-linux/blob/96ccdc00e1fcf1684f9734a189baf90e00ff0c9a/login-utils/login.c#L1321) nor [shadow-utils](https://github.com/shadow-maint/shadow/blob/eaebea55a495a56317ed85e959b3599f73c6bdf2/src/login.c#L284) `login` seem to work like that
Note: I only tested this very briefly, by adding a drop-in for one of my `getty@.service` instances to make it call my modified `agetty` with `--autologin <user>`. That seemed to work as expected
=> agetty: always pass user name to login with --

libblkid/src/superblocks/superblocks.c
In the stable version, the BLOCK_SIZE attribute is unconditionally set when probing the device.
Commit c9b2297eb1f357d9bc9989aacc874f218081fcb8 added a new FSINFO flag and conditionally set the BLOCK_SIZE attribute only when it is used.
This breaks the ABI interface. Cryptsetup reencrypt code depends on checking the minimal accessible FS block to prevent the destruction of the filesystem if a user requests reencryption to a larger sector than
the filesystem can handle.
This patch removes the condition to make ABI compatible again (as we cannot add FSINFO bit retrospectively).
Signed-off-by: Milan Broz <gmazyland@gmail.com>
=> libblkid: fix regression in setting BLOCK_SIZE value

Documentation/deprecated.txt, Documentation/howto-contribute.txt, README, configure.ac, man-common/translation.adoc, util-linux.doap
Some browsers already force https use, fix links
for sites that can be easily redirected.
Signed-off-by: Milan Broz <gmazyland@gmail.com>
=> Use https for project-related documentation.

libblkid/src/Makemodule.am, libblkid/src/fuzz.c, tests/commands.sh, tests/ts/fuzzers/test_blkid_fuzz, tools/oss-fuzz.sh
* Added new fuzz target calling blkid_do_safeprobe(), mainly based off of how libblkid is used in the cryptsetup project (same flags used etc.)
* Added the fuzz target to the Makemodule and all relevant scripts.
* Made as part of my upcoming bachelor thesis.
Signed-off-by: David Flor <493294@muni.cz>
=> libblkid: new fuzz target

bash-completion/rfkill
Add toggle to the bash completion script with the same behaviour as list, block and unblock.
Signed-off-by: Daniel Peukert <daniel@peukert.cc>
=> rfkill: add toggle to bash completion

tests/ts/mount/fstab-btrfs
Fixes mount/fstab test failure on btrfs filesystem, if kernel support for btrfs is missing
before:
```
... OK (all 2 sub-tests PASSED)
mount: btrfs (fstab)                  ...ERROR: not a btrfs filesystem: .
/1/mator/util-linux/tests/../tests/ts/mount/fstab-btrfs: line 61: cd: ./s1: No such file or directory
ERROR: not a btrfs filesystem: .
ERROR: cannot access 's2': No such file or directory
ERROR: Not a Btrfs filesystem: Invalid argument
ERROR: not a btrfs filesystem: /1/mator/util-linux/tests/output/mount/fstab-btrfs-mnt-create
ERROR: can't access '/1/mator/util-linux/tests/output/mount/fstab-btrfs-mnt-create'
ERROR: not a btrfs filesystem: .
umount: /1/mator/util-linux/tests/output/mount/fstab-btrfs-mnt-create: not mounted.
: btrfs                       ... FAILED …
```
=> [tests] skip mount btrfs if kernel support for filesystem is missing

libblkid/src/superblocks/bitlocker.c, libblkid/src/superblocks/f2fs.c
Note: There are no testfiles for bitlocker.
=> libblkid: fix unaligned accesses

tools/oss-fuzz.sh
to somewhat cover architectures where unaligned access can lead to crashes and make it possible for OSS-Fuzz to catch issues like https://github.com/util-linux/util-linux/pull/1906.
With this patch applied the libblkid fuzz target built with the OSS-Fuzz toolchain triggers "runtime error: load of misaligned address" in `probe_exfat` so it seems to be working.
=> oss-fuzz: turn on the alignment check explicitly

sys-utils/irq-common.c
When sorting irqs by delta, sort first by delta, then by name. This helps interrupts occuring at the same rate reach a more stable display ordering.
Signed-off-by: Richard Allen <rsaxvc@gmail.com>
=> irqtop: improve delta-sort stability

libblkid/src/superblocks/erofs.c
Erofs on-disk superblock struct should be marked as packed to avoid default struct members alignment.
Fix OSS-Fuzz issue 53615
=> libblkid: fix misaligned-address in probe_erofs

libblkid/src/superblocks/exfat.c
Value checked in le32_to_cpu() needs to be properly aligned. Just copy the value temporarily for conversion.
Fix OSS-Fuzz issue 53696
=> libblkid: fix misaligned-address in probe_exfat

tests/Makemodule.am
This helps investigating issues, especially spurious errors only happening during CI like the failure of "hardlink/options-maximum-size-8192"
=> autotools: show test failure diff

include/shells.h, lib/shells.c, login-utils/Makemodule.am, login-utils/chsh.c, login-utils/su-common.c
This PR solves the issue defined in:
https://github.com/util-linux/util-linux/issues/1857
=> Supporting vendor given "shells" configuration file

tests/functions.sh, tests/ts/minix/fsck
Tests fail when the build directory contains 
'@' in its path, as its sent to 'sed' unescaped.
This patch allows to build in such environments,
which typically happen on automated systems (for
example, when building concurrently with Jenkins).
=> tests: allow paths in tests to contain '@' char

meson.build
Also drop a few unnecessary mentions of logindefs.c
=> meson: use shells.c where needed

sys-utils/lsns.8.adoc, sys-utils/lsns.c, tests/ts/lsns/ioctl_ns
This skips the tests on setups were the nsfs ioctls are not functional.
(Old kernels, 32bit userland on 64 bit kernel, see #1924)
=> lsns: report unsupported ioctl

.packit.yaml
Let's run at least the unit-tests on Fedora Rawhide via Packit, as it supports a couple of alternative architectures (aarch64, ppc64le, s390x) as well as i*86, which were source of issues in the past.
=> ci: build & test util-linux on Fedora Rawhide via Packit

misc-utils/rename.1.adoc
Document the behaviour of an empty `expression` argument, and of `/` in the `expression` and `replacement` arguments.
I also tried to make it slightly clearer that `-s` changes where a symlink points, but doesn't change the thing that it points at.
Discussed this briefly in #1741 but I only just got around to looking into it.
=> rename.1: document edge cases.

sys-utils/hwclock.c
hwclock should return 0 on sucessful --param-get.
Fixes: 6097b12df ("hwclock: add --param-get option")
Fixes: #1570
=> hwclock: fix return value on successful --param-get

include/pathnames.h, include/sysfs.h, lib/sysfs.c, meson.build, sys-utils/Makemodule.am, sys-utils/setarch.c
Kernel implementation: https://lore.kernel.org/lkml/20221221-address-bits-v1-1-8446b13244ac@weissschuh.net/
=> sysfs: read address bits from sysfs file

AUTHORS, libblkid/src/superblocks/lvm.c, misc-utils/lsblk-properties.c, misc-utils/lsblk.8.adoc, misc-utils/lsblk.c, misc-utils/lsblk.h
- ID_REVISION in udev supports more device types like NVMEs.
- add this to --nvme output list as in --scsi output.
There is still fallback to old sysfs device/rev read, so for non-udev systems it should do the same.
And update my email (drop this patch if it is not posssible :-)
=> lsblk: read firmware revision from udev and use it for --nvme output

tests/ts/lsns/ioctl_ns
The check introduced in 249ba69c introduced a proper feature check.
This reverts commit 857038d4512a5f2e9a1fd4a3d89c2c27eae456fd.
=> Revert "tests: use KNOWN_FAIL for lsns/ioctl_ns"

libblkid/src/partitions/bsd.c, libblkid/src/partitions/gpt.c, libblkid/src/partitions/sgi.c, libblkid/src/partitions/sun.c
This enables unified reporting and configuration.
In addition it provides checksum bypass for the fuzzers, so this code will be fuzzed properly.
It also includes new checksum handling for BSD partition tables.
=> libblkid: partitions: use generic checksum handling

meson_options.txt
This is a boolean, not a string.
Found with muon analyze.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
=> meson: fix option value

libblkid/src/cache.c, libblkid/src/evaluate.c, libblkid/src/init.c, libblkid/src/probe.c
Otherwise sometimes we have no debugging. For example in `lsblk`.
=> libblk: unify debug initialization

misc-utils/rename.1.adoc, misc-utils/rename.c, tests/expected/rename/subdir, tests/ts/rename/subdir
That is, it only updates the final path component, unless either the expression or the replacement contains a '/'.
As discussed in #1962.
=> `rename -s` treats paths the same as without `-s`.

.github/workflows/cibuild.yml
gcc 10 has false positives around null strings:
In file included from /usr/include/stdio.h:894,
from lib/strutils.c:8:
In function ‘printf’,
inlined from ‘test_strutils_cstrcasecmp’ at lib/strutils.c:1324:2,
inlined from ‘main’ at lib/strutils.c:1348:10:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:112:10: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
112 |   return __printf_chk (__USE_FORTIFY_LEVEL - 1, __fmt, __va_arg_pack ());
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
=> WIP: CI: update gcc to 12

lib/strutils.c
In file included from /usr/include/stdio.h:894,
from lib/strutils.c:8:
In function ‘printf’,
inlined from ‘test_strutils_cstrcasecmp’ at lib/strutils.c:1324:2,
inlined from ‘main’ at lib/strutils.c:1348:10:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:112:10: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
112 |   return __printf_chk (__USE_FORTIFY_LEVEL - 1, __fmt, __va_arg_pack ());
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
=> lib/strutils: fix compiler error

Makefile.am, meson.build, tools/asciidoctor-includetracker.rb
This will rerun the manpage generation if any of the involved files have been updated.
=> build: track dependencies of manpage generation

schedutils/taskset.1.adoc
Provide some minor improvements to the existing taskset man page, namely:
-- Illustrate the ability to specify cpumasks without a leading "0x" with an example that is clearly hexadecimal.
-- Clarify that a successful return code from the command does not mean that a process has actually migrated.
-- Provide a couple of examples to further explain the significance of the taskset return code.
=> schedutils: clarify the usage and behavior of the taskset command

login-utils/login.c
If the signal handler is triggered after a failed fork attempt, then child_pid will be -1. This in turn leads to a positive test and a subsequent call of kill(1, signal). If signal was SIGTERM, then there will be also another kill(1, SIGHUP) call.
Test explicitly for a positive child_pid value to prevent these cases.
Signed-off-by: Samanta Navarro <ferivoz@riseup.net>
=> login: never send signals to init

include/c.h
The previous implementation relied on signed-integer overflow. This is undefined behavior.
Instead use an implementation that only requires twos-complement representation. This is what everybody uses anyways and it will be required by C23.
=> c.h: avoid undefined behavior in SINT_MAX macro

disk-utils/mkswap.c
If blkdev_get_size fails, then size is not set. Exit with an error code and indicate what went wrong instead of continuing with random stack content.
Proof of Concept:
```
$ mkswap /dev/null
mkswap: warning: truncating swap area to 17179869180 KiB
mkswap: /dev/null: insecure permissions 0666, fix with: chmod 0600 /dev/null
mkswap: unable to assign device to libblkid probe
```
The first output line depends on stack content and sometimes does not show up at all. Abort operation if argument is neither regular file nor block device.
Signed-off-by: Samanta Navarro <ferivoz@riseup.net>
=> mkswap: do not use uninitialized stack value

lib/blkdev.c
The code in blkdev_get_size should have a better error handling:
- the read system call might be interrupted by a signal. I don't think that it's a good idea to report a smaller disk size back to the application compared to giving an error return value
- an error return value should always set errno, because applications within util-linux evaluate errno for error messages
- last but not least: off_t is signed and the code should try to support block devices as large as possible by considering INTMAX_MAX instead of UINTMAX_MAX. I lack such a block device though for a proof of concept :)
=> lib/blkdev: better error handling

libblkid/src/superblocks/befs.c
BEFS does not check maximal value for ag_shift leading to undefined behavior. Avoid this by limiting shift size.
Reproducer found with OSS-Fuzz (issue 55285) running over cryptsetup project (blkid is used in header init).
Signed-off-by: Milan Broz <gmazyland@gmail.com>
=> libblkid: befs - avoid undefined shift

.github/workflows/differential-shellcheck.yml, .shellcheckrc, lib/timeutils.c, tests/commands.sh, tests/ts/lib/timeutils
Edit: also contains some changes for the shellcheck lint.
=> lib/timeutils: parse_timestamp: bugfix, unittests and usec support

sys-utils/lscpu-arm.c
ID 002 for the Exynos-m3 core seems weird since Exynos-m1 had 001 but Samsung's Mongoose line differs only by stepping between M1 and M2 
* Mongoose 1, for example [Exynos 8890](https://github.com/ThomasKaiser/sbc-bench/blob/master/results/Exynos-8890-highperformance.cpuinfo): Exynos-m1 / r1p1
* Mongoose 2, for example [Exynos 8895](https://github.com/ThomasKaiser/sbc-bench/blob/master/results/Exynos-8895.cpuinfo): Exynos-m1 / r4p0
* Mongoose 3, for example [Exynos 9810](https://github.com/ThomasKaiser/sbc-bench/blob/master/results/Exynos-9810.cpuinfo): Exynos-m3 / r1p0
=> Add missing ARM cores

disk-utils/fsck.c, lib/pager.c, login-utils/last.c, login-utils/su-common.c, login-utils/sulogin.c, misc-utils/hardlink.c, sys-utils/flock.c, term-utils/write.c, text-utils/pg.c
Generally
- It is only warranted that writting to an static volatile sig_atomic_t works.
- You cannot use any function outside the signal-safety 7 list 
-  Most importantly if you call anything that ends calling stdio or malloc..kaboom..
=> fix some Signal safety issues

libblkid/src/superblocks/bcache.c
=> libblkid: bcachefs: avoid overflow in member size validation and drop redundant checks

libblkid/src/Makemodule.am, libblkid/src/fuzz.c, meson.build
This can be used to easily reproduce crashes produced by the fuzzers.
=> libblkid: add test_blkid_fuzz_sample

disk-utils/fsck.cramfs.c
The error message for a failing chmod call contains chown as reason. Fix this by stating that chmod failed.
Signed-off-by: Samanta Navarro <ferivoz@riseup.net>
=> fsck.cramfs: fix error message

schedutils/chrt.1.adoc
I've come looking at this manpage with the simple "how do I make this process use realtime scheduling?" question and couldn't find a definite answer. Of course, RT is more complicated than "just make this real time": there's various queues and scheduling classes, but I think it's worth giving a good, simple example that should basically work.
In particular, my use case was "my audio is stuttering, is this a scheduling problem?" By picking the RR scheduler, we set a realtime scheduling priority that's lower than kernel threads (e.g. migration is FF/99, irq is FF/50) so that we go above existing processes, but without kicking out more critical systems.
This, of course, is a matter of taste, and the settings here are a little arbitrary. I send this patch in the hope that either those are …
=> add more concrete examples of how to use chrt(1)

misc-utils/lsfd-sock-xinfo.c, tests/expected/lsfd/mkfds-unix-stream, tests/ts/lsfd/mkfds-unix-stream
The original code uses '%s' scanf specifier to read lines in /proc/net/unix.
If white space is included in a path, lsfd could read only the first word of the path.
This pull request fixes the bug.
=> lsfd:  read the UNIX socket path including white spaces correctly

configure.ac, libblkid/src/blkidP.h, libblkid/src/probe.c, libblkid/src/superblocks/superblocks.c, meson.build
If a device is locked with OPAL we'll get an I/O error when probing past the LUKS2 header. Try it first to avoid this issue.
Signed-off-by: Luca Boccassi <bluca@debian.org>
=> libblkid: try LUKS2 first when probing

libmount/src/context_mount.c, sys-utils/mount.8.adoc
Add a special value for rootcontext=, namely `@target`, to set the root
context of the new filesystem to the current context of the target
mountpoint.  Useful for in-memory filesystems, like tmpfs and ramfs.
Closes: #1830
=> mount: add rootcontext=@target

tests/expected/hardlink/options-maximum-size-8191, tests/expected/hardlink/options-maximum-size-8192, tests/ts/hardlink/options
Depending on external circumstances the exact amount of compared files can vary.
So don't test for this statistics as otherwise spurious test failures will occurr.
=> hardlink: (tests) do not assert amount of compared files

libmount/src/hook_idmap.c
The current code writes to sock_fds[0], which is set to -1 on line 227, instead of the correct sock_fds[1]. As a cause, a simple `mount` command which uses idmapping and doesn't specify a user ns hangs indefinitely.
=> libmount: idmap: fix sock write to child

sys-utils/wdctl.c
Note: This is pending kernel support in https://lore.kernel.org/lkml/20221125222315.4925-1-linux@weissschuh.net/
=> wdctl: read firmware_version from sysfs

bash-completion/nsenter, include/all-io.h, include/env.h, lib/env.c, sys-utils/nsenter.1.adoc, sys-utils/nsenter.c
This commit adds support for the -e or --env option in nsenter, allowing a new process to inherit the environment variables from the target process.
If the option is not given, the environment variables will stay the same as in the current namespace.
Example:
Setup the namespace:
$ docker run -d -e PROJECT='util linux' --rm alpine sleep 10000
cb0b69aa7aec
$ docker inspect --format '{{ .State.Pid }}' cb0b69aa7aec
470012
Enter the namespace:
$ nsenter --all -t 470012 --env env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=cb0b69aa7aec
PROJECT=util linux
HOME=/root
=> nsenter: add --env for allowing environment variables inheritance

configure.ac
=> build-sys: work around broken cross-compiles on Debian
