tests/helpers/test_md5.c
tests/helpers/test_sha1.c

The standard streams must not be closed unless it is the very last thing a program does before termination.
A warning about this was added to POSIX.1-2008 and later standards.
One must redirect stdin to /dev/null using freopen instead.

tests: fclose(stdin) UB

---

libmount/src/hook_idmap.c

This fixes the second issues reported in [1] where calling mount -o 'X-mount.idmap=[...]' just hangs.
Fixes: https://github.com/util-linux/util-linux/issues/2130 [1]

idmap: kill child when writing the idmap fails

---

text-utils/hexdump-parse.c

If the fmt being parsed by block_size is exactly '%', *++fmt is the terminator and strchr will return a valid pointer to the terminator of spec rather than NULL, the while condition will pass and subsequent strchr will read past the end of fmt until a spec character is found again
ASAN aborts with the following error on the first buffer overread:
```
AddressSanitizer: heap-buffer-overflow on address 0x602000000212 at pc 0x55bf1c4b2d78 bp 0x7ffe33c8cff0 sp 0x7ffe33c8cfe0 READ of size 1 at 0x602000000212 thread T0
#0 0x55bf1c4b2d77 in block_size ../text-utils/hexdump-parse.c:207
#1 0x55bf1c4ad36f in main ../text-utils/hexdump.c:214
#2 0x7f15f063c78f  (/usr/lib/libc.so.6+0x2378f)
#3 0x7f15f063c849 in __libc_start_main (/usr/lib/libc.so.6+0x23849)
#4 0x55bf1c4ac6c4 in _start …
```

hexdump-parse: handle truncated format pattern

---

bash-completion/nsenter
sys-utils/nsenter.1.adoc
sys-utils/nsenter.c

Making the argument to -S and -G optional in #2092 broke the cli compatability.
So replace it with an explicit "follow" argument that provides the new functionality with a compatible interface.
Fixes #2143

nsenter: use explicit argument to follow target PID/GID

---

include/crc32c.h
lib/crc32c.c
libblkid/src/superblocks/xfs.c

The Linux kernel computes the sb_crc by crcing the superblock with the CRC field set to 0. The code is trying to avoid doing this in three separate CRC calls like the kernel performs by simply zeroing the field and making a single call.
Except that the passed copy "ondisk" isn't the same as the returned copy "csummed" so the zeroing goes into the wrong buffer. Meaning that the CRC is computed incorrectly. This results in blkid returning:
/dev/sda4: PARTUUID="2f162043-63c2-d145-869b-e53f9db57476"
rather than:
/dev/sda4: UUID="45b931b7-592a-46dc-9c33-d38d5901ec29" BLOCK_SIZE="4096" TYPE="xfs" PARTUUID="2f162043-63c2-d145-869b-e53f9db57476"
Which can result in lots of failures including boot failures if XFS modules aren't placed into the initrd, or scripts/etc cannot determine the fs UUID.

libblkid: Compute CRC with sb_crc zeroed

---

misc-utils/fadvise.1.adoc
misc-utils/fadvise.c

Some of them were split out from #2169 because that PR seems to take longer to fix the tests everywhere.
So these fixes can go into the next 2.39 RC faster.
Cc @masatake

fadvise: fixes

---

libmount/src/utils.c
tests/ts/mount/fstab-all

By using AT_CWFD the call to statx() can also handle relative filenames. Without this safe_stat() which is called on the fstab, source, target...

libmount: safe_stat: support relative filenames

---

libmount/src/context_mount.c

fix_optstr() in context_mount.c calls the MNT_STAGE_PREP_OPTIONS hooks but discards returned errors. This suppresses error messages and can make invalid option strings 'fail open' in surprising ways. Handle error returns from these hooks correctly.
No other callers of mnt_context_call_hooks() discard the return value, so other hooks aren't affected.

libmount: check for errors from prep-options hooks

---

meson.build
tests/commands.sh
tests/helpers/Makemodule.am
tests/helpers/test_enosys.c
tests/ts/mount/fallback

It seems the fallback for move_mount does not work at the moment.

libmount: validate ENOSYS fallback

---

tests/ts/mount/fstab-bind

The necessary functionality is not implemented there.

mount: (tests) skip fstab-bind on qemu-user

---

login-utils/su-common.c

Added return statement to ensure that all execution paths end with a return statement.
Fix for #2190

add return in supam_conv function

---

.github/workflows/cibuild.yml
libmount/src/mountP.h
tests/functions.sh
tests/helpers/test_sysinfo.c
tests/ts/lsns/nsfs
tests/ts/mount/fstab-bind
tests/ts/mount/fstab-broken
tests/ts/mount/fstab-btrfs
tests/ts/mount/fstab-none
tests/ts/mount/move
tests/ts/mount/subdir

Since commit e828630a16c7 ("libmount: recover from ENOSYS for the new API") these work correctly.
Note: please wait for the CI to finish, as I don't really know that this works now.

mount: (tests) run bind mount tests on qemu-user

---

tests/helpers/test_sysinfo.c

When fsopen() is not provided by mount-api-utils.h it comes from sys/mount.h.

tests: (test_sysinfo) include sys/mount.h

---

.github/workflows/cibuild-setup-ubuntu.sh
.github/workflows/cibuild.yml
po-man/.gitignore
po-man/Makefile.am
tools/asciidoctor-unicodeconverter.rb

Currently po4a is asciidoctor is rejecting quite a few translated manpages:
```
asciidoctor: ERROR: cal.1.adoc: line 28: non-conforming name section body
```
The problem is that asciidoctor expects a dash between the command and its short description:
```
== НАЗИВ
cal приказује календар
^ should have " - " here
```
It seems to affect most of the `sr` locale and some other pages.
We could probably also extend `tools/asciidoctor-unicodeconverter.rb`, which already preprocesses this part of the translated pages.
This is maybe something that needs to be fixed for next release or the translators may be unhappy.
(And the packagers, as it fails the build)

ci: build translated manpages during test

---

login-utils/sulogin.c

The service invoking sulogin might already have set TERM to something useful so if that's the case let's not overwrite it.
Fixes #2221

sulogin: Don't overwrite TERM if already set

---

lib/pager.c

Commit 518a0ad dropped `fflush(stdout)` and `fflush(stderr)` from `wait_for_pager()` before `STDOUT_FILENO` and `STDERR_FILENO` are closed because it is called from a signal handler and they are async-unsafe.
However, failure to flush output leads to unwanted truncation when stdout is fully buffered, which it is by default when we are linked against musl.
Ensure stdout and stderr are line-buffered before redirecting them to the pager subprocess to avoid this.
Addresses: https://github.com/util-linux/util-linux/issues/2218
Signed-off-by: Chris Webb <chris@arachsys.com>

lib/pager: fix output truncation from buffered stdout

---

tests/functions.sh

I'm forwarding this patch from the Debian project. Original reference: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1007139
Original bug report:
> while investiating some things, I fonud that util-linux still uses the
> chown user.group notation that has been deprecated for quite a  while
> now. The occurrencies that i found are both in tests/functions.sh.

Use non-deprecated chown syntax

---

libmount/src/context_mount.c

This affects already translated messages, so for v2.40

libmount: report failed syscall name

---

misc-utils/enosys.c

Otherwise there is no guarantee that all syscall numbers detected by tools/all_syscalls are actually available to enosys.c.
This should also be applied to 2.39

enosys: include sys/syscall.h

---

tests/ts/lsfd/option-inet

Reported-by: Bruce Dubbs <bruce.dubbs@gmail.com>
ref. https://marc.info/?l=linux-kernel&m=168445262924692&w=2

lsfd: (tests) fix process leak

---

libmount/src/optmap.c
tests/expected/mount/special
tests/ts/mount/special

"defaults" is only a pseudo-option that expands to other options. It should not be passed to helpers.
Reported-by: Quentin Rameau <quinq@fifth.space>
Closes: https://lore.kernel.org/util-linux/20230521181814.0b0f2d38.quinq@fifth.space/
This should also be applied to 2.39

libmount: don't pass option "defaults" to helper

---

lib/shells.c

You can see the memory leak with address sanitizer if util-linux is compiled with `--with-vendordir=/usr/etc`.
How to reproduce:
1. Prepare a custom shell file as root
```
mkdir -p /etc/shells.d
echo /bin/myshell > /etc/shells.d/custom
```
2. Run chsh as regular user
```
chsh
```

lib/shells: Plug econf memory leak

---

configure.ac

The new pidfd stuff waitpid uses is not compatible with older kernel headers, but the rest of the util-linux is still perfectly fine, so allow disabling just the waitpid utility to make the builds happy again.

build-sys: add --disable-waitpid

---

misc-utils/enosys.c

enosys is not a security tool so we can allow the CPU to speculate.

enosys: allow CPU speculation

---

sys-utils/mount.8.adoc
sys-utils/mount.c

Allow an X-mount.idmap option to be specified either from an existing
userns with --map-users=/proc/PID/ns/user or incrementally with a series
of --map-users=INNER:OUTER:COUNT and --map-groups=INNER:OUTER:COUNT
options which compose into a single X-mount.idmap mount option.
Apart from distinguishing absolute namespace paths from literal mappings,
defer validation to libmount when it parses X-mount.idmap.

mount: add --map-users and --map-groups convenience options

---

login-utils/login.1.adoc
login-utils/login.c
term-utils/agetty.8.adoc
term-utils/agetty.c

Let's check if we've been passed credentials by systemd and if so, try to read the user to autologin from the agetty.autologin credential.
Partially fixes #2012

agetty: Load autologin user from agetty.autologin credential

---

libmount/src/hook_mount.c
tests/expected/mount/fallback-mount_setattr
tests/ts/mount/fallback

If mount_setattr is not available but needed fall back to the legacy mount API.
Fixes #2247
This should also be applied to 2.39 with the following changes:
* Use `$TS_HELPER_ENOSYS` in testcase
* Add `__NR_move_mount` to `test_enosys`

libmount: check for availability of mount_setattr

---

term-utils/agetty.c

It is needed to access xreaddir()

agetty: include fileutils.h

---

misc-utils/lsfd-file.c
misc-utils/lsfd-sock-xinfo.c
misc-utils/lsfd.c
misc-utils/lsfd.h
tests/expected/lsfd/column-source-namespace-ASSOC
tests/expected/lsfd/column-source-with-root-SysVIPC-shmem
tests/helpers/test_mkfds.c
tests/ts/lsfd/column-source
tests/ts/lsfd/column-source-with-root

An example output:
```
COMMAND        PID USER  ASSOC MODE TYPE SOURCE MNTID      INODE NAME
test_mkfds 3428907  jet cgroup  ---  REG   nsfs     0 4026531835 cgroup:[4026531835]
test_mkfds 3428907  jet    ipc  ---  REG   nsfs     0 4026531839 ipc:[4026531839]
test_mkfds 3428907  jet    mnt  ---  REG   nsfs     0 4026531841 mnt:[4026531841]
test_mkfds 3428907  jet    net  ---  REG   nsfs     0 4026531840 net:[4026531840]
test_mkfds 3428907  jet    pid  ---  REG   nsfs     0 4026531836 pid:[4026531836]
test_mkfds 3428907  jet  pid4c  ---  REG   nsfs     0 4026531836 pid:[4026531836]
test_mkfds 3428907  jet   time  ---  REG   nsfs     0 4026531834 time:[4026531834]
test_mkfds 3428907  jet time4c  ---  REG   nsfs     0 4026531834 time:[4026531834]
test_mkfds 3428907  jet   user  ---  REG …
```

lsfd: fill SOURCE column for sysvipc shmem mappings and nsfs files

---

sys-utils/dmesg.c

In Linux 6.3.4, with a kernel build with a relatively long kernel command-line, `dmesg` fails to print the `Kernel command line: ...` line and all subsequent lines of kernel logs. `strace dmesg` shows `read(3, 0xaaaae0150090, 1023)           = -1 EINVAL (Invalid argument)` at this point: passing a 1kB buffer is not sufficient to hold the line (using `strace cat /dev/kmsg` instead shows this `read()` call to read 1031B).
It seems dmesg hard-codes whatever the libc defines as `BUFSIZ`, but it should use a value that matches the kernel's idea of how large a kernel log message can be. I believe `PRINTK_MESSAGE_MAX` is the appropriate limit: per [this message](https://lore.kernel.org/lkml/20230105103735.880956-9-john.ogness@linutronix.de/):
> PRINTK_MESSAGE_MAX:
> 
> This is the maximum size …

Increase buffer size for read() of /dev/kmsg to match PRINTK_MESSAGE_MAX

---

tests/functions.sh
tests/ts/misc/enosys
tests/ts/mount/fallback

Fixes #2277
The same for 2.39:
https://github.com/t-8ch/util-linux/commit/c80840e3a4938a4d599ed0e84d673794e048d0b3

test_enosys: fix build on old kernels

---

tests/functions.sh

Previously these tests would silently fail to compare $TS_OUTPUT / $TS_ERRLOG.

tests: fix subtests containing spaces in their name

---

libmount/src/hook_mount.c
sys-utils/mount.8.adoc

Let's introduce a stable workaround for use cases where new kernel API is not ready to use.
The patch does not use "goto enosys" to exit as nothing in the hookset is initialized yet.
Addresses: https://github.com/util-linux/util-linux/issues/1992
Addresses: https://github.com/util-linux/util-linux/issues/2283

libmount: introduce LIBMOUNT_FORCE_MOUNT2={always,never,auto}

---

.github/workflows/cibuild.yml

Newer releases of GCC 13 have reigned in the false positives, so use it for CI now.

ci: build with GCC 13 / clang 16

---

meson.build

... which is required for `cal`.
Fixes GH-2316

meson: check for _NL_TIME_WEEK_1STDAY in langinfo.h

---

.github/workflows/cibuild.yml
.github/workflows/cifuzz.yml

Let's cancel already running GH Actions jobs when a PR is (force) pushed to conserve resources and make the CI runs faster thanks to the freed up queue.

ci: cancel running jobs on push

---

tests/run.sh

This makes it easier to run test.sh from the build directory as everything will work without any parameters irrespective of the build directories name.

tests: (run.sh) detect builddir from working directory

---

bash-completion/nsenter
sys-utils/nsenter.1.adoc
sys-utils/nsenter.c

The issue is that some times the user namespaces can become unbound to any process. (for example bubblewrap) This will make the namespace unaccessible without using special ioctl.
Closes: #1592
When this option is used nsenter will fetch the parent user
namespace from any namespace file descriptors available.
It can be combined with existing `--user` option in which case
the parent user namespace will be fetched from the user namespace
and replace it.
How to test:
1. Use bwrap with `--dev` option: `bwrap --dev /test --dev-bind / / /bin/sh`
2. Using regular `nsenter` does not work: `nsenter --preserve-credentials --user --mount --target $PID bash`
3. Using new option will work: `./build/nsenter --preserve-credentials --user-parent --mount --target $PID bash`

Add `--user-parent` option to nsenter

---

include/bitops.h

This is no longer needed on supported versions of FreeBSD and causes build failures

include/bitops.h: Remove bswap* compatibility hack for FreeBSD

---

libmount/src/hook_mount.c

Similar to e80f8e46127e45907db25b4ffd58c699fdf4c35f and fallout from 6753e6f6912658e836966a6316df956e1af5fcae

libmount: fix typo

---

libmount/src/libmount.h.in

The implementation using the new FD based mount kernel API (ie., fsconfig/fsopen) uses MNT_ERR_APPLYFLAGS for failed mount_setattr(2) calls, which involves more mount attributes (eg., MOUNT_ATTR_RDONLY, MOUNT_ATTR_NOSUID, etc.) in addition to the MS_PROPAGATION flags (eg., MS_SHARED, MS_UNBINDABLE, etc.).
Note that mount_setattr(2) is part of the new FD based mount kernel API, and is not used by the classic mount(2) based version.
Fallout from 987d844cdbc0f91ca81de3c1e5d0628a60eb458f

libmount: update documentation for MNT_ERR_APPLYFLAGS

---

sys-utils/prlimit.c

Before:
```console
$ prlimit --verbose --core=1x
New CORE limit for pid 42: <1:1>
```
After:
```console
$ prlimit --verbose --core=1x
prlimit: failed to parse CORE limit
```

prlimit: reject trailing junk in limits without ":"

---

bash-completion/lsclocks
include/timeutils.h
lib/timeutils.c
misc-utils/lsclocks.1.adoc
misc-utils/lsclocks.c
tests/ts/lib/timeutils

This also incorporates feedback from #2343 :
* Shorter default columns
* Human readable resolution

lsclocks: implement REL_TIME column

---

bash-completion/nsenter
include/pathnames.h
sys-utils/nsenter.1.adoc
sys-utils/nsenter.c

This commit adds support for the -c or --join-cgroup option in nsenter, allowing a new process to join the cgroup of target process.
```
Example:
Setup the target process:
$ podman run --rm -d docker.io/golang sleep 10000
51a89deb6baf6d
$ podman inspect --format '{{ .State.Pid }}' 51a89deb6baf6d6
216054
Enter the cgroup namespace of target process without option -c:
$ sudo ./nsenter -C -U -t 216054 sh -c "cat /proc/self/cgroup"
0::/../../../../session-899.scope
Enter the cgroup namespace of target process with option -c:
$ sudo ./nsenter -c -C -U -t 216054 sh -c "cat /proc/self/cgroup"
0::/
```

nsenter: add option `-c` to join the cgroup of target process

---

configure.ac
libmount/python/meson.build
m4/ax_compare_version.m4

Python 3.12 introduced a -Wredundant-decls warning. Work around it by not breaking the build.
See https://github.com/python/cpython/issues/106560
Closes: #2366

RFC: libmount: (python): work around python 3.12 bug

---

.github/workflows/codeql.yml

This rule fires for file operations on user-specified paths. As this behavior is the very core of many util-linux utilities it is a false positive.
Note: I'm not completely sure if this is the correct syntax. The docs are fairly ambivalent...

ci: disable cpp/path-injection rule

---

misc-utils/fincore.c

Device files do not give file size with st.st_size field, they return 0. Instead there's an ioctl to obtain device file size, BLKGETSIZE64. Use it.

Fincore: Support device files.

---

misc-utils/lsfd-bdev.c
misc-utils/lsfd-cdev.c
misc-utils/lsfd-fifo.c
misc-utils/lsfd-file.c
misc-utils/lsfd-sock-xinfo.c
misc-utils/lsfd-sock.c
misc-utils/lsfd-sock.h
misc-utils/lsfd-unkn.c
misc-utils/lsfd.c
misc-utils/lsfd.h
tests/expected/lsfd/mkfds-unix-stream
tests/ts/lsfd/mkfds-unix-stream

/proc/net/unix provides unix socket information in line oriented way.
The line oriented way can be a trouble because a unix socket path can have a newline char.
See https://github.com/util-linux/util-linux/pull/2067.
With this pull request, lsfd utilizes the sockdiag netlink interface
for getting the paths. The interface provides strings of paths as is.
The main commit (ed450a0ed1861234e0bc514d57498f6d5b0e4bc4) is mostly based on Thomas Weißschuh's work,
https://github.com/t-8ch/util-linux/commit/06030390a5e6a16cc4b914bbf5fcedd3b6d83608.
Unlike the original work, this commit keeps /proc related code.
Unlike /proc interface, the sockdiag information source doesn't provide
enough information for filling struct unix_xinfo::st member. So this
commit uses /proc interface to fill most …

lsfd: use sockdiag netlink interface for handling a newline in a unix socket path

---

tests/ts/fincore/count

The fincore tests call ts_log_both inside an output redirection of both stdout and stderr, leading to the ts_log_both output ending up twice in both stdout and stderr.
Call ts_log_both before setting up the output redirection.
Debian patch (for 2.39.1) https://salsa.debian.org/debian/util-linux/-/blob/master/debian/patches/fincore-tests-fix-double-log-output.patch

fincore: (tests) fix double log output

---

tests/ts/lsfd/option-inet

Close #2399.
The original code assumes the background processes prepare sockets enough fast. #2399 showed the assumption was wrong; lsfd reported half-cooked sockets.
To avoid the timing issue, the test case with this change uses a fifo to receive pids from the child test_mkfds processes. test_mkfds reports its pid after cooking the sockets. When the option-inet script recives the pid, we can expect the sockets are ready.
Note: bash's coproc cannot be used here; it supports only one co-process at once.
Analysed-by: Alexander Kanavin <alex.kanavin@gmail.com>

tests: (lsfd::option-inet) get child-processes' pids via fifo

---

libmount/src/context_mount.c
libmount/src/hook_mount.c
libmount/src/hook_mount_legacy.c
libmount/src/hooks.c
sys-utils/mount.8.adoc

It was originally designed to play nasty games with /etc/mtab (mount when /etc is read-only and update later when it's write-able).
The --fake is completely useless with the new API due to complexity where we cannot skip any step, because the next stuff depends on it. So, it makes more sense skip all functionality where libmount does anything significant.
This commit add --fake check to hooks logic to skip all hooks as the hooks are place where libmount implements mount related invasive operations (create mountpoint, namespaces, create superblock, move, mount, etc.).
Frankly, --fake without mtab is useless.
Fixes: https://github.com/util-linux/util-linux/issues/2395

libmount: cleanup --fake mode

---

misc-utils/lsfd-sock-xinfo.c
tests/expected/lsfd/mkfds-unix-stream
tests/expected/lsfd/mkfds-unix-stream-requiring-sockdiag
tests/ts/lsfd/mkfds-unix-stream
tests/ts/lsfd/mkfds-unix-stream-requiring-sockdiag

Close #2402.
In the current implementation of lsfd, the communication code for retrieving unix socket information doesn't consider the byteorder.
NOTE: The second commit doesn't require the first.

tests: (lsfd) don't run the unix-stream testcase including newlines in the path on qemu-user

---

term-utils/ttymsg.c

Some wayland display managers (GDM) put strings like "seat0" in the ut_line field of utmp entries. These are not valid tty devices.
Avoid writing a confusing error message for ttys that do not exist.
Bug: https://bugs.gentoo.org/911336

wall: do not error for ttys that do not exist

---

libmount/src/utils.c

If the systemcall is not available ENOSYS is returned.
Under glibc the statx implementation also has its own fallback logic. As AT_STATX_DONT_SYNC can't be implemented correctly in that fallback logic the wrapper will return EINVAL in case the emulation is needed and AT_STATX_DONT_SYNC is set.
So also use our own fallback in that case.
Fixes: #2409

libmount: (utils) fix statx fallback

---

po/meson.build

Commit e91a49c9747f ("meson: don't build po if no gettext") tried to add the possibility to build util-linux without gettext.
Unfortunately by default the call to find_program() would abort the build if the program is not found.
Avoid aborting the build.

meson: properly handle gettext non-existence

---

tests/expected/fincore/count.65536
tests/expected/fincore/count.nosize

For #2380 the testcases for 4k pages were adapted to the new output format, but the other testcases were missed.
CC @mator

fincore: (tests) adapt alternative testcases to new header format

---

libmount/src/hook_veritydev.c
sys-utils/mount.8.adoc

If the roothash is the same among two volumes, then the images are guaranteed
to be equivalent. The filename of the image on the other hand does not imply
that the images are equivalent.
In systemd we open verity devices as '<roothash>-verity', so that we know for
sure we can reuse them. Do the same here, so that we are a bit more confident
that images can be reused before the safety check, and also so that we can
take advantage of the kernel refcounting together with images used by systemd,
as setting up verity is expensive.

verity: use <roothash>-verity as the device mapper name instead of libmnt_<image>

---

libmount/meson.build
meson.build
meson_options.txt
tools/all_syscalls

using sh removes the bash dependencies, for those who don't have
bash on their system, and replaced the GNU awk with a portable
grep and sed.
as for the meson, I've done the same and used the beginner meson book. since all_syscalls utility will always right syscalls.h, theres no point to have it be an output and launched by bash, if meson has this feature already called `run_command`.

tools/all_syscalls & meson depends simplification, program-tests option

---

.github/workflows/cibuild-setup-ubuntu.sh

The original change (86d5c4dbf6e62c52fe9295f4e55eb629d8e26cfb) didn't consider "set -e" at the beginning of the script.

github: check apt-cache in more robust way (v2)

---

.github/workflows/cibuild-setup-ubuntu.sh
include/loopdev.h
lib/loopdev.c

The current code follows ro/rw mode not only set mode of the new device, but also to open the device node for ioctls.
Linux kernel does not care and it seems O_RDONLY is good enough for all cases (ioctls).
Unfortunately, udevd is sensitive as it monitors devices by inotify and IN_CLOSE_WRITE event is expected to apply udev rules for the device.
Changes:
* remove LOOPDEV_FL_{RDONLY,RDWR} private flags, it's too complex and unnecessary
* use mode_t for open() modes (rater than int)
* re-open only if O_RDWR requested otherwise default to O_RDONLY
* make sure O_RDWR is used on device setup
Fixes: https://github.com/util-linux/util-linux/issues/2434

losetup: cleanup device node modes

---

libblkid/src/probe.c

Many probers read data from disk bounded by some field from the probed disk itself.
The probers should validate the read length before using. Add a fallback that kicks in when the proper does not check the length epxlicitly.
See #2427

libblkid: limit read buffer size

---

configure.ac
meson.build
term-utils/Makemodule.am
term-utils/agetty.c
term-utils/wall.c
term-utils/write.c

Three out of four, lslogins.c will take longer as that is much more work.
sd_session_get_username() will only be available with systemd v254, but it builds and works with current git version of systemd already.

Y2038: query systemd-logind instead of utmp for username and tty (#2088)

---

bash-completion/enosys
misc-utils/enosys.1.adoc
misc-utils/enosys.c
tests/expected/misc/enosys-ioctl
tests/helpers/test_enosys.c
tests/ts/misc/enosys

Ioctls are blocked with ENOTTY.
This is still missing a mechanism to discover ioctls at build time.
At the moment only `FIOCLEX` is supported.

enosys: add support for ioctl blocking

---

login-utils/last.1.adoc
login-utils/last.c

Greetings,
This patch introduces a  -T  option to the  last  command. 
This  -T  option allows for tab-separated output, enhancing  awk  parsing without altering the default behavior. By introducing this option, we provide a more efficient solution while preserving the simplicity of the  last  command.
During the development of a diagnostic data aggregator for servers, the lack of reliable  awk  piping with  last  became evident, leading to a workaround of directly parsing the wtmp file.
Here are the changes in the commit below.
Signed-off-by: Cristian Zmole <chiarel@tragdate.ninja>

Add  -T (tab-separated) Option to  last  Command

---

libblkid/src/superblocks/bcache.c

The bcachefs probe has a maximum superblock size hardcoded to 4KiB. This is causing it to miss filesystems whose superblock has grown larger than 4KiB. The maximum potential size of the superblock is encoded at a fixed location within the superblock, so this value should be used instead.

libblkid: (bcachefs) fix not detecting large superblocks

---

libblkid/src/probe.c
libblkid/src/superblocks/jmicron_raid.c
libblkid/src/superblocks/vfat.c
libblkid/src/superblocks/zonefs.c

The cached buffers are shared between multiple probers.
To avoid (potentially security-sensitive) interdependencies between
probers make let the kernel enforce the write-protection.
Note:
I can imagine the fuzzers to find some more cases that we need to then fix.

libblkid: protect shared buffers against modifications

---

configure.ac
include/fileutils.h
libmount/src/hook_mount.c
libmount/src/utils.c
libmount/src/version.c
meson.build

Using sys/stat.h and linux/stat is too tricky.h together. It seems better to rely on libc and use sys/stat.h only. Users affected by old libc must update to use recent util-linux.
Fixes: https://github.com/util-linux/util-linux/issues/2448

libmount: fix statx() includes

---

misc-utils/waitpid.c
tests/ts/misc/waitpid

With this change, we can reduce the number of keystrokes, "2> /dev/null".

waitpid: warn of "exited" only when --verbose is given

---

sys-utils/lscpu-arm.c

The core with ID `0xd01` was wrongly named as the SoC it appeared in. `0xd02` is a newer variant of the TaiShan architecture used at least in Kirin 990A and 9000S and HiSilicon also has another custom core advertised as a Cortex-A77 variant.
In recently appeared Kirin 9000S `cpu4`-`cpu6` are yet unknown custom cores with ID `0xd42`, most probably an A78AE derivate that is SMT capable. But I'll try to get more insights first and send this in a separate PR later.

Revise/add HiSilicon core names

---

libblkid/src/blkidP.h
libblkid/src/partitions/partitions.c
libblkid/src/probe.c
libblkid/src/superblocks/superblocks.c
libblkid/src/topology/topology.c

When a new buffer is cached that is a superset of another existing
buffer the old buffer can be removed as future requests can be satisfied
by the new one.
As probe functions can have local references to buffered data, delay the
cleanup until the probefunc is finished to avoid accessing freed data.
For the bcachefs.img testfile this reduces the final (maximal) cache
from 34338 bytes in 54 buffers  to 24760 bytes in 40 buffers.

libblkid: prune unneeded buffers 

---

term-utils/scriptreplay.c

The old scriptreplay supported XON/XOFF flow control. The new implementation uses cfmakeraw() and it disables it by default. Let's enable it by IXON iflag.
Fixes: https://github.com/util-linux/util-linux/issues/2480
References: https://github.com/util-linux/util-linux/pull/1101

scriptreplay: support ctrl+s and ctrl+g

---

meson.build
tests/commands.sh
tests/functions.sh
tests/helpers/Makemodule.am
tests/helpers/test_cap.c
tests/ts/lsfd/mkfds-timerfd-alarm

The old capability testing logic would incorrectly interpret the following output from getpcaps as cap_wake_alarm being supported:
$ getpcaps 0
0: cap_wake_alarm=i
Instead of relying on brittle command output parsing at a test helper to detect capabilities.
Note: I also have an implementation that just fixes the shell parsing logic if that is better.
Cc @masatake

tests: fix capability testing

---

sys-utils/lscpu-cputype.c

BUFSIZ can vary quite a bit  e.g. glibc/linux systems its 8192 but on musl/linux and OSX its 1024, on mingW it is 256, some tests e.g. x86_64-64cpu-linux6.2.tar.gz has added really long line for cpu flags line which is greater than 1024 characters and hence this test fails on musl because lscpu -s reports truncated string

lscpu: Use larger buffer size for lscpu_read_cpuinfo

---

meson.build
misc-utils/Makemodule.am
misc-utils/lsfd-file.c
tests/ts/lsfd/mkfds-mqueue

Though lsfd reads device minor numbers for file-systems having "nodev"
from /proc/$pid/mountinfo, we observed lsfd failed to resolve the
values of SOURCE column for mqueue files on s390 CI/CD env. It seems
that /proc/$pid/mountinfo doesn't provide enough information.
This change makes lsfd open a mqueue file in lsfd's initialization
stage as a new data source for resolving; lsfd can collect an
actually-used minor number from the file descriptor with fstat(2).

lsfd: collect the device number for mqueue fs in the initialization stage

---

login-utils/login.c

A comment has not been moved when its associated code was moved.
While at it, change child_pid to pid_t data type as well.

login: Comment cleanup

---

include/c.h
libblkid/src/blkidP.h
libblkid/src/probe.c
libblkid/src/superblocks/adaptec_raid.c
libblkid/src/superblocks/cramfs.c
libblkid/src/superblocks/ddf_raid.c
libblkid/src/superblocks/drbd.c
libblkid/src/superblocks/highpoint_raid.c
libblkid/src/superblocks/isw_raid.c
libblkid/src/superblocks/jmicron_raid.c
libblkid/src/superblocks/lsi_raid.c
libblkid/src/superblocks/nvidia_raid.c
libblkid/src/superblocks/promise_raid.c
libblkid/src/superblocks/silicon_raid.c
libblkid/src/superblocks/via_raid.c

This PR mostly refactors the DRBD prober to avoid potential unaligned access when comparing the superblock magic.
For this it introduces some generic infrastructure that will be also useful for other probers.

libblkid: refactor drbd prober

---

libblkid/src/superblocks/lvm.c

The lvm2_calc_crc() will create a checksum over LVM2_LABEL_SIZE bytes, which all need to be read.
Currently this works because the superblock is cached by blkid_probe_get_idmag() which always reads 1024 bytes.

libblkid: (lvm2) read complete superblock

---

Documentation/howto-contribute.txt
Documentation/howto-pull-request.txt
README

GitHub has dropped support for the git:// protocol:
https://github.blog/changelog/2022-03-15-removed-unencrypted-git-protocol-and-certain-ssh-keys/

docs: use HTTPS for GitHub clone URLs

---

misc-utils/blkid.c

err_exclusive_options needs to be passed the long options array, otherwise it will crash.

libblkid: fix call to err_exclusive_options

---

libfdisk/src/utils.c

The else branch will be executed on short reads.
For those errno is not reset so a random left-over errno value may be checked.

libfdisk: reset errno before calling read()

---

libmount/src/tab.c

coverity claims that this is now a use-after-free. Let's revert the original change and make the code clearer before trying another fix.
This reverts commit d36306a560fd6d747e18ab22fc1279f4a373f43d.

Revert "libmount: (tab) avoid leaking memory allocated in loop"

---

libmount/src/hook_mount.c
libmount/src/mountP.h

The kernel helpfully provides feedback about failed operations via the
filesystem descriptor. Read that information and expose it via libmounts
debug facilities.
Notes:
For #2528 we get the following message:
`646514: libmount:      CXT: message from kernel:  e overlay: No changes allowed in reconfigure`
The `#define`-based usage is a bit iffy but so convenient.
Related to #2314

 libmount: report all kernel messages for fd-based mount API 

---

login-utils/login.c

- Use xasprintf instead of manually performing strlen + malloc + snprintf
- Access login.noauth file directly instead of scanning its parent directory for all files

login: simplify code

---

include/path.h
lib/path.c
sys-utils/lscpu-virt.c

- Avoid an out of boundary access on illegal /sys files
- Better error handling
- Remove ul_prefix_fopen
- Fix typos

lib/path: clean up path functions

---

meson.build

`conf` as configuration_data() object can contain any datatype. For `HAVE_FOO` variables this will be a `1` int to generate `#define HAVE_FOO 1` or a `false` bool to generate `#undef HAVE_FOO` in `conf.h`.
When retrieving and testing `HAVE_FOO` from `conf` it can be both types. Newer versions of meson are unhappy about comparisions of int with non-int
../meson.build:734: DEPRECATION: Project uses feature that was always broken, and is now deprecated since '1.2.0': int operations with non-int. It is not commutative and only worked because of leaky Python abstractions.
WARNING: Broken features used:
* 1.2.0: {'int operations with non-int'}
As both `int` and `bool` support a `.to_string()` method, we can use that to convert them into a well-known type and compare that.
Unfortunately meson …

meson: avoid int operation with non-int

---

libblkid/src/superblocks/exfat.c

Commit f98b56326 set the maximum number of iterations to 10000. If the volume label is after the 10000th entry, the volume label will not be found. So this commit sets the maximum number of iterations to correct value 256×1024×1024/32.
256×1024×1024/32 is from https://learn.microsoft.com/en-us/windows/win32/fileio/exfat-specification#95-directory-size-limits.

libblkid: exfat: fix fail to find volume label

---

tests/ts/chfn/gecos

Don't fail on `chfn/gecos` test in case of `/etc/libuser.conf` absence
Current behaviour:
```
chfn: gecos                          ...chfn: libuser initialization failed: could not open configuration file `/etc/libuser.conf': No such file or directory.
FAILED (chfn/gecos)
```
after patch:
```
util-linux/tests# ./run.sh chfn/gecos
...
chfn: gecos                          ... OK
```

[tests] fix chfn/gecos libuser.conf absence

---

sys-utils/lscpu.c

Fixes: https://github.com/util-linux/util-linux/issues/2544

lscpu: fix caches separator for --parse=<list>

---

include/mbsalign.h
include/strutils.h
lib/buffer.c
lib/mbsalign.c
lib/strutils.c
libsmartcols/docs/libsmartcols-sections.txt
libsmartcols/samples/fromfile.c
libsmartcols/samples/wrap.c
libsmartcols/src/calculate.c
libsmartcols/src/cell.c
libsmartcols/src/column.c
libsmartcols/src/libsmartcols.h.in
libsmartcols/src/libsmartcols.sym
libsmartcols/src/print.c
libsmartcols/src/smartcolsP.h
libsmartcols/src/table.c
misc-utils/findmnt.8.adoc
misc-utils/findmnt.c
misc-utils/lsblk.c
tests/expected/libsmartcols/fromfile-wrapzero
tests/expected/libsmartcols/fromfile-wrapzero-tree
tests/ts/libsmartcols/files/col-wrapzero
tests/ts/libsmartcols/files/data-string-nl
tests/ts/libsmartcols/files/data-string-zero
tests/ts/libsmartcols/fromfile

Now, we use line-break to separate data in multi-line cells (for example, MOUNTPOINTS in lsblk). This is pretty fragile as \n is a valid char in many cases (see https://github.com/util-linux/util-linux/issues/2533).
This set of patches adds to libsmartcols support to use \0 to separate data for the custom wrapping function (callback). It also rewrites how libsmartcols prepares data for the cells to make more easier to use (in the library) and avoid spaghetti code ...

libsmartcols: add support for zero separator 

---

include/loopdev.h
lib/loopdev.c
sys-utils/losetup.c

If a /dev/loopX is lost because someone might have removed it by mistake, future losetup operations on that loop device will fail and losetup --all and --list will not report the devices (although kernel still uses it).
Since /sysfs still have the loop device intact, detect that and report it.
Changes:
* --list and --all add "(lost)" after device node path
```
NAME              SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE    DIO LOG-SEC
/dev/loop0 (lost)         0      0         0  0 /root/l0.img   0     512
/dev/loop0 (lost): []: (/root/l0.img)
```
* use /sys to get devno rather than stat()
* report warning after failed operation
```
losetup: /dev/loop0: detach failed: No such file or directory 
losetup: device node /dev/loop0 (7:0) is lost. You may use mknod(1) to recover it.
```
* fix copy …

loopdev: report lost loop devices

---

meson.build

... to fix:
write: effective gid does not match group of /dev/pts/3

meson: install write executable with group 'tty'

---

libuuid/src/gen_uuid.c

Define cs_min through a `define` and not a `const int` to avoid the following build failure with `-O0` raised since version 2.39 and https://github.com/util-linux/util-linux/commit/2fa4168c8bc9d5438bc1dfadda293c7c21b6fa59:
```
libuuid/src/gen_uuid.c: In function 'uuid_generate_time_generic': libuuid/src/gen_uuid.c:536:33: error: initializer element is not constant
THREAD_LOCAL int  cache_size = cs_min;
^~~~~~
```
Fixes:
- http://autobuild.buildroot.org/results/2f80a5cdb523cc3c8c0f3693607a1be036b2ae98

libuuid/src/gen_uuid.c: fix cs_min declaration

---

misc-utils/lslocks.8.adoc
misc-utils/lslocks.c
tests/commands.sh
tests/expected/lslocks/lslocks-flock-ex
tests/expected/lslocks/lslocks-flock-sh
tests/expected/lslocks/lslocks-lease-w
tests/expected/lslocks/lslocks-ofd--w
tests/expected/lslocks/lslocks-ofd-r-
tests/expected/lslocks/lslocks-ofd-rw
tests/expected/lslocks/lslocks-posix--w
tests/expected/lslocks/lslocks-posix-r-
tests/expected/lslocks/lslocks-posix-rw
tests/ts/lslocks/lslocks

With this change, lslocks can show fill the COMMAND and PID columns of OFDLCK locks if the process of lslocks can access /proc/$pid/fdinfo/$fd.
```
qemu-system-x86 3003408 OFDLCK   10G READ  0        100        101 /var/lib/libvirt/images/client8-0.qcow2
qemu-system-x86 3003408 OFDLCK   10G READ  0        103        103 /var/lib/libvirt/images/client8-0.qcow2
qemu-system-x86 3003408 OFDLCK   10G READ  0        201        201 /var/lib/libvirt/images/client8-0.qcow2
qemu-system-x86 3003408 OFDLCK   10G READ  0        203        203 /var/lib/libvirt/images/client8-0.qcow2
...
```

lslocks: reduce "(unknown)" and "(undefined)" by utilizing "lock:" fields of /proc/$pid/fdinfo/$fd

---

misc-utils/lsfd-sock-xinfo.c
misc-utils/lsfd.c

Passing a pointer to a pid_t to tfind() which expects it to be backed by a 'struct proc' evokes undefined behavior.
This triggers UBSAN as shown below.
Instead pass a proper 'struct proc'.
```
../misc-utils/lsfd.c:513:27: runtime error: member access within misaligned address 0x7ffe9ee6495c for type 'struct proc', which requires 8 byte alignment 0x7ffe9ee6495c: note: pointer points here
1a 1a 1a 1a 01 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  d0 49 e6 9e fe 7f 00 00
^
#0 0x56159cfa4a3b in proc_tree_compare ../misc-utils/lsfd.c:513
#1 0x7f9dd4d2d743 in __tfind (/usr/lib/libc.so.6+0x10f743) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)
#2 0x56159cfa4ac3 in get_proc ../misc-utils/lsfd.c:518
#3 0x56159cfe217b in anon_pidfd_get_name ../misc-utils/lsfd-unkn.c:203
#4 …
```

lsfd: avoid undefined behavior

---

configure.ac
libfdisk/samples/Makemodule.am
libfdisk/samples/mkpart-fullspec.c
libfdisk/samples/mkpart.c
libfdisk/src/Makemodule.am
libfdisk/src/ask.c
libfdisk/src/gpt.c
libfdisk/src/item.c
libfdisk/src/script.c
libfdisk/src/utils.c
libfdisk/src/version.c
libmount/samples/Makemodule.am
libmount/src/Makemodule.am
libmount/src/cache.c
libmount/src/context.c
libmount/src/context_mount.c
libmount/src/lock.c
libmount/src/monitor.c
libmount/src/optlist.c
libmount/src/optstr.c
libmount/src/tab.c
libmount/src/tab_diff.c
libmount/src/tab_update.c
libmount/src/utils.c
libmount/src/version.c
libsmartcols/samples/Makemodule.am
libsmartcols/samples/continuous.c
libsmartcols/samples/maxout.c
meson.build

The autotools build used -Wno-unused-parameter to silence these warnings for a few files. On meson however this configuration was not duplicated leading to persistent warnings, preventing the usage of -Werror.
Instead of having to maintain the exceptions in two buildsystems, mark the exceptions directly in the source code.
Afterward clean up autotools to not use -Wno-unused-parameter anymore.

treewide: explicitly mark unused arguments

---

sys-utils/irq-common.c

`qsort`(3) requires three-way result like that from `strcmp`(3), not an `std::less`-like boolean.
The wrong result is very obvious on Alpine where musl version of `qsort`(3) probably have different properties than one in glibc.
The suggested fix seems to work on both musl and glibc.

irqtop: fix numeric sorting

---

include/xalloc.h
misc-utils/lsfd.h
misc-utils/lslocks.8.adoc
misc-utils/lslocks.c
tests/expected/lslocks/lslocks-flock-ex+HOLDERS
tests/expected/lslocks/lslocks-flock-sh+HOLDERS
tests/expected/lslocks/lslocks-lease-w+HOLDERS
tests/expected/lslocks/lslocks-ofd--w+HOLDERS
tests/expected/lslocks/lslocks-ofd-r-+HOLDERS
tests/expected/lslocks/lslocks-ofd-rw+HOLDERS
tests/helpers/test_mkfds.c
tests/ts/lslocks/lslocks

In open file description-oriented locks like flock, there can be more than one holder for a lock. This pull request adds a new column "CO-HOLDERS" to lslocks. The column is for printing the holders for a lock.
An example output:
```
$  ./test_mkfds make-regular-file 5 file=/tmp/xxx lock=lease-w dupfd=9
3113841
```
This command line makes a write lease for /tmp/xxx opened as fd 5, then duplicates the fd. The process gets 9 as the duplicated fd.
```
$ ./lslocks -p 3113841 -o+CO-HOLDERS
COMMAND             PID  TYPE SIZE MODE  M START END PATH   CO-HOLDERS
test_mkfds      3113841 LEASE      WRITE 0     0   0 /tmp/x 3113841,test_mkfds,5
3113841,test_mkfds,9
```
lslocks can print both 5 and 9 in the CO-HOLDERS column.

lslocks: add HOLDERS column

---

include/shells.h
lib/shells.c
login-utils/chsh.c

lib/shells.c uses already libeconf to read /etc/shells, so do the same for chsh -l. Else it could be surprising if shells are declared as valid which chsh -l does not list.

chsh: use libeconf to read /etc/shells

---

sys-utils/lscpu-arm.c

Adding core information for Phytium E2000 series CPU: FTC310 and FTC664

Add Phytium FTC310 & FTC664 support

---

.github/workflows/cibuild.sh

Now that all warnings have been eliminated from the meson build, make sure no new ones are introduced.

ci: enable -Werror for meson

---

configure.ac
meson.build
tests/helpers/Makemodule.am

Link: https://lore.kernel.org/util-linux/9211accf8670f28778166a1acdc186e8dd28f2e8.camel@physik.fu-berlin.de/

build: only build test_enosys if an audit arch exists

---

login-utils/su-common.c

musl has removed the non-prototype declaration of basename from string.h [1] which now results in build errors with clang-17+ compiler
include libgen.h for using the posix declaration of the funciton.
Fixes
../util-linux-2.39.2/login-utils/su-common.c:847:20: error: call to undeclared function 'basename'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
847 |                 shell_basename = basename(shell);
|                                  ^
[1] https://git.musl-libc.org/cgit/musl/commit/?id=725e17ed6dff4d0cd22487bb64470881e86a92e7
Signed-off-by: Khem Raj <raj.khem@gmail.com>

login-utils: include libgen.h for basename API

---

sys-utils/unshare.c

If the child process is killed with `SIGKILL`, don't attempt to reset the disposition of `SIGKILL` (which can't be caught or ignored anyway) before self-signalling, which caused a misleading `sigprocmask unblock failed` error instead of dying with the same `SIGKILL` status as the child. This fixes https://github.com/util-linux/util-linux/issues/2614.

unshare: don't try to reset the disposition of SIGKILL

---

misc-utils/rename.c
tests/expected/rename/basic
tests/ts/rename/basic

Instead of hand-rolling a basename() function use the standard one which provides the functionality that we want to use.
Also add a testcase.
Fixes #2569

rename: properly handle directories with trailing slash

---

include/Makemodule.am
include/column-list-table.h
misc-utils/lsfd.c
misc-utils/lslocks.8.adoc
misc-utils/lslocks.c

Before implementing -H options to the other ls* commands, I revised that in lsfd.
The original code does the following:
```
fprintf(out, " %20s  %-10s%s\n", infos[i].name,
```
I wanted to remove "20" and "10".
Do you think using libscols as the replacement is overkiling?

Refactor the implementation of -H option in lsfd

---

libuuid/src/libuuid.sym
libuuid/src/uuid.h
libuuid/src/uuid_time.c

There is one big problem where I don't know how to solve best: it is not expected that uuid_time() can fail. But with an uuid created e.g. 2040, it has to fail. The current "error handling" by does not really work, any ideas how this could be done better?
My current proposal would be, set ret_val to NULL, set errno and return -1.
Else the behavior depends on with which flags which parts where compiled:
Old 32bit binary using libuuid with time64_t: identical output as with libuuid.so.1.3.0 for UUIDs created before 2038. With UUIDs created after 2038, error handling is missing.
New 32bit binary with time64_t linked against time64_t compiled libuuid: everything works correct.
New 32bit binary with time64_t linked against time64_t compiled libuuid, but running with a new libuuid compiled …

libuuid: Add uuid_time64 for 64bit time_t on 32bit

---

text-utils/more.c

more command continues to run in case stdin have closed the file and it takes 100% of CPU. This is because revents on stdin send POLLIN | POLLHUP | POLLERR once stdin is closed. more receives it even though it is not requested in events. This is common Linux behaviour to never mask out POLLHUP or POLLERR. The loop in more_key_command() runs infinitely because more_poll() returns 0 and read_command() reads 0 bytes.
Check for POLLERR and POLLHUP, and exit more in case of an error.
Steps to reproduce:
1. Setup /etc/systemd/logind.conf with KillUserProcesses=no
2. Add config "Defaults use_pty" in /etc/sudoers
3. Start an ssh session to the machine
4. # sudo su -
5. # more <big enough file>
6. kill the parent ssh process, say close the tab
At this time "more" runs with 100% CPU utilization.

more: exit if POLLERR and POLLHUP on stdin is received

---

bash-completion/setpriv
configure.ac
meson.build
sys-utils/Makemodule.am
sys-utils/meson.build
sys-utils/setpriv-landlock.c
sys-utils/setpriv-landlock.h
sys-utils/setpriv.1.adoc
sys-utils/setpriv.c
tests/commands.sh
tests/expected/setpriv/landlock-nothing-allowed
tests/expected/setpriv/landlock-partial-access-fail
tests/ts/setpriv/landlock

landlock [0] is a Linux stackable LSM that can be used by unprivileged processes to build a sandbox around them.
With support for landlock in setpriv users can easily construct a sandbox on-the-fly when executing programs.
[0] https://landlock.io/
Note: This is only an RFC state, missing help, completions and docs.

setpriv: add landlock support

---

sys-utils/fallocate.c

Otherwise it can generate a unused variable warning.

fdisk: guard posix variable

---

po-man/po4a.cfg

As usual: Once a new man page arises, it needs to be added to po-man/po4a.cfg to make it translatable. Maybe an extension of the script tools/checkadoc-missing.sh would be helpful…?

exch: Add man page to po4a.cfg to make it translatable

---

misc-utils/lsclocks.1.adoc

This patch adds the man pages of enosys and lsclocks to po4a.cfg to make them translatable. Besides that, it fixes the Asciidoctor markup in lsclocks.1.adoc to add line breaks for better readability.

enosys and lsclocks: Add man pages to po4a.cfg

---

sys-utils/hwclock.c

set_hardware_clock_exact() spins in a loop, trying to exit when we are `delay` seconds from an integer time on the system clock. However, there might be jitter which causes an exit a little bit later than ideal.
The prior code could cause a relatively small error in loop exit time to produce a relatively large error in the RTC.
For example, suppose upon exit from the loop, we have:
sethwtime=1704239206
refsystime=1704239206.000000
nowsystime=1704239206.500372
delay=0.5
In this case, the error is very small: 0.000372. However, we will compute:
newhwtime = 1704239206 + ceil(0.500371 - 0.5) = 1704239207
And in slightly less than `delay` seconds, the system clock will be 1704239207 while the RTC will be approximately 1704239208, about 1 second of error.
We are better off rounding in this …

hwclock: Improve set error in the face of jitter

---

libfdisk/src/bsd.c
libfdisk/src/dos.c
libfdisk/src/fdiskP.h
libfdisk/src/gpt.c
libfdisk/src/parttype.c
libfdisk/src/sgi.c
libfdisk/src/sun.c

The builtin struct fdisk_parttypes are not supposed to be modified. This is enforced in the mutation functions.
While the API could be cleaned up to distinguish between const and non-const versions of fdisk_parttype this could break user code.
Instead preserve the API and add some internal casts.

libfdisk: constify builtin fdisk_parttype

---

login-utils/login.1.adoc
login-utils/login.c

The login program would run every shell with a blank in its name (as defined in pw_shell) as a shell script. Check if it is an executable binary first to support such login shells as well.
While at it, improve error message and simplify name creation.
Proof of Concept (error message):
1. Set login shell of a user to `/bin/sh`
2. Remove executable permission for this user from `/bin/sh`
3. Try to log in
You will see that the error message states that shell script could not be executed
Proof of Concept (blank shell)
1. Create symbolic link from e.g. `/bin/sh with blank` to `/bin/sh`
2. Set login shell of a user to `/bin/sh with blank`
3. Depending on your PAM setup, you have to add `/bin/sh with blank` to `/etc/shells`
5. Try to log in
The login will fail due to illegal call of the shell …

login: allow login shells with blank in path

---

libmount/src/context.c
libmount/src/context_umount.c
libmount/src/lock.c
libmount/src/monitor.c
libmount/src/mountP.h
libmount/src/tab_update.c
libmount/src/utils.c
misc-utils/logger.c

This PR splits utab locking and utab changes reporting. The issue is that the lock can be used more than once during one mount(8) call when /sbin/mount.type helper used. The multiple events for one mount can make some applications that depend on x-* options in utab confused (e.g. gnome).
After this, libmount will use utab.lock for locking and utab.event to inform applications about a change. The built-in libmount monitor was also modified to use utab.event now. The change is backward compatible, applications that monitor utab.lock will still work without a change.

libmount: utab event

---

libuuid/src/gen_uuid.c
libuuid/src/uuidP.h
misc-utils/uuidd.c

cont_clock requires a correct time setup and therefore it must be possible to detect a step back between uuidd starts.
Reserving the next 10 seconds is sufficient and should not have a noticeable performance impact. It will also provide the possibility to start with the clock_reg from the previous session when the system was rebooted.
Whith that, the early cont_clock initialization in uuidd should be removed because writing the cont_clock persitence when -C was not set is useless and might be confusing.

uuidd: add cont_clock persistence

---

tests/expected/fdisk/mbr-nondos-mode-first-sector-at-end
tests/expected/fdisk/sunlabel-create-second-partition
tests/expected/libfdisk/gpt-all-defaults
tests/expected/libfdisk/gpt-all-defaults-with-typo

Fixes: 101dca2f18eb ("libfdisk: fdisk_deassign_device: only sync(2) blockdevs")

libfdisk: (tests) fix tests for removal of non-blockdev sync()

---

sys-utils/fallocate.c

Unlike Linux native system calls, posix_fallocate doesn't return -1 whe an error occurs; it returns a errno value directly.
The bug of the original code was reported by @Yugend on #2714.

fallocate: fix the way to evaluate values returned from posix_fallocate

---

sys-utils/ctrlaltdel.c

The ctrlaltdel performs an extra permission check with `geteuid()` , preventing the non-root processes from executing the reboot system call, even with the CAP_SYS_BOOT capability which should be enough. Sees #2709

ctrlaltdel: remove unnecessary uid check

---

libmount/docs/libmount-sections.txt
libmount/src/context.c
libmount/src/libmount.h.in
libmount/src/libmount.sym
libmount/src/lock.c
libmount/src/monitor.c
libmount/src/mountP.h
libmount/src/tab_update.c

This is the last set of patches to improve x-* options used in gnome and other userspace applications that monitor mount events. We must avoid reloading the mount table in the applications if the mount process is incomplete and generates multiple events. This all is done only for mounts with x-* options. For performance reasons, kernel-only mounts have no userspace synchronization with the monitor.

libmount: veil kernel events in monitor

---

bash-completion/findmnt
misc-utils/findmnt.8.adoc
misc-utils/findmnt.c
misc-utils/findmnt.h

An example output:
$ ./findmnt -I
SOURCE                            FSTYPE      INO.TOTAL  INO.USED INO.AVAIL INO.USE% TARGET
/dev/mapper/fedora_dev64-root     ext4          5341184   1135307   4205877      21% /
devtmpfs                          devtmpfs     32930640      1209  32929431       0% /dev
tmpfs                             tmpfs        32938620        86  32938534       0% /dev/shm
...

findmnt: add -I, --dfi options for imitating the output of df -i

---

configure.ac
liblastlog2/lastlog2.pc.in
liblastlog2/src/Makemodule.am
pam_lastlog2/Makemodule.am

* use pkg-config (PKG_CHECK_MODULES) rather than check for sqlite3.h only
* define $SQLITE3_LIBS
* use UL_ macros in configure.ac for liblastlog2 and pam_lastlog2
* add --disable-pam-lastlog2
* check for PAM to define BUILD_PAM_LASTLOG2
* install lastlog2.h to $(includedir)/liblastlog2/lastlog2.h
* fix liblastlog2_la_LDFLAG
* add Requires.private to lastlog2.pc.in
* use $(SQLITE3_LIBS) rather than hardcoded -lsqlite3
Fixes: https://github.com/util-linux/util-linux/issues/2734
I'm not sure if something will also be necessary for meson. Probably possibility disable pam_lastlog2, this PR is autotools only ;-)

autotools: cleanup lastlog2 stuff

---

.github/workflows/cibuild.yml

Some configurations where not migrated from 10 to 13.

ci: consistently use gcc 13 during CI

---

meson.build

SO_PASSCRED is not exposed in standards mode that was enabled in commit 6240e4458cdf ("build: use -std=c99 and -std=c++11 by default").
Fixes: #2750

meson: define _GNU_SOURCE when checking for SO_PASSCRED

---

lib/c_strtod.c

Without this fix, compilation fails with:
```
../lib/c_strtod.c: In function ‘c_strtod’:
../lib/c_strtod.c:56:45: error: ‘locale’ undeclared (first use in this function); did you mean ‘c_locale’?
56 |                 locale_t org_cl = uselocale(locale);
|                                             ^~~~~~
|                                             c_locale
../lib/c_strtod.c:56:45: note: each undeclared identifier is reported only once for each function it appears in
gmake[2]: *** [Makefile:11631: lib/libcommon_la-c_strtod.lo] Error 1
```

lib/c_strtod: fix uselocale() fallback if strtod_l() is not available

---

misc-utils/lsclocks.c

lsclocks: use clock id from clock_getcpuclockid in add_cpu_clock

---

.gitignore
meson.build
misc-utils/Makemodule.am
misc-utils/lsfd-file.c
misc-utils/lsfd-sock-xinfo.c
misc-utils/lsfd.1.adoc
misc-utils/lsfd.c
misc-utils/lsfd.h
tests/expected/lsfd/error-eaccess
tests/expected/lsfd/error-eperm
tests/helpers/test_mkfds.c
tests/ts/lsfd/error-eaccess
tests/ts/lsfd/error-eperm
tools/Makemodule.am
tools/all_errnos

This change may go to v2.41.
lsfd ignored file descriptors with that readlink(2) or
stat(2) returned errors.
With ERORR type, lsfd can print these file descriptors with incomplete
information.
An example output:
COMMAND        PID   USER ASSOC  XMODE  TYPE          SOURCE MNTID INODE NAME
systemd      10677 yamato    31 ????-- ERROR readlink:EACCES
slirp4netns 901147 yamato     7 ????-- ERROR     stat:EACCES             /home/yamato/.local/share/.../merged
The format of SOURCE column is SYSCALL:ERRNO.

lsfd: list file descriptors with incomplete information

---

libmount/python/meson.build

The extension_module call was in the wrong place.

meson: Only build libmount python module if python was found

---

include/blkdev.h

In Linux commit c5f1ac8b94bd10f97f5aa1a3279ad8e8bbc6311a (“Split SCSI header files”) these definition where split out into `include/scsi/scsi_proto.h`
This commit also removes the git link (any kernel sources will do just fine) and just names the file.

blkdev.h: update location of SCSI device types

---

include/c.h
lib/pager.c
misc-utils/hardlink.c
text-utils/pg.c

"Fetching and setting the value of errno is async-signal-safe provided that the signal handler saves errno on entry and
restores its value before returning."
save and restore errno on cases where it is needed.

Save and restore errno on signal handlers

---

misc-utils/namei.1.adoc

This was being rendered in the man page as:
The program was rewritten by Karel Zak Karel Zak <kzak@redhat.com>.
Instead of as:
The program was rewritten by Karel Zak <kzak@redhat.com>.

docs: remove duplicated author name in namei.1.adoc

---

misc-utils/lastlog2.c

This replicates the behavior of lastlog. Having extra space at the end of the line can trip up some parsers.

lastlog2: Don't print space if Service column is not printed

---

meson.build

Through the addition of default_options: c_std=c99 some build-time checks were incorrect. Explicitly add -D_GNU_SOURCE where necessary.
Fixes: 6240e4458cdf ("build: use -std=c99 and -std=c++11 by default")
(This is also for 2.40)

meson: run compiler checks with -D_GNU_SOURCE when necessary

---

sys-utils/lscpu-arm.c

References: 
* [Neoverse-V3](https://developer.arm.com/documentation/107734/0001/AArch64-registers/AArch64-Identification-registers-summary/MIDR-EL1--Main-ID-Register)
* [Neoverse-N3](https://developer.arm.com/documentation/107997/0000/AArch64-registers/AArch64-Identification-registers-summary/MIDR-EL1--Main-ID-Register)

Adding Neoverse-V3/-N3 ARM cores

---

meson_options.txt

Avoid the following message from meson:
NOTICE: Future-deprecated features used:
* 1.1.0: {'"boolean option" keyword argument "value" of type str'}

meson: avoid future-deprecated feature

---

sys-utils/dmesg.c

* don't use string based function strspn() if work with non-zero terminated buffer
* make sure that message size is calculated from within buffer pointers
Fixes: https://github.com/util-linux/util-linux/issues/2807

dmesg: fix wrong size calculation

---

libmount/src/context.c
libmount/src/context_mount.c
libmount/src/hook_mount.c
libmount/src/mountP.h

This is a very minimalistic implementation for v2.40 designed to print error messages from the kernel. It exclusively displays errors, and the patch does not introduce any new library interface for this purpose. Instead, it simply replaces hardcoded messages within libmount with kernel messages.
It's worth noting that the final implementation will necessitate per-hook error handling in libmount and likely a new library API to access other types of messages (warnings, notices, etc.).

libmount: report kernel message from new API

---

disk-utils/blockdev.8.adoc
disk-utils/blockdev.c

If you execute the command
blockdev --report /dev/noexist
we get an error "blockdev: cannot open /dev/noexist: No such file or directory".
But the return code (echo $?) is 0.
I suggest to return 1 if we get an error in the report.

Fixed report return code in blockdev.

---

meson.build

Checks for the required headers for blkzone and blkptr are done for Autotools. This logic wasn't carried over to Meson. This PR just adds the same checks.
Fixes #2850.

meson: Only build blkzone and blkpr if the required linux header exists

---

libmount/src/hook_mount.c
libmount/src/mountP.h
libmount/src/optlist.c

mount(8) cares about case when option specified as "name=" (it means without data). See for example 727c689908c5e68c92aa1dd65e0d3bdb6d91c1e5.
We need this also for new mount API and use FSCONFIG_SET_STRING rather than FSCONFIG_SET_FLAG.
strace -e fsconfig ./mount -o usrjquota= /dev/sdc1 /mnt/test
Old:
fsconfig(3, FSCONFIG_SET_STRING, "source", "/dev/sdc1", 0) = 0 fsconfig(3, FSCONFIG_SET_FLAG, "usrjquota", NULL, 0) = -1 EINVAL (Invalid argument)
Fixed:
fsconfig(3, FSCONFIG_SET_STRING, "source", "/dev/sdc1", 0) = 0 fsconfig(3, FSCONFIG_SET_STRING, "usrjquota", "", 0) = 0
Fixes: https://github.com/util-linux/util-linux/issues/2837

libmount: make sure "option=" is used as string

---

sys-utils/hwclock-rtc.c

passing double pointer doesn't fill param value

sys-utils: hwclock-rtc: fix pointer usage

---

libuuid/man/uuid_compare.3.adoc
libuuid/man/uuid_copy.3.adoc
libuuid/man/uuid_is_null.3.adoc
libuuid/man/uuid_parse.3.adoc
libuuid/man/uuid_time.3.adoc
libuuid/man/uuid_unparse.3.adoc

Several function declarations in the libuuid man pages contradicts with those in [the header](https://github.com/util-linux/util-linux/blob/master/libuuid/src/uuid.h).

libuuid: (man) fix function declarations

---

meson.build

meson: respect c_args/CFLAGS when generating syscalls/errnos

---

pam_lastlog2/Makemodule.am

Otherwise building the dist tarball via meson doesn't work.
Fixes #2875

autotools: distribute pam_lastlog2/meson.build

---

README.licensing
sys-utils/flock.c

Looking at the license text, flock.c is under the MIT license (see https://spdx.org/licenses/MIT).
Add an SPDX license identifier header and add to the list of licenses the source so everything is correctly listed/identified.

README.licensing/flock: Add MIT license mention

---

meson.build

HAVE_ENVIRON_DECL is being defined to 0 by cfg_data.set10(). The code only checks whether or not is defined. This leads to it not being declared appropriately. Use cfg_data.set() instead of cfg_data.set10() to define it when true.
Fixes #2884.

meson: Don't define HAVE_ENVIRON_DECL when environ is unavailable

---

pam_lastlog2/src/Makemodule.am

While at it also drop the duplicated include path.
Fixes #2897

pam_lastlog2: link against liblastlog

---

meson.build

The `crypt` library is only necessary for two executables. These are build-newgrp and build-sulogin. Don't otherwise require this dependency.
Fixes  #2876.

meson: Only require the crypt library when necessary

---

meson.build

The has_function check incorrectly detects mempcpy on macOS. This function is not available on macOS and should not be detected. Likely, this has to do with Meson's detection of compiler built-ins. Use has_header_symbol to check for this symbol instead.
Fixes #2880.

meson: Fix false positive detection of mempcpy on macOS

---

tests/helpers/test_mkfds.c

Close #2901
The original code passed a closed file descriptor to bind(2).

tests: (test_mkfds::netlink) pass a correct file descriptor to bind(2)

---

libblkid/src/topology/ioctl.c

Coverity complains about the data copy within the union. Instead use a dedicated temporary value.
While at it replace the hardcoded numeric size values with sizeof() expressions as used in "topology_vals".

libblkid: topology/ioctl: don't copy within union

---

libblkid/src/blkidP.h
libblkid/src/probe.c
libblkid/src/superblocks/luks.c
libblkid/src/superblocks/superblocks.c
libblkid/src/superblocks/superblocks.h

When LUKS OPAL HW encryption is enabled and the partition is locked, any read from the locked area ends in reading error. The blkid tool is used in udev rules (at least in Debian), which is executed on every close of the block device, so errors from blkid can flood the logs. Fix this by checking LUKS first.
I do not know if it is correct to check LUKS before RAID, but it is crucial to not touch LUKS area before LUKS it is unlocked.
Not checking LUKS before RAID leads to the following errors when OPAL area is not yet unlocked:
```
kernel: ata8.00: exception Emask 0x0 SAct 0x0 SErr 0x0 action 0x0
kernel: ata8.00: irq_stat 0x40000001
kernel: ata8.00: failed command: READ DMA EXT
kernel: ata8.00: cmd 25/00:08:80:af:c0/00:00:d1:01:00/e0 tag 23 dma 4096 in
res …
```

libblkid: Check LUKS OPAL before RAID

---

misc-utils/lsfd-sock-xinfo.c
misc-utils/lsfd.c
misc-utils/lsfd.h
tests/helpers/test_mkfds.c

(Rewrote in Apr  5 2024)
This pull request is for skipping the test cases reported as failed on the platform where sock diag sockets for AF_UNIX don't work.
To seek the root cause of the failure, I also added `LSFD_DEBUG` environment variable. 
(The original message)
This pull request enables debug print for inspecting #2822. This pull fixes the test helper. So, merging this to v2.40.x is optional.

tests: (test_mkfds::sockdiag) verify the recieved message to detect whether the socket is usable or not

---

tests/ts/lsfd/mkfds-multiplexing

Close #2867
Close #2887
We should skip the test case on the platforms where /proc/$pid/syscall doesn't report correct system call number. On such platforms,

tests: (lsfd::mkfds-multiplexing) skip if /proc/$pid/syscall is broken

---

meson.build

This matches what the autotools build is doing.
Also see https://github.com/util-linux/util-linux/pull/2768 .

meson: use signed chars

---

sys-utils/lsns.c
tests/ts/lsns/filedesc

Close #1884.
```
4026540683 /run/netns/foo
[1] 1187058
NS TYPE NPROCS PID USER COMMAND
4026540683 net       0     root
```
Even after removing the nsfs file created by ip-netns-add, lsns successfully reports the namespace.

lsns: show namespaces only kept alive by open file descriptors

---

include/pidfd-utils.h
misc-utils/Makemodule.am
misc-utils/lsfd-file.c
misc-utils/lsfd-pidfd.c
misc-utils/lsfd-pidfd.h
misc-utils/lsfd-unkn.c
misc-utils/lsfd.c
misc-utils/lsfd.h
misc-utils/meson.build
tests/expected/lsfd/column-name-pidfd
tests/expected/lsfd/column-type-pidfd
tests/expected/lsfd/mkfds-pidfd
tests/ts/lsfd/column-ainodeclass
tests/ts/lsfd/column-name
tests/ts/lsfd/column-type
tests/ts/lsfd/mkfds-pidfd

In Linux 6.9 pidfds are moved from the anonymous inode infrastructure to a tiny pseudo filesystem named pidfs.  Recognize it properly.
Fixes #2865.

lsfd: Support pidfs

---

misc-utils/enosys.1.adoc

"utility <ins>to</ins> make syscalls fail with ENOSYS"

enosys: (man) add missing word

---

meson.build

liblastlog2 requires the sqlite dependency. Currently, Meson enforces this dependency to be available only when the build-liblastlog2 feature is explicitly enabled. liblastlog2 is built by default, so if sqlite is not available, the build will be configured correctly, but fail to compile. This commit fixes this case by automatically disabling the build-liblastlog2 feature when it is auto and sqlite is not found.
Fixes #2921.

meson: Enforce sqlite dependency for liblastlog2

---

libmount/python/meson.build

Meson doesn't properly check that the necessary Python.h header file is available for the pylibmount module.
Passing true for the embed keyword argument for the Python dependency function ensures that this header file is available.
The Python dependency function is documented [here](https://mesonbuild.com/Python-module.html#dependency).
Fixes #2923.

meson: Require Python dependency which can be embedded for pylibmount

---

tests/ts/lsfd/mkfds-multiplexing

This is the same as #2910 but for the master branch. 
Close #2867
Close #2887
We should skip the test case on the platforms where /proc/$pid/syscall doesn't report correct system call number. On such platforms,
(cherry picked from commit e199a933058ae052b1dfa2fcb457791f47b60b11)

<for the master branch>tests: (lsfd::mkfds-multiplexing) skip if /proc/$pid/syscall is broken

---

misc-utils/findmnt.c
misc-utils/findmnt.h
tests/expected/findmnt/df-options
tests/ts/findmnt/df-options

Fixes #2913.
3dd79293b5b655da9d913dedd8facb08959a7826 added -I option. However, the code used bit flags (FL_DF and FL_DF_INODES) wrongly; the code broke the output of the -D option.
This change is applicable to both the master and stable branch

findmnt: revise the code for -I and -D option

---

meson.build

Several executables require the pam library. The current behavior in Meson only requires this library when these executables are explicitly enabled. Unfortunately, by default, Meson will not throw an error when the required pam library is missing while still trying to build these executables. To fix this, make the pam library a disabler which automatically disables these executables if it is not found.
Fixes #2925.

meson: Disable targets requiring pam when it is missing

---

libblkid/meson.build
libuuid/meson.build

macOS does not support the --version-script linker flag. Only use it if it is available. I started with the libraries I know this needs to be done for. It might need to be done for more than just `libuuid` and `libblkid`. Not sure if `darwin_versions` needs to be used to better control API compatibility on macOS.
Fixes #2935.

meson: Only use the --version-script linker flag where it is supported

---

sys-utils/lsns.8.adoc
sys-utils/lsns.c
tests/helpers/test_sysinfo.c
tests/ts/lsns/filedesc
tests/ts/lsns/filter

In the original code, lsns printed nothing if it failed in opening the
last dntry in /proc/[0-9]* though lsns should work partially.
The original behavior caused the combination of the following two
test cases failed:
$ tests/ts/lsns/filter & tests/ts/lsns/ioctl_ns &
[1] 19178
[2] 19179
$          lsns: ownership and hierarchy        ...         \
lsns: -Q, --filter option            ... FAILED
FAILED
[1]-  Done                    tests/ts/lsns/filter
[2]+  Done                    tests/ts/lsns/ioctl_ns

lsns: continue the executing even if opening a /proc/$pid fails

---

misc-utils/lslocks.c
tests/ts/lslocks/lslocks

If a process ($pid) taking a lock is gone while running lslocks,
gathering per-process information for the process may fail in opening
/proc/$pid. Though lslocks should work with incomplete information,
the original code stopped gathering per-process information for the
other processes.
As a result of the original behavior, tests/ts/lslocks/lslocks really
failed in an environment where multiple test cases ran simultaneously.
Close #2624 again.
See also #2633.

lslocks: don't abort gathering per-process information even if opening a /proc/[0-9]* fails

---

meson.build
meson_options.txt

Same as #2879 but for the `stable/v2.40` branch.

meson: Add build-lsfd option and make rt dependency optional

---

tests/functions.sh
tests/ts/lsfd/lsfd-functions.bash

Fixes #2919.
Suggested by Karel Zak <kzak@redhat.com>.
The original code used an obsolete formula to make a device number from given major and minor numbers.
ts_device_make is a new helper function based on the formula of __SYSMACROS_DEFINE_MAKEDEV macro defined in
/usr/include/bits/sysmacros.h of GNU libc.
Suggested by Karel Zak <kzak@redhat.com> in #2919.

tests: (functions.sh) add a helper funcion making a device number from given major and minor nums

---

libsmartcols/scols-filter.5.adoc
libsmartcols/src/filter-parser.y
libsmartcols/src/filter-scanner.l
libsmartcols/src/filter.c

Based on https://github.com/util-linux/util-linux/pull/2864 from @masatake.

libsmartcols: (filter) accept prefix like k, M, G as a parts of a number

---

include/Makemodule.am
include/fgetwc_or_err.h
login-utils/islocal.c
term-utils/agetty.c
tests/expected/colcrt/regressions-crash1
tests/expected/colcrt/regressions-crash1.err
tests/expected/colcrt/regressions-crash2
tests/expected/colcrt/regressions-crash2.err
tests/expected/colcrt/regressions-hang1
tests/expected/colcrt/regressions-hang1.err
tests/ts/colcrt/regressions
text-utils/colcrt.c
text-utils/colrm.c
text-utils/more.c
text-utils/rev.c
text-utils/ul.c

A return value of WEOF of fgetwc() can either mean end-of-file or an
error in errno. The error was ignored and interpreted as end-of-file.
Introduce a new helper that aborts on error and use it in text-utils.
This replaces all calls to plain fgetwc().
Closes #2909
@jidanni Your testcase from #2909 now:
```
perl -wle 'print pack("CCC",0xef,0xbb,0xbf), 1 x 22;'|env - LC_CTYPE=zh_TW.UTF-8 ./colrm 11|wc
colrm: fgetwc() failed: Invalid or incomplete multibyte or wide character
0       0       0
```

textutils: introduce and use fgetwc_or_err

---

meson.build

The cherry-pick of #2879 in PR #2941 to the stable/v2.40 branch didn't include the removal of `mq_libs` like it should have. I must have resolved a conflict incorrectly in the cherry-pick. This just removes the lingering definitions which are no longer used. The extra `find_library` call for `rt` is a problem and this fixes that.

meson: Remove lingering mq_libs variable

---

misc-utils/lslocks.c
tests/ts/lslocks/lslocks

The same as #2953 but for the stable branch.
This fixes the failure of "lslocks/lslocks" test case.

<for the stable branch>  lslocks: don't abort gathering per-process information even if opening a /proc/[0-9]* fails

---

configure.ac
meson.build
misc-utils/Makemodule.am
tools/all_errnos
tools/all_syscalls

Posix-compliant awk does not seem capable of matching lines and extracting capture groups of them.
Use sed instead.
Reported-by: John Paul Adrian Glaubitz <glaubitz@physik.fu-berlin.de>
Link: https://lore.kernel.org/util-linux/051624b9256db27a731d62c031cb627d9f5a256e.camel@physik.fu-berlin.de/

all_errnos/all_syscalls: use sed to extract defines from headers

---

disk-utils/fdisk-list.c
disk-utils/fdisk-list.h
disk-utils/fdisk-menu.c
disk-utils/fdisk.c
disk-utils/fdisk.h
libfdisk/docs/libfdisk-sections.txt
libfdisk/src/ask.c
libfdisk/src/libfdisk.h.in
libfdisk/src/libfdisk.sym
sys-utils/blkdiscard.8.adoc

We currently have blkdiscard(8), but it can be difficult to use for unpartitioned areas or for partitions when working with a whole-disk device.
This PR adds BLKDISCARD support to fdisk, so that the user does not have to specify any range, but instead follows the partition table.

fdisk trim support

---

meson.build
meson_options.txt

The `build-ipcrm` option exists in `meson_options.txt` but has no effect. Use the option to gate building the `ipcrm` executable.
Add `build-ipcmk` option.
Require the `seminfo` type for `ipcmk`, `ipcrm`, and `ipcs`.

meson: Add missing check for build-ipcrm option and the seminfo type

---

configure.ac
meson.build
misc-utils/Makemodule.am
tools/all_syscalls

Backport of #2960 and #2964 , without the changes to `all_syscalls` as that doesn't exist there.

v2.40: all_syscalls: use sed

---

meson.build

Meson's check for an absolute path does not work on Windows. Meson 0.54.0 introduced the [fs.is_absolute](https://mesonbuild.com/Fs-module.html#is_absolute) function. Use this instead.

meson: Use is_absolute to determine if the prefix directory is absolute

---

meson.build
meson_options.txt

Require the `sys/klog.h` header to exist in order to enable the feature.

meson: Add build-dmesg option

---

term-utils/agetty.c

Before 4869b259d68f65ea88df625ce8df9c0177d55a01, any TERM passed on the agetty command line would be used instead of the default TERM. After 4869b259d68f65ea88df625ce8df9c0177d55a01, the default TERM is used unconditionally.
Fix the regression by checking if the user passed a custom TERM.
Fixes: 4869b259d68f65ea88df625ce8df9c0177d55a01

agetty: Don't override TERM passed by the user

---

tests/ts/lsns/ioctl_ns

See #2967.
On the stable branch, we have rarely observed the lsns::ioctl_ns test case.
The changes in this pull request make the case print more information when it fails, which will be useful for future debugging of the case and lsns command.

lsns:  enhance the way to debug lsns::ioctl_ns test case

---

misc-utils/findmnt.c

libsmartcols expects it's data fields to be zero terminated. See the call to strlen() in scols_column_greatest_wrap(). ul_buffer however does not guarantee that termination, ul_buffer_append_strings() discard the zero-termination.
Always zero-terminate in get_data_col_sources() and drop the now unnecessary variable "i".
Closes: https://github.com/util-linux/util-linux/issues/2980
Notes:
The issue need root to reproduce.
This should also be backported.

findmnt: always zero-terminate SOURCES data

---

libmount/src/context.c

The function mnt_has_regular_utab() properly detects that the utab is not writable, but this is ignored by the high-level context API. As a result, the library later attempts to update the file and ends up with a warning in mount(8):
$ mkdir sys
$ unshare --map-root-user --mount
$ mount --rbind /sys sys
$ umount --lazy sys; echo $?
umount: /home/user/sys: filesystem was unmounted, but failed to update userspace mount table.
16
In this case, the utab should be ignored.
Fixes: https://github.com/util-linux/util-linux/issues/2981

libmount: Fix access check for utab in context

---

sys-utils/lsns.c

```
Segmentation fault (core dumped)
```
The function interpolate_missing_namespaces() reads data from /proc. However, in the case of a persistent namespace, there is no procfs entry for the namespace. Therefore, this function should ignore it.
Fixes: https://github.com/util-linux/util-linux/issues/2982

lsns: fix netns use

---

include/strutils.h
include/xalloc.h
meson.build
meson_options.txt

Sorry for the large PR, I can break into smaller PR's as necessary. I tried to keep the commits as small and focused as possible.
These are the remaining build options and tweaks to get Meson building on macOS, at least when using `meson setup -Dauto_features=disabled ...`. Still, macOS builds will continue to be blocked by issue #2873.
I should be able to follow up with additional fixes for when `-Dauto_features=disabled` is omitted.

meson: Add missing build options to enable building on macOS

---

sys-utils/flock.c

From mailing-list:
Currently, there is no way for shell scripts to safely access resources protected by POSIX locking (fcntl with the F_SETLK/F_SETLKW commands). For example, the glibc function lckpwdf(), used to protect access to the /etc/shadow database, works by taking a F_SETLKW on /etc/.pwd.lock .
Due to the odd semantics of POSIX locking (e.g. released when any file descriptor associated to the inode is closed), we cannot usefully directly expose the POSIX F_SETLK/F_SETLKW commands. However, linux 3.15 introduced F_OFD_SETLK[W], with semantics wrt. ownership and release better matching those of flock(2), and crucially they do conflict with locks obtained via F_SETLK[W]. With this, a shell script can do
exec 4> /etc/.pwd.lock
flock --fcntl 4
<access/modify /etc/shadow ...>
flock …

flock: add support for using fcntl() with open file description locks

---

sys-utils/losetup.8.adoc

See e.g. https://github.com/containers/bootc/pull/375#issuecomment-1981109022
The phrasing here was in my opinion technically correct but quite confusing and easy to misunderstand.
Let's be very clear:
- The default is *off*
- You can turn it on in two ways
- You can also explicitly turn it off

losetup.8: Clarify --direct-io

---

libblkid/src/superblocks/bcache.c

~The size of the super block as stated in the kernel:~
```c
sb_max_size_bits; /* base 2 of 512 byte sectors */
```
~So the existing constant is off by a factor of 512.  This was discovered as some existing bcachefs FS have super blocks which exceed (1 << 0x010) or 65536.~
This constant had an incorrect value.  However, the code already
does a max. size check which is correct.
Note: bcachefs can theoretically have a superblock of 32MiB, but
this is very unlikely to happen.

bcachefs: Remove BCACHEFS_SB_MAX_SIZE & check

---

libmount/python/meson.build
meson.build

This PR fixes a couple of issues with the current Python handling in Meson.
1. I inadvertently rendered the `build-python` option useless in commit b6799cc. This caused issue #3014.
2. The `embed` argument for the Python dependency used to incorporate the `Python.h` header file worked around an issue in Meson itself, see https://github.com/mesonbuild/meson/issues/12862 and the discussion in #2924. Meson should actually require the `Python.h` header file be present when `find_installation` is called for the Python module. This has an additional side-effect that Meson 1.4.1 will require `Python.h` in order to run the tests which use `find_installation`. The tests just need the path to the Python executable, not the `Python.h` header file.
This PR fixes these problems by making sure to use …

meson: Fix handling of the Python dependency

---

text-utils/column.1.adoc

fstab is:
1. fs_spec
2. fs_file
3. fs_vfstype
4. fs_mntops
5. fs_freq
6. fs_passno
In other words it's:
SOURCE,TARGET,TYPE,OPTIONS,FREQ,PASS

Fix fstab order in `column` manpage example.

---

disk-utils/cfdisk.c

'cfdisk_extra' looks unused since it's original commit (I think because it ended up using libscols instead). Remove it.

cfdisk: Remove unused struct 'cfdisk_extra'

---

lib/path.c

The current implementation cuts off the last character of the buffer if there is no trailing newline.

Fix ul_path_read_buffer()

---

include/pidfd-utils.h

This allows code which can gracefully fall back to compile.
This should fix the CI on Ubuntu 18.04.

include/pidfd-utils: provide ENOSYS stubs if pidfd functions are missing

---

pam_lastlog2/src/Makemodule.am

The second assignment ends up on the linker/libtool commandline, potentially confusing the tools.

pam_lastlog2: drop duplicate assignment pam_lastlog2_la_LDFLAGS

---

libmount/src/optlist.c

All atime settings are mutually exclusive, and the attr_set mask for the mount_setattr() syscall cannot contain multiple MOUNT_ATTR_ atime related options.
Unfortunately, during a remount, the list of options is composed of both old and new options. In this case, libmount sets more atime options to the mask. The correct behavior is to use the last atime related option from the list.
Fixes: https://github.com/util-linux/util-linux/issues/3032

libmount: Fix atime remount for new API

---

libuuid/src/gen_uuid.c

get_clock_counter() does not return a gregorian timestamp as required for v6.

libuuid: fix v6 generation

---

libsmartcols/src/calculate.c

There is no proper check for the number of reduction stages, so in some cases, the code can loop indefinitely.
The patch also fixes 'rc' variable shadowing.
Fixes: https://github.com/util-linux/util-linux/issues/3046

libsmartcols: fix reduction stages use

---

sys-utils/setarch.c

Fix the following build failure with uclibc-ng < 1.0.39 (i.e., without https://github.com/wbx-github/uclibc-ng/commit/85ac4f04d94e98389a8315e720630d0f95bfdfd6) raised since version 2.39 and https://github.com/util-linux/util-linux/commit/03a254f010b08da1175f50a8ae7882e59228f1b4:
```
sys-utils/setarch.c:106:7: error: 'PER_LINUX32_3GB' undeclared here (not in a function); did you mean 'PER_LINUX32'?
106 |     X(PER_LINUX32_3GB) \
|       ^~~~~~~~~~~~~~~
```
Fixes:
- http://autobuild.buildroot.org/results/fb1feb47f2660882fa53f66bacc63e191fd52175

sys-utils/setarch.c: fix build with uclibc-ng < 1.0.39

---

libuuid/src/Makemodule.am
libuuid/src/gen_uuid.c

More details in the commit messages.
The usage of `__attribute__((constructor))` is a bit iffy, but I didn't find another, always correct solution.

 libuuid: clear uuidd cache on fork() 

---

libuuid/src/libuuid.sym

The symbol uuid_time64 is conditionally defined. It only exists on 32-bit platforms that use the glibc library and enable support for the 64-bit time_t type.
For all other platforms, the symbol is undefined. As a result, when ld.lld version 17 or newer is used with default flags, ld.lld will reject the symbol map with the error:
version script assignment of 'UUID_2.40' to symbol 'uuid_time64'
failed: symbol not defined
To fix this issue, configure.ac and libuuid/src/Makemodule.am are updated to determine which version of the symbol map is needed, and supply the proper symbol map to ld.lld when linking.
fixes util-linux/util-linux#3036
fixes Gentoo bug #931328

Conditionally add uuid_time64 to sym. version map

---

libuuid/src/gen_uuid.c

The layout of "struct uuid" is specific to UUIDv1.
Using it for UUIDv6/7 makes the logic complicated and confuses Coverity.
Also validated with #3051

libuuid: construct UUIDv6/7 without "struct uuid"

---

Documentation/licenses/COPYING.EUPL-1.2
README.licensing

schedutils/coresched is licensed under the EUPL 1.2.
Similarly to other open source licenses, it is necessary to include a copy of the license.

docs: add European Public License v1.2

---

bash-completion/coresched

The bash completions for `coresched` were not yet implemented. This pull request implements bash completion for `coresched`.

coresched: add bash completions

---

libuuid/src/Makemodule.am

Since commit a3f1255f1891 ("libuuid: clear uuidd cache on fork()") compilation of gen_uuid.c requires libpthreads.

libuuid: link test_uuid_time with pthread

---

pam_lastlog2/src/pam_lastlog2.sym

otherwise ld.lld by default errors with
ld: error: version script assignment of 'global' to symbol 'pam_sm_chauthtok' failed: symbol not defined
since the symbol is not in the library

pam_lastlog2: remove symbol that doesn't exist from version script

---

libmount/src/context.c
libmount/src/context_mount.c
libmount/src/hook_loopdev.c
libmount/src/hook_mount.c
libmount/src/hook_mount_legacy.c
libmount/src/hook_subdir.c
libmount/src/mountP.h

Let's keep it simple and stupid :-) 
This set of patches only cleanups and extends the current internal API for the error messages generated by kernel or library modules. It does not introduce any replacement. This way seems the best.

libmount improve error messages

---

AUTHORS
term-utils/script-playutils.c
term-utils/script-playutils.h
term-utils/scriptreplay.1.adoc
term-utils/scriptreplay.c

Adds interactive playback controls based of #2999 .
Status:
I did not add all suggested in #2999 , These are what i think the most important.
Adding a backward step is non trivial without rewriting lots of how the playback works, and most terminals allow to scroll back the stream anyway.
Speed for holding the key-bind is also self emerging from the `inputDelay`.
So i think its best to attempt to merge this basic form so it ships the core features with less complex changes.

scriptreplay: add interactive playback controls

---

libmount/src/context_mount.c
libmount/src/context_umount.c
libmount/src/libmount.h.in
sys-utils/mount.8.adoc
sys-utils/umount.8.adoc

* Introduce special exit status 126 to inform about failed execl of the /sbin/[u]mount.<type> helpers.
* Introduce MNT_ERR_EXEC as an API return code to inform about failed execl() calls.
* Add mount and umount messages for failed execl() calls.
* Add EXIT STATUS section to umount man page.
Addresses: https://github.com/util-linux/util-linux/pull/3063

libmount: expose exec errors

---

.github/dependabot.yml

This should update your existing GitHub Actions to the latest latest version. 
By updating your GitHub Actions, you will get rid of the following [warnings](https://github.com/util-linux/util-linux/actions/runs/8433258299):
```
build (openwrt, ath79)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

Enable dependency manager for GitHub Actions

---

include/c.h

libc function dprintf is meant to be signal safe for as long you obey the documented constrains.

Allow printf to be used on signal handlers

---

sys-utils/lscpu-arm.c

Arm has announced the Cortex-X925 and published the TRM here: https://developer.arm.com/documentation/102807/0001/?lang=en
As well as the Cortex-A725 with a TRM here:
https://developer.arm.com/documentation/107652/0001/?lang=en

lscpu: New Arm Cortex part numbers

---

libmount/src/context.c
libmount/src/hook_mount.c
libmount/src/hook_subdir.c
libmount/src/mountP.h

* Initialize the tree file descriptor in the hook_subdir.c module if it has not been initialized yet. (hook_mount.c does not open the tree if the mount.<type> helper will be executed.)
* Move the function to open the tree to context.c to make it more generic and usable in more places.

libmount: fix tree FD usage in subdir hook

---

sys-utils/wdctl.c

When there is no sysfs at all for the watchdog, fall back to reading from the device node.
This is also useful if the legacy compat /dev/watchdog device which never has a sysfs interface.
Closes: #3073

wdctl: always query device node when sysfs is unavailable

---

lsfd-cmd/lsfd.c

Copied from the test case in lib/fileutils.c.

lsfd: minimize the output related to lsfd itself

---

sys-utils/lsns.c

Fix #2799.
If a process is gone, system calls accessing files under /proc can return ESRCH.
Suggested by Johannes Edmeier (@joshiste).

lsns: ignore ESRCH errors reported when accessing files under /proc

---

libmount/src/hook_mount.c

* Ensure data termination from read() function
* Allocate space for terminator using "sizeof(buf)-1"

libmount: improving robustness in reading kernel messages

---

include/pathnames.h
sys-utils/unshare.1.adoc
sys-utils/unshare.c

Based on https://lore.kernel.org/util-linux/20240619081951.656640-1-laurent@vivier.eu/

unshare: manage binfmt_misc mounts 

---

include/pathnames.h
sys-utils/swapoff.c

Based on patch from dparalen <vetrisko@gmail.com>.
Fixes: https://github.com/util-linux/util-linux/issues/3095

swapoff: avoid being killed by OOM

---

configure.ac

Currently, if `--disable-all-programs` is used hexdump cannot be built as `--enable-hexdump` is not recognized, so lets add support for it.

hexdump: allow enabling with --disable-all-programs

---

sys-utils/setpgid.c

f  was missing from the getopt_long optstring so only --foreground was
working, not -f.

sys-utils/setpgid: make -f work

---

misc-utils/lsblk-properties.c
misc-utils/lsblk.8.adoc
misc-utils/lsblk.c
misc-utils/lsblk.h

This new option allows for controlling the method(s) used by lsblk to gather file system and partition data about devices.
Fixes: https://github.com/util-linux/util-linux/issues/2047

lsblk: add --properties-by option

---

misc-utils/uuidd.c

Calling errx in sa_handler is as-unsafe as it is implemented using stdio.

misc-utils:uuidd: Use ul_sig_err instead of errx

---

man-common/bugreports.adoc

Otherwise, the period gets included in the URL which makes it not work.

Prevent problems with period after the URL

---

tests/helpers/test_sysinfo.c

Include `<sys/mount.h>` only on Linux; it is used for `fsopen()`, which is available only on Linux.

tests: include <sys/mount.h> only on Linux

---

libmount/samples/Makemodule.am

This sample uses the libmnt_context API, which is available only on Linux.

build-sys: build sample-mount-overwrite only on Linux

---

sys-utils/lsmem.c

Some systems may occupy the first memory block. As a result, the NUMA node is not printed. Add new option for force output all numa nodes of memory.
https://github.com/util-linux/util-linux/issues/3110

lsmem: make lsmem to check for the nodes more robust

---

meson.build
meson_options.txt

Allows using -Dauto_features=disabled to disable most utilities.
I have questions about this.
Is this PR on the right track? or should I try matching configure.ac?
As an example, configure.ac has
```
AS_HELP_STRING([--disable-scriptutils], [do not build script, scriptreplay and scriptlive]),
```
whereas in meson, these are all separate.

meson: add options for more utilities

---

term-utils/scriptlive.c

```
[vagrant@localhost ~]$ script --version
script from util-linux 2.40
[vagrant@localhost ~]$ scriptlive --version
scriptlive from util-linux 2.40
```
`scriptlive` does not echo (display) the commands it's re-running.
For example, here I create a simple "in" stream typescript.
```
[vagrant@localhost ~]$ script -ttypescript.timing -Itypescript.script
Script started, input log file is 'typescript.script', timing file is 'typescript.timing'.
[vagrant@localhost ~]$ date
Sat Jul 20 10:49:25 PM UTC 2024
[vagrant@localhost ~]$ 
exit
Script done.
```
When I re-run this, the input command `date` is not echoed.
```
[vagrant@localhost ~]$ scriptlive -ttypescript.timing -Itypescript.script
>>> scriptlive: Starting your typescript execution by /bin/bash.
[vagrant@localhost ~]$ 
Sat Jul 20 10:49:36 PM …
```

scriptlive: echo re-run commands from in stream

---

libuuid/meson.build

Fixes: https://github.com/util-linux/util-linux/issues/3131
https://github.com/util-linux/util-linux/pull/3017 didn't modify the meson build system to add the threads dependency to libuuid.
Changes are as per https://mesonbuild.com/Threads.html
We have it implemented here:
https://github.com/chromebrew/chromebrew/blob/44d2749e809d2b8f3083a2766303354f09f9ae5c/packages/util_linux.rb#L46

Add thread dep to libuuid meson.build to fix meson build regression in 2.40.2

---

sys-utils/lscpu-arm.c
sys-utils/lscpu-cputype.c
sys-utils/lscpu-virt.c
sys-utils/lscpu.c
sys-utils/lscpu.h

lscpu behaves differently when run sudo vs non-sudo on AMD architectures.
On sudo runs, it adds a BIOS model name and BIOS CPU family which it does not add for the latter. However since this parsing from the DMI is primarily catered to aarch64, for AMD platform the BIOS model name is printed out as follows "AMD XXX Processor *Unknown* CPU @ X.XGHz" due to the part number is not populated on the platform.
The issue boils down to an unconditional call to arm_decode() which attempts to read the DMI path and populate the processor information such as processor version and part number which is set to Unknown on AMD CPUs.
81d6de9 (lscpu: remove the old code) changed the DMI path from /sys/firmware/dmi/entries/4-0/raw (non-existent) to /sys/firmware/dmi/tables/dmi (existent) which has brought …

lscpu: Skip aarch64 decode path for rest of the architectures

---

libmount/src/context_mount.c

Fix the read-only fallback for a command such as:
```
mount -t ntfs3,ntfs-3g /dev/sda1 /media
```
where `ntfs-3g` is not found and will return `ENODEV`.
This extracts the error handling logic from `do_mount_by_pattern()` and reuses it in `do_mount_by_types()` so that processing the list of filesystem types stops when a "useful" error is returned.

Fix read-only fallback with multiple filesystem types

---

tests/functions.sh

Helpers should use ts_check_test_command, not ts_check_prog.

tests: properly look for ts_cap helper

---

libblkid/meson.build
libfdisk/meson.build
libmount/meson.build
libsmartcols/meson.build
meson.build

According to [1], since meson 0.49.0, using the / operator on strings is equivalent to calling join_paths().
As the expressions written using the / operator are shorter and nicer than their equivalents written using join_paths(), and given that we've been using this new operator since commit
5f2c862a4aff19f5bc732e677405f04e2d07c211, let's convert remaining join_paths() invocations to use the / operator instead.
[1] https://mesonbuild.com/Reference-manual_functions.html#join_paths

meson: use a / b instead of join_paths(a, b)

---

sys-utils/setpriv.1.adoc
sys-utils/setpriv.c

This makes it easier to use a debugger on systems with Yama configured without making the debugger binary itself privileged.

setpriv: Add --ptracer, which calls PR_SET_PTRACER

---

disk-utils/fdisk-menu.c
libfdisk/src/sgi.c

Four small fixes to entering a boot file name for an SGI disk volume header with fdisk.
1. The prompt was missing words.
2. The name minimum length was wrong.
3. The return value was wrong.
4. The return value was never passed up the chain, but the default -EINVAL instead.

fdisk: fix sgi bootfile entry

---

meson.build
misc-utils/Makemodule.am
tools/all_errnos
tools/all_syscalls

While creating a wrap-file for util-linux, I came across an issue with the paths of the generated
headers `syscalls.h` and `errnos.h`:
The output-path is currently the execution-path of the underlying scripts (`tools/all_syscalls` and
`tools/all_errnos`). This is by default the topmost build-directory in meson-build. However, when
adding util-linux as a subproject to any other project, it will lead to an error, as the topmost
build-directory is not an include-path (and should not!) of any of the util-linux' build-targets.
* Checkout <https://github.com/mesonbuild/wrapdb.git>
* Create the file `subprojects/util-linux.wrap` with the following content:
```
[wrap-git]
directory=util-linux
url=https://github.com/util-linux/util-linux.git
#revision=v2.40.2
revision=master
depth=1
[provide] …
```

meson: fix generated header paths while compiling as subproject

---

sys-utils/lscpu-virt.c

Patch from Mailing-list.
The lscpu command needs to traverse the /proc/bus/pci/devices file three times to check for any PCI devices related to virtualization. If there are many PCI devices on the machine, this can lead to increased execution time for lscpu. It would be beneficial to consolidate these queries into a single check to optimize the execution time of lscpu.
Use time command to test on a machine with 13000 PCI devices: before:
real  0m13.506s
user  0m0.028s
sys   0m13.409s
after:
real  0m5.834s
user  0m0.018s
sys   0m5.771s

lscpu: optimize query virt pci device

---

libblkid/src/probe.c

This PR propose to fix compilation error on Cygwin due to BLKBSZGET is missing.
In some cases where is `ioctls` is empty (may impossible?), `blkid_get_io_size()` simply and consistently returns `DEFAULT_SECTOR_SIZE` without any redundant assembly code.
Similar with util-linux/util-linux@224f299896db3021e4761e5f8abf9f2ec1d74c47, but I don't know if that's a good way to do it.

libblkid: improve portability

---

misc-utils/findmnt.c
tests/expected/findmnt/filterQ-options
tests/expected/findmnt/filterQ-options-name
tests/expected/findmnt/filterQ-options-nameval-neg
tests/expected/findmnt/filterQ-options-neg
tests/expected/findmnt/filterQ-options-no
tests/expected/findmnt/filterQ-types
tests/expected/findmnt/filterQ-types-multi
tests/expected/findmnt/filterQ-types-neg

```
$ findmnt -Q 'FSTYPE=="ext4"'
TARGET         SOURCE                  FSTYPE OPTIONS
/              /dev/sda4               ext4   rw,relatime
├─/var         /dev/sda3               ext4   rw,relatime
│ └─/var/cache /dev/sda5               ext4   rw,relatime
├─/mnt/virt    /dev/sdb1               ext4   rw,relatime
└─/boot        /dev/sda2               ext4   rw,relatime
``
Addresses: https://github.com/util-linux/util-linux/pull/3090

findmnt: improve -Q to output tree

---

tests/helpers/test_mkfds.c

A bit of background, at conda-forge we target 2.17, so ENOSYS isn't really defined.
xref: https://github.com/conda-forge/util-linux-feedstock/pull/42

Define EXIT_ENOSYS in test helpers

---

configure.ac
text-utils/more.c

This PR is attempted to simply fixes compilation error on Cygwin due to the missing `sys/ttydefaults.h`.
These codes are taken from [2.39.3-cygwin-more.patch](https://cygwin.com/cgit/cygwin-packages/util-linux/tree/2.39.3-cygwin-more.patch) on Cygwin.
`more` maybe works properly on other platforms (like FreeBSD), however I'm not tested.

more: fix compilation

---

bash-completion/newgrp
login-utils/newgrp.1.adoc
login-utils/newgrp.c

This patch proposes adding the `-c` command option to `newgrp`, generalizing the behavior from the `sg` utility in shadow-utils [1]. Rationale: usability of newgrp in the work flow of starting background processes, like firewalls as a specific group.
I'm aware of the no-new-option recommendation [2] but would argue that this change does not break SUSv2 (which newgrp does not adhere to the letter anyway, not allowing dash as the default group name).
Thank you for considering the proposal and I'd like to hear your thoughts.
[1] https://github.com/shadow-maint/shadow
[2] https://github.com/util-linux/util-linux/blob/25c6fc917ae4d30243ba655081ee84a839f338ba/Documentation/howto-contribute.txt#L242

Optionally execute a program after group change

---

.github/workflows/cifuzz.yml

The used v1 is deprecated and its usage generates errors. Use the current v4 instead.

ci: use upload action v4

---

bash-completion/look

look(1) opens /usr/share/dict/words as dictionary by default. Doing TAB completion for look(1) without the dictionary installed will result in popups like
$ look look: /usr/share/dict/words: No such file or directory
messing up the terminal.
As /usr/share/dict/words is not shipped by quite a few distros nowadays and it should not be listed as a hard dependency of util-linux, we make sure the dictionary exists before calling look(1) when doing completion, avoiding these error messages.

bash-completion: look: disable completion if dictionary is not available

---

.github/workflows/cifuzz.yml
bash-completion/sfdisk
disk-utils/fdisk.c
disk-utils/sfdisk.8.adoc
disk-utils/sfdisk.c
include/blkdev.h
sys-utils/blkdiscard.8.adoc
sys-utils/blkdiscard.c

Why do we need this? It can be difficult for end-users to discard
unpartitioned areas using blkdiscard, as it requires using fdisk to
obtain a list of free areas and then using blkdiscard with the correct
--offset and --length options. It is less risky for end-users to use
(s)fdisk, as they have a better understanding of the disk layout.

sfdisk: add --discard-free

---

misc-utils/meson.build

meson: don't install getopt examples if disabled

---

configure.ac
include/pidfd-utils.h
lsfd-cmd/lsfd.c
lsfd-cmd/lsfd.h
lsfd-cmd/sock-xinfo.c
sys-utils/lsns.c
sys-utils/nsenter.1.adoc
sys-utils/nsenter.c

Arista's userspace uses network namespaces a lot, including userspace VRFs, some form of containers, etc. Because of that, processes such as BGP may have many file descriptors in different network namespaces. There were issues with file descriptor leaks, which resulted in userspace misbehaviour and it was challenging to find which process/fd prevents some network namespace from being destructed. It resulted years ago in a kernel patch that provides `/proc/<pid>/fdns/...` links for each socket to its corresponding network namespace.
But we are in 2024 and I don't want to have or maintain such a patch. The userspace is fully capable of figuring out all the needed details about the sockets. Initially, I wrote a stand-alone tool that allows joining and showing the information about the …

lsfd + nsenter: Parse and allow to join target process's network namespace

---

.github/workflows/cibuild.yml

The current checkout action does not run on Ubuntu 18.04
/usr/bin/docker exec  90a3de3652fb2e69b0cf70fc8567dba6b1a25bf1a6645236d19bb6f1486c6158 sh -c "cat /etc/*release | grep ^ID" /__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
Fixes: #3215

CI: Downgrade checkout version for compat build

---

disk-utils/partx.8.adoc

The example is:
partx -d --nr :-1 /dev/sdd
Removes the last partition on _/dev/sdd_.
The documentation says:
M:
Specifies the lower limit only (e.g. --nr 2:).
:N
Specifies the upper limit only (e.g. --nr :4).
In the above example the lower limit is not set and the upper is set to the last partition, meaning all partitions. The lower limit should be set instead.
partx -d --nr -1: /dev/sdd

partx: Fix example in man page

---

login-utils/su-common.c

PAM modules can change the user during their execution, in such case su would still use the user that has been provided giving potentially access to another user with the credentials of another one.
So prevent this to happen, by ensuring that the final PAM user is matching the one required.
---
Another option is instead to perform the access for the new user as requested by PAM (and it looks somewhat better to me, but it has more implications):
```diff
diff --git a/login-utils/su-common.c b/login-utils/su-common.c
index 12c933633..409d7d4de 100644
--- a/login-utils/su-common.c
+++ b/login-utils/su-common.c
@@ -379,9 +379,10 @@ static void supam_export_environment(struct su_context *su)
}
}
-static void supam_authenticate(struct su_context *su)
+static const char *supam_authenticate(struct …
```

login-utils/su-common: Check the user didn't change during PAM transaction

---

meson.build

Commit 55c7120accab ("nsenter: Provide an option to join target process's socket net namespace") added stubs for pidfd_getfd() but didn't add the code for meson to check if the function is already available.

meson: test for pidfd_getfd()

---

login-utils/su-common.c

The additional coded added in commit
d6564701e812 ("login-utils/su-common: Check that the user didn't change during PAM transaction") was inserted in between the assignment and tests of "rc", making the return value unchecked.
Add a new explicit check.

login-utils/su-common: Validate all return values again

---

libfdisk/src/dos.c

The logical partitions are defined by a chain of extended partitions, with the beginning of the chain located on the whole disk device.
If a user runs "fdisk --list /dev/sda4", libfdisk cannot calculate proper offsets for the items in the chain, resulting in the following error message:
"Failed to read extended partition table (offset=22528): Invalid argument"
This error message may confuse users and is unnecessary when fdisk is used in list-only mode (--list option). It would be sufficient to only print the content of the partition without the error message and not continue to the next item in the chain.
However, in write mode (without --list), the error message will still be displayed as it is potentially dangerous to edit the EBR table.
Addresses: …

libfdisk: (dos) ignore incomplete EBR for non-wholedisk

---

tests/helpers/test_mkfds.c

As suggested by @karelzak in https://github.com/util-linux/util-linux/pull/3202#discussion_r1776568760 .
However, we keep calling unlink even when exiting with EXIT_FAILURE so as not to pollute the file system.

tests: (test_mkfds) don't close fds and free memorobjects when exiting with EXIT_FAILURE

---

libmount/src/context.c
libmount/src/context_mount.c
libmount/src/context_umount.c
libmount/src/mountP.h
sys-utils/mount.8.adoc
tests/expected/mount/xnocanon-file-over-symlink
tests/expected/mount/xnocanon-symlink-over-file
tests/expected/mount/xnocanon-symlink-over-symlink
tests/ts/mount/xnocanon

The new kernel mount API can bind-mount over a symlink. However, this feature does not work with libmount because it canonicalizes all paths by default. A possible workaround is to use the --no-canonicalize option on the mount(8) command line, but this is a heavy-handed solution as it disables all conversions for all paths and tags (such as LABEL=) and fstab processing.
This commit introduces the X-mount.nocanonicalize userspace mount option to control canonicalization. It only affects paths used for mounting and does not affect tags and searching in fstab. Additionally, this setting possible to use in fstab.
If the optional argument [=source|target] is not specified, then paths canonicalization is disabled for both the source and target paths.
Adresses: …

libmount: add X-mount.nocanonicalize[=source|target]

---

sys-utils/setpriv.c

Dynamic memory, referenced by 'buf' is allocated by calling function 'xstrdup' add then changed by calling of strsep function.
The free(buf) call is incorrect if buf != NULL, and points to some place inside or outside the source string.

sys-utils: (setpriv): fix potential memory leak

---

sys-utils/hwclock.c

Dynamic memory, referenced by 'content', is allocated by calling function 'xasprintf' and lost when function returns.
Found by the static analyzer Svace.

sys-utils: (save_adjtime): fix memory leak

---

login-utils/chsh.1.adoc

The current man page for chsh (1) contains duplicate descriptions for both options -h and -V, one given explicitly (in more detail) and another each from a standard include file. 
Excluded  man-common/help-version.adoc  to avoid duplicate -h  and -V option descriptions in the man page for  chsh(1).

Update chsh.1.adoc to avoid duplicates in man page

---

disk-utils/fdisk-list.c
libsmartcols/docs/libsmartcols-sections.txt
libsmartcols/samples/continuous-json.c
libsmartcols/samples/continuous.c
libsmartcols/src/libsmartcols.h.in
libsmartcols/src/libsmartcols.sym
libsmartcols/src/line.c
lsfd-cmd/lsfd.c
misc-utils/lsclocks.c
sys-utils/irq-common.c
sys-utils/lscpu.c
sys-utils/lsipc.c

Add new API functions using printf(3) compatible format strings to fill in column data.
These can be used to avoid intermediate buffers in the calling application code.
Everywhere a string generated with `xasprintf()` is directly passed to `scols_line_refer_data()`, use `scols_line_sprintf()` to remove the need for an intermediate buffer.

libsmartcols: add printf api to fill in column data

---

lsfd-cmd/lsfd.1.adoc

Inspired by the blog article:
https://blog.fraggod.net/2024/08/06/list-connected-processes-for-unix-sockets-on-linux.html

lsfd: (man) add more filter examples related to unix stream sockets

---

text-utils/column.1.adoc

This started out as a series of spelling corrections, but I've ended rephrasing some option descriptions as well. I hope they're a bit clearer now.

column.1.adoc: Fix spelling and improve option descriptions

---

disk-utils/mkswap.c

With --file, shen the file is created by mkswap, stat() fails with -ENOENT and the st_mode field is not populated, so the IS_REG() check fails. But if we created by mkswap, we know it's just a regular file and we should apply the selinux label.
Reported in https://bugzilla.redhat.com/show_bug.cgi?id=2324811#c56.

mkswap: set selinux label also when creating file

---

tests/ts/fadvise/drop
tests/ts/fincore/count

In certain isolation environments (f.e. Debian's sbuild+unshare), `/proc/mounts` does not have an entry for the directory we're building in.
Then, findmnt as used in the tests returns nothing. As the build directory might very well be on tmpfs (and often is, in Debian), disable the two tests known to fail on tmpfs.
In yet another scenario, if ran in a Docker/podman container, the fstype will read "overlayfs", which in the end can also be tmpfs, and we see problems there, too.
This was noticed because torvalds/linux@e88e0d366f9cfbb810b0c8509dc5d130d5a53e02 changed the behaviour of the underlying syscalls on tmpfs in Linux 6.6.
Closes: #3266
Debian bug #1086706

Skip tmpfs-sensitive tests if fstype cannot be determined

---

configure.ac
login-utils/login.1.adoc
meson.build
meson_options.txt
term-utils/Makemodule.am
term-utils/mesg.1.adoc
term-utils/mesg.c

* improve mesg(1) behavior in more explicit way
* add ./configure and meson options to disable setgid tty group
* remove  fchmod(S_IWOTH)  legacy support

mesg: tty group cleanup

---

sys-utils/nsenter.1.adoc
sys-utils/nsenter.c

The pidfd cannot be used to enter namespaces using setns() before Linux 5.7. To ensure compatibility with older kernels, we will check the kernel version before using pidfd_open() and, if necessary, fall back to using the classic /proc/#/ns/ files.
Reported-by: Alex Xu

nsenter: improve portability to older kernels

---

bash-completion/irqtop
bash-completion/lsirq
sys-utils/irq-common.c
sys-utils/irq-common.h
sys-utils/irqtop.1.adoc
sys-utils/irqtop.c
sys-utils/lsirq.1.adoc
sys-utils/lsirq.c

Add a new option to filter out IRQs whose counters are below the specified value. The argument supports plain integers and human readable values (e.g. `1.2K`).
For consistency with `irqtop`, add a `--cpu-list` option to `lsirq` to specify a list of CPUs for which to display interrupt counters.

lsirq and irqtop improvements

---

libblkid/src/superblocks/zfs.c

Currently, `blkid` relies on the presence of Uber blocks to detect ZFS partition types. However, Uber blocks are not consistently dumped for cache and spare vdevs, particularly in pools created prior to https://github.com/openzfs/zfs/commit/d9885b3. Additionally, indirect vdevs are incorrectly detected by `blkid` due to the presence of Uber blocks in the label. ZFS itself does not depend on Uber blocks either when reading ZFS labels; instead, it parses the nvlist.
This commit aligns `blkid`'s approach with ZFS by parsing the nvlist in the label to detect ZFS partition types, requiring at least one valid label for successful detection. This change also ensures compatibility with `wipefs`, as it now uses nvlist headers for offsets instead of the Uber Magic offset. Consequently, running …

libblkid: zfs: Use nvlist for detection instead of Uber blocks

---

meson_options.txt

This option was not used even when it was originally introduced in #2508.
Fixes #3163.

meson: remove unused lastlog-compat-symlink option

---

libmount/src/hook_loopdev.c
sys-utils/mount.8.adoc

libmount automatically creates a loop device and mounts it if the source of the mount is a regular file that contains a well-known filesystem. However, in some cases, this feature may be unwanted. The new mount option "X-mount.noloop" forces libmount to use the file directly as the mount source.
Addresses: https://github.com/util-linux/util-linux/pull/3288

libmount: support X-mount.noloop

---

term-utils/agetty.8.adoc
term-utils/agetty.c

Currently, additional locations (such as /run or /usr/lib) are only read if /etc/issue does not exist. This behavior makes it difficult to use local settings (/etc) together with generated (/run) and distribution-specific (/usr/lib) files. Let's read all the locations.
If the output of issue files is unwanted, the option --noissue can be used, or the default locations can be ignored by using --issue-file <list>.
Fixes: https://github.com/util-linux/util-linux/issues/3279
Addresses: https://github.com/systemd/systemd/issues/35071

agetty: always read additional issue file locations

---

libblkid/src/superblocks/zfs.c

[See this discussion on PR #3274](https://github.com/util-linux/util-linux/pull/3274#discussion_r1851902649)

libblkid: zfs: fix overflow warning [coverity scan]

---

libblkid/src/blkidP.h
libblkid/src/probe.c
libblkid/src/superblocks/ext.c

**[Patch from a mailing list.]**
Reads of ext superblocks can race with updates.  If libblkid observes a checksum mismatch, re-read the superblock with O_DIRECT in order to get a consistent view of its contents.  Only if the O_DIRECT read fails the checksum should it be reported to have failed.
This fixes a problem where devices that were named by filesystem label failed to be found when systemd attempted to mount them on boot.  The problem was caused by systemd-udevd using libblkid. If a read of a superblock resulted in a checksum mismatch, udev will remove the by-label links which result in the mount call failing to find the device.  The checksum mismatch that was triggering the problem was spurious, and when we use O_DIRECT, or even perform a subsequent retry, the superblock is …

libblkid: fix spurious ext superblock checksum mismatches

---

libmount/src/context_mount.c
libmount/src/context_umount.c
tests/expected/mount/special-basic
tests/expected/mount/special-multi-types
tests/expected/mount/special-options
tests/expected/mount/special-user
tests/expected/mount/special-username

libmount: exec mount helpers with posixly correct argument order
This improves compatibility with non-gnu userspaces.
On distributions such as Chimera Linux and Void Linux Musl where the libc provides posix getopt instead of gnu getopt, mount helpers which use getopt to parse arguments will not parse options which appear after non-option arguments. In particular, mount.nilfs2 from nilfs-utils is affected by this and on such systems, mounting NILFS filesystems fails in some situations when the mount utility is from util-linux and the nilfs mount helper is present. This patch ensures mount/unmount work as expected on such systems with no negative effects or compromises for ordinary GNU/linux.
Fixes [https://github.com/nilfs-dev/nilfs-utils/issues/12](https://github.com/nilfs-dev/nilfs-utils/ …

libmount: exec mount helpers with posixly correct argument order

---

configure.ac
sys-utils/Makemodule.am
sys-utils/hwclock-rtc.c
sys-utils/hwclock.c
sys-utils/hwclock.h

**[patch from mailing list]**
* configure.ac: add HURD so it can be used in conditional in am files
* sys-utils/Makemodule.am: compile hwclock for GNU Hurd
* sys-utils/hwclock-rtc.c: compile for GNU Hurd
* sys-utils/hwclock.c: compile for GNU Hurd
* sys-utils/hwclock.h: compile for GNU Hurd

hwclock: Support GNU Hurd

---

.gitignore

This file is generated by test runner and shouldn't be tracked.

gitignore: ignore `tests/failures`

---

misc-utils/fincore.c

fincore: Use correct syscall number for cachestat on alpha

---

sys-utils/lscpu-arm.c

Add an entry for FUJITSU aarch64 part MONAKA.
Dear lscpu development team,
This commit adds present support for FUJITSU-MONAKA.
Also update lscpu-arm.c to show the model name in lscpu command.
FUJITSU-MONAKA Specification URL:
https://github.com/fujitsu/FUJITSU-MONAKA
Please review and merge these patches
Best regards.
Emi, Kisanuki

lscpu: Add FUJITSU aarch64 MONAKA cpupart

---

misc-utils/lsclocks.c

Without an explicitly specified clock id, lsclocks would always use clock id 0 (CLOCK_REALTIME) for the dynamic/PTP clocks.

lsclocks: fix dynamic clock ids

---

libsmartcols/src/column.c
libsmartcols/src/table.c

Use gtk-doc constructs to mark up formatted sections of documentation so that they display properly in the rendered output.
- Enclose code samples with informalexample+programlisting tags
- Enclose preformatted blocks of text (tables) in same
- Present numbered lists in markdown format (leading 1., 2., etc.) so that they're translated into HTML ordered lists

libsmartcol docs: Format samples, lists, tables

---

lib/fileeq.c

The current code rounds down the values for readsiz and blocksmax, which is incorrect. The sizes must be large enough to match the files.
Addresses: https://github.com/util-linux/util-linux/issues/3330

hardlink: fix memory corruption (size calculation)

---

sys-utils/fstab.5.adoc
sys-utils/mount.8.adoc

The value of the mount option X-mount.idmap= can contain spaces as separators between mappings. Unfortunately, this conflicts with the fstab format where fields are separated by spaces. Using quotes does not solve this issue because fields are separated before they are parsed.
This limitation of the fstab parser within libmount is due to backward compatibility. The fstab format is a de-facto standard and is parsed by many tools and libraries, including third-party shell scripts. It would not be practical to introduce any improvements in libmount that would make fstabs unparseable in other places.
Users must understand that in-field spaces must be escaped by \040. For example, X-mount.idmap="0:0:1\040500:1000:1".
Addresses: https://github.com/util-linux/util-linux/issues/2829

fstab.5 mount.8: add note about field separator

---

.github/workflows/cibuild.yml

coverall CI output:
COMPILER=gcc
COMPILER_VERSION=10
...
Found gcov version: 13.2.0
...
geninfo: ERROR: Incompatible GCC/GCOV version found

ci: bump coveralls compiler version to gcc 13

---

tests/helpers/test_mkfds.c
tests/ts/lsfd/lsfd-functions.bash
tests/ts/lsfd/mkfds-vsock
tests/ts/lsns/filter

On some platforms, lsns::filter test failed with the following message:
+test_mkfds: failed to write to /proc/self/uid_map: -1: Operation
not permitted
The first commit in this pull request is to skip the test case on such platforms.
The second and the third commits are for skipping the lsfd::mkfds-sock test case where the diag socket for AF_VSOCK is unavailable.

revise test cases (lsns::filter and lsfd::mkfds-vsock)

---

meson.build

Noticed this when looking at why the `check` target isn't created with `-Dauto_features=disabled`. This doesn't fix that but it does fix a bunch of issues I noticed along the way after a hint from Eli Schwartz.

meson: add missing `is_disabler` checks

---

meson.build
meson_options.txt

libuuid is not compiled on FreeBSD.
--auto-features=disabled -Dbuild-libuuid=enabled -Dprogram-tests=false
Sponsored by: Future Crew, LLC

Check options for building lib_pam_misc

---

po-man/ro.po

asciidoctor-2.0.23 was giving an error:
asciidoctor: ERROR: fsck.minix.8.adoc: line 29: dropping cells from incomplete row detected end of table

po-man: Fix table formatting in romanian translation

---

include/logindefs.h
lib/logindefs.c
login-utils/login.c
login-utils/lslogins.c

When login is almost done it chdir()'s into the user's home directory. It currently uses pwd->pw_dir, i.e the home dir actually assigned to the user.
OTOH it explicitly allows overriding HOME (see comment in init_environ()), and explicitly imports PAM's env vars (which quite possibly contain $HOME) into its env block.
This patch makes sure that HOME is *properly* overridable via the env var and via PAM: it actually honours it for the chdir().
(Background: I am working on a PAM module that under some conditions would like to redirect the home dir to some other dir, and while I can nicely set $HOME from the PAM module, it has not as much as effect as I wish, because whie the rest of userspace respects it login so far didn't and leaves the user in the wrong dir).

login: actually honour $HOME for chdir()

---

disk-utils/sfdisk.c
libblkid/src/probe.c
libblkid/src/superblocks/ext.c
libmount/meson.build
libmount/src/Makemodule.am

This fixes non-Linux builds, by:
- making sfdisk discard option conditioned by availability of BLKDISCARD
- defining and using blkid_probe_get_buffer only if O_DIRECT is available
- always building src/fs_statmount.c and src/tab_listmount.c, they already contain proper conditions to make them void if support is not available.

Fix non-Linux build

---

lib/fileeq.c

The size of the eq->buf_a and eq->buf_b buffers depends on the readsize setting. This setting is modified by ul_fileeq_set_size(), so the buffers need to be resized accordingly. Deallocating is sufficient, as they will be allocated later with the correct size.
Addresses: https://github.com/util-linux/util-linux/issues/3330

hardlink: fix memory corruption in read buffers

---

meson.build
misc-utils/meson.build
misc-utils/uuidd-sysusers.conf

This will allow the user to be created automatically and the scriptlets to create the user and group dropped from the spec file: https://fedoraproject.org/wiki/Changes/RPMSuportForSystemdSysusers
The config is equivalent to what the Fedora package does, i.e. a dynamically-allocated uid and gid, and an account with nologin as the shell.

uuidd: add sysusers file

---

sys-utils/setpriv.c

The static analyzer flagged a memory leak in the parse_groups function. The memory allocated for 'buf' (via xstrdup) was not freed at the end of the function, leading to a memory leak.
Changes:
- Added free(buf) at the end of the function to release allocated memory.
Triggers found by static analyzer Svace.
Signed-off-by: Anton Moryakov <ant.v.moryakov@gmail.com>

setpriv.c: fix memory leak in parse_groups function

---

misc-utils/whereis.c

See https://github.com/util-linux/util-linux/issues/3239
Perhaps it would be better to fix xstrncpy to always add a terminating NUL to `dest`, even when `src` is an empty string (like `strncpy` does), but I'm not sure whether it would be safe.
The output it produces is still bogus, though:
```
root@974aed1734e0:/src# ./whereis /
`:
root@974aed1734e0:/src# ./whereis /
: /usr/share/man/cs/. /usr/share/man/da/. [ ... snip ... ] /usr/share/info/.
```
It's not clear what is the expected output in this case.

whereis: avoid accessing uninitialized memory

---

meson.build
sys-utils/fallocate.1.adoc
sys-utils/fallocate.c

Option --posix picks posix_fallocate, which does not have a
mode flag. Forbid using any options that set mode flags when
also giving --posix.
Addresses: https://lore.kernel.org/util-linux/173703231441.1463009.14898093986088300384@localhost/
Obviously it would be better if the modes were supported, but that means writing a lot more code.

fallocate: forbid --posix with special options

---

sys-utils/lscpu.c

**[from Mailing list]**
Change an adverb to an adjective, use the plural "lines", and use the plural form of the verb "have".  Also, put a clarification between parentheses, and reshuffle it a bit for clarity.

lscpu: make three column descriptions more grammatical

---

.github/workflows/cibuild.sh
.github/workflows/cibuild.yml

Generating all documentation (man pages, man page translations, and library API docs) is a very time-consuming task. It is also architecture-independent, as it involves text conversions using Python, Ruby, etc. It would be better to only do this once in CI and only when all other tasks have been successfully completed.
This commit also enables verbose output for autotools to make the compiler command line visible in logs.
* Add V=1 (verbose) for "make" command.
* Add CONFIGUREFAST phase with disabled po-man, asciidoc, and gtk-doc.
* Use full version CONFIGURE phase only for the distcheck CI job.

github: enable verbose output, don't generate docs default

---

lib/mbsedit.c
text-utils/pg.c

**[from Mailing list]**
Fix warnings when compiling without wide char support.
Marc.

Fix --disable-widechar compile warnings

---

login-utils/lslogins.c

In the parse_utmpx function, errors of the stat() call are ignored. As result is imax=1 and ary=NULL.
In best case will getutxent() fail, too. In worst case, lslogins will crash in ary[i] = *u; since ary is NULL and the if (i == imax) failed, since i=0 and imax=1.
Since we replaced wtmp with wtmpdb, there is no /var/log/wtmp on openSUSE/SUSE anymore. So we run quite frequently now into this.
My first idea was to add wtmpdb support, but since we have lastlog which provides all needed values, too, I see this as overkill.

lslogins: don't ignore stat error

---

sys-utils/dmesg.c

The --notime command line option disables parsing of timestamps from kmsg. This is a bug because the timestamps can be used for operations other than just output. For example, they can be used for filters like --since (dmesg --since '1 day ago' --notime).
Addresses: https://github.com/util-linux/util-linux/issues/3392

dmesg: fix --notime use

---

disk-utils/mkswap.8.adoc
disk-utils/mkswap.c
sys-utils/swapon.8.adoc

Let's attempt to set the "nonow" attribute; ignore it if unsupported.

mkswap: improve --file to be usable on btrfs

---

sys-utils/lscpu-topology.c

read_mhz() sets cpu->mhz_min_freq from /sys/devices/system/cpu/cpuN/ cpufreq/cpuinfo_min_freq. The file read fails if cpuN is offline and cpu->mhz_min_freq is left as 0. 0 MHz is treated as invalid frequency.
lsblk_cputype_get_minmhz() iterates through all possible CPUs to find the minimum frequency. If one or more CPUs are offline, the minimum frequency will be 0. This is reflected in the output of lscpu:
$ ./lscpu | grep min
CPU min MHz:                        0.0000
Ignore 0-MHz frequencies to find the actual minimum frequency:
$ ./lscpu | grep min
CPU min MHz:                     1200.0000
Reported-by: Thangamani Krishnan <thangamani.krishnan@intel.com>

lscpu: skip frequencies of 0 MHz when getting minmhz

---

lib/colors.c

The current check relies on "*sfile" to recognize if a configuration has been found in the current directory. However this condition is only true for "type == UL_COLORFILE_SCHEME", breaking the .enable and .disable configurations.
Instead reorder the logic a bit so that any valid configuration returns rc == 0.
Reported-by: Chris Hofstaedtler <zeha@debian.org>
Link: https://lore.kernel.org/util-linux/Z5a08yD10L1J8AIa@per.namespace.at/
Fixes: 4bdf22803f9a ("lib/colors: ensure fallback to system directory")

lib/colors: fix fallback to system directory

---

sys-utils/lscpu-virt.c

The comparison `'\0' != 0` always evaluates to false, as `'\0'` is
equivalent to 0. This check is redundant and triggers a warning from
the static analyzer (Svace). Remove it to avoid confusion and improve
code clarity.
Additionally, the check for sizeof(uint8_t), sizeof(uint16_t), and
sizeof(uint32_t) remains intact to ensure cross-platform compatibility.
Signed-off-by: Anton Moryakov <ant.v.moryakov@gmail.com>

sys-utils: remove redundant comparison in read_hypervisor_dmi in lscpu-virt.c

---

bash-completion/ipcmk
bash-completion/ipcrm
bash-completion/lsipc
configure.ac
include/pathnames.h
meson.build
sys-utils/Makemodule.am
sys-utils/ipcmk.1.adoc
sys-utils/ipcmk.c
sys-utils/ipcrm.1.adoc
sys-utils/ipcrm.c
sys-utils/ipcutils.c
sys-utils/ipcutils.h
sys-utils/lsipc.1.adoc
sys-utils/lsipc.c
sys-utils/meson.build

The lsipc, ipcrm and ipcmk tools currently support on the listing, removal and creation of System V IPCs. The additions include support for POSIX IPCs (shm, mqueue and sem).
- lsipc
a. Global view now also shows POSIX mqueue resource limits.
b. Command line options -M (--posix-shmems), -Q (--posix-mqueues), -S (--posix-semaphores) added.
c. Mounts `/dev/mqueue` if not already mounted for POSIX mqueue operations.
- ipcrm
a. Unlinks POSIX IPCs
- ipcmk
a. Opens POSIX IPCs

sys-utils: added POSIX IPC support to lsipc, ipcrm and ipcmk

---

sys-utils/fallocate.c

As far as I can tell, `--keep-size` is only incompatible with `--collapse-range` (as specified in the man pages).
This behavior was relied on before b85feb999c505222d4815638344c8883d5e4ab58, which reordered the mutually exclusive options in `fallocate.c`'s `excl` parameter to match the documented ascii-ordering requirement.
This was done with the express goal of making `--posix` incompatible with other options.  Presumably, the "incorrect" ordering of the options before that patch resulted in behavior that was mostly-acceptable.
This patch does something much simpler: it removes `n` from the list.  If `--keep-size` is indeed incompatible with `--zero-range`, then at a minimum, the following statement should be removed from the manual page, under the `--zero-range` option:
```
Option …
```

fallocate: keep-size and zero-range are compatible

---

schedutils/chrt.1.adoc
schedutils/chrt.c
tests/expected/schedutils/chrt-batch-custom-slice
tests/expected/schedutils/chrt-other-custom-slice
tests/functions.sh
tests/ts/schedutils/chrt

Kernels starting with 6.12 have a new feature which allows requesting a custom slice length on a task while using one of **SCHED_OTHER**, **SCHED_BATCH** or **SCHED_EXT**. The interface was created by repurposing the **_sched_attr::sched_runtime_** parameter. Similarly, this patch series uses the existing chrt interface to take advantage of this new feature.
With these changes, for **SCHED_{OTHER,BATCH}**, the current/new value of **_sched_runtime_** is reported even if the custom slice feature is not present and also, **SCHED_DEADLINE** output is now on two lines (see differences in expected test output). This may or may not be desirable.
Test output (kernel 6.13.0-rc1-00060-g7d9da040575b):
```
schedutils: chrt                           ...
: fifo                        ... OK
: batch …
```

chrt: Add --sched_runtime support for SCHED_{OTHER,BATCH}

---

sys-utils/lsipc.1.adoc

Missed updating man for lsipc.

lsipc: doesn't mount /dev/mqueue

---

configure.ac
meson.build
sys-utils/Makemodule.am
sys-utils/zramctl.c

systemd-udevd takes a lock during processing the uevent for a block device. The kernel refuses 'reset' attribute for zram device is written when the device node is opened. Hence, during systemd-udevd processes a uevent for zram device, we cannot write 'reset' attribute. Let's wait for the device being initialized and unlocked by udevd.
Note, there still exists a race window, as we need to release the lock before writing 'reset' attribute. But, the situation should be better now.

zramctl: wait for device being initialized and unlocked by udevd

---

term-utils/agetty.c

Addresses: https://github.com/util-linux/util-linux/issues/3304

agetty: fix stdin conversion to tty name

---

libmount/src/context_mount.c

When executed as root, libmount replaces the "owner" and "group" mount options with "nosuid, nodev, ..." However, this can result in an "invalid argument" error because libmount removes the unwanted options first and then tries to address the location for the new options using the already removed options. To fix this, we need to reverse the order of operations.

libmount: Fix removal of "owner" option when executed as root

---

include/mount-api-utils.h
libmount/src/fs.c
libmount/src/fs_statmount.c

* read mount source by statmount() 9requires kernel >=6.14
* add new STATMOUNT_* masks

libmount: add support for STATMOUNT_SB_SOURCE

---

sys-utils/fallocate.c

Follow up to [d95f9a6](https://github.com/aerusso/util-linux/commit/d95f9a6a7242bdcd2081c88caa34785cacd88d3e) and [util-linux#3410](https://github.com/util-linux/util-linux/pull/3410) addressing ordering requirements, natural incompatibilities between various options, and limitations of `posix_fallocate`.
@karelzak Hopefully I didn't fat-finger this PR yet again.

fallocate: rework incompatible options

---

include/pidfd-utils.h
misc-utils/kill.c
sys-utils/unshare.c
tests/helpers/test_mkfds.c

* Check for all SYS_* macros
* Define UL_HAVE_PIDFD only if all syscalls are available
Fixes: https://github.com/util-linux/util-linux/issues/3437

include/pidfd-utils: improve robustness

---

configure.ac
meson.build
tests/helpers/test_mkfds.c
tests/helpers/test_mkfds_ppoll.c

Fixes #3432
The ppoll multiplexer requires RAW sigset_t type generally defined in asm/linux.h. However, the parisc arch of the kernel older than 487fa28fa8b60417642ac58e8beda6e2509d18f9 didn't export the type to the user space.

test_mkfds: disable ppoll multiplexer if sigset_t is not defined

---

.github/workflows/cibuild.yml

The latest v3 version should address the sporadic segfaults we've been
seeing (mainly on s390x).

ci: bump uraimo/run-on-arch-action to v3

---

tests/ts/lsns/nsfs

Fixes #3442
If a target directory is bind-mount'ed, lsns returns multiple paths as the value for NSFS column. This change considers this case.

tests: (lsns/nsfs) consider the cases that lsns returns multiple paths

---

sys-utils/lscpu-arm.c

Arm has announced the Cortex-A320 and published the TRM here: https://developer.arm.com/documentation/109551
The Cortex-A520AE with a TRM here:
https://developer.arm.com/documentation/107726
The Cortex-A720AE with a TRM here:
https://developer.arm.com/documentation/102828
The Neoverse-V3AE with a TRM here:
https://developer.arm.com/documentation/101595

lscpu: New Arm part numbers

---

sys-utils/chmem.c

sys-utils/chmem: fix typo.

---

meson.build

Before it was different, and the executable was not installed.

meson: bring hexdump in line with others

---

tools/poman-translate.sh

For example (`cd ..`  from git working directory):
```
cd ..
meson setup build-dir util-linux
ninja -C build-dir
```
Addresses: https://github.com/util-linux/util-linux/pull/3378

tools/poman-translate: fix to work outside on source dir

---

sys-utils/lsipc.c

Use `ipc_stat::cgid` for the column `COL_CGID`.

Use `ipc_stat::cgid` for the column `COL_CGID`.

---

sys-utils/Makemodule.am
sys-utils/lscpu-cputype.c
sys-utils/lscpu-riscv.c
sys-utils/lscpu.c
sys-utils/lscpu.h
sys-utils/meson.build
tests/expected/lscpu/lscpu-rv64-linux
tests/expected/lscpu/lscpu-rv64-milkvpioneer
tests/expected/lscpu/lscpu-rv64-visionfive2

[**from mailling list**]
The ISA information for RISC-V is important for understanding the different extensions supported by the CPU. Print the ISA information in the summary, with the Base ISA and single-letter extensions at the beginning, followed by multi-letter extensions sorted in alphabetical order. The information is the same as the cpuinfo information, except that underscores are replaced by spaces and multi-letter extensions are simply sorted instead of following any ISA string ordering rule.
The sample output below shows the difference between cpuinfo and lscpu.
cpuinfo output:
isa             : rv64imafdch_zicbom_zicboz_zicntr_zicsr_zifencei_zihintntl_zihintpause_zihpm_zawrs_zfa_zba_zbb_zbc_zbs_smaia_ssaia_sstc
lscpu output:
ISA:                rv64imafdch smaia ssaia sstc …

lscpu: RISC-V: Print ISA information in summary

---

lib/colors.c
lib/terminal-colors.d.5.adoc
man-common/colors.adoc

We already provide the ability to easily disable output colorization, but there is also the https://no-color.org initiative based on the NO_COLOR environment variable. Let's support this method to disable colors. Let's be friendly :-)
Addresses: https://github.com/util-linux/util-linux/issues/3463

terminal-colors.d: support NO_COLOR

---

po-man/meson.build
tools/poman-install.sh

* in po-man/meson.build use already defined mandir
* make sure $DESTDIR is used in the install script
Addresses: https://github.com/util-linux/util-linux/pull/3378

meson: fix po-man installation

---

sys-utils/flock.c

This patch fixes a spelling typo in a message.

sys-utils/flock.c Fix a typo in flock.c

---

include/pathnames.h
sys-utils/hwclock-rtc.c
sys-utils/hwclock.8.adoc

This (effectively) reverts commit
1811900a91be856e794005511eac7859adb8e383.
There was no real motivation given, and it certainly makes the default behaviour of hwclock on current linux systems counter-intuitive: udev has a standard rule so that whichever rtc device is designated as the CONFIG_RTC_HCTOSYS_DEVICE one in the kernel configuration also becomes the target of the /dev/rtc symlink. People may have some other way of setting that symlink, but regardless, that must be considered the primary or default rtc for the system.
Also, busybox's implementation of hwclock still uses the original /dev/rtc, /dev/rtc0 order, meaning that installing util-linux's version on a board previously using busybox leads to unexpected regressions - it's not at all clear that one must go around and stick …

Revert "hwclock-rtc.c: try the 'new' rtc class first"

---

sys-utils/lsns.c

Fixes:
sys-utils/lsns-lsns.o: In function `read_process':
lsns.c:(.text+0x9e8): undefined reference to `add_namespace_for_nsfd'
collect2: error: ld returned 1 exit status
This should fix https://github.com/util-linux/util-linux/issues/3483, but I'm not really sure that my fix/implementation is the right one, so see it as a reference.

lsns: fix undefined reference to add_namespace_for_nsfd #3483

---

lsfd-cmd/lsfd.1.adoc
lsfd-cmd/lsfd.c
lsfd-cmd/sock-xinfo.c
tests/expected/lsfd/mkfds-mapped-packet-socket
tests/helpers/test_mkfds.c
tests/ts/lsfd/mkfds-mapped-packet-socket

The original code read the protocol field of /proc/net/packet as a decimal number.

lsfd: scan the protocol field of /proc/net/packet as a hex number

---

include/namespace.h

sys-utils/lsns.c: In function ‘add_namespace_from_sock’: sys-utils/lsns.c:580:19: error: ‘SIOCGSKNS’ undeclared (first use in this function)
nsfd = ioctl(sk, SIOCGSKNS);
^~~~~~~~~
SIOCGSKNS was added in https://github.com/torvalds/linux/commit/c62cce2caee558e18aa05c01c2fd3b40f07174f2.
Fixes: https://github.com/util-linux/util-linux/issues/3502

lsns: fix compilation on Linux < 4.10

---

lsfd-cmd/lsfd.c
misc-utils/enosys.c
misc-utils/uuidd.c
misc-utils/wipefs.c
sys-utils/ipcrm.c
sys-utils/nsenter.c

In some parts of the code, the optional argument handling is missing for cases where the argument starts with '='. This is particularly important for short options with optional arguments, as suggested by our man pages. The libc getopt_long() handles this for long options, but for short options, it's our responsibility.
Note that some argument parsing functions (mostly colormode_or_err()) already implement this, as they are usually used with optional arguments.

treewide: fix optional arguments usage

---

disk-utils/mkfs.bfs.c
include/c.h

GCC15 requires to annotate such fields as nonstrings or a warning is now issued that they are missing the ending null.

disk-utils: add attribute nonstring to bfs byte arrays

---

libuuid/src/uuid_time.c

Weak aliases are not supported by clang on Darwin. Instead this fix uses inline asm to make `_uuid_time` and alias to `___uuid_time`
Fixes util-linux/util-linux#2873

This re-enables build on macOS.

---

meson.build

Should append instead of assigning. Otherwise fails with
```
meson.build:1482:22: ERROR: Object <[ExternalLibraryHolder] holds [ExternalLibrary]: <ExternalLibrary rt: True>> of type ExternalLibrary does not support the `+` operator.
```

meson: fix a bug in posixipc_libs configuration

---

libblkid/src/verify.c
liblastlog2/src/lastlog2.c

Using strerror is not safe in shared libraries as it is unknown what the calling apps may do with the storage behind the scenes. Using %m is ok, except in contexts that need to be as-safe.

Do not use strerror on shared libraries

---

include/loopdev.h
lib/loopdev.c

Details in the commit messages.
This is not yet ready to be merged as the kernel fix has not hit mainline yet.

lib/loopdev: drop workaround for kernel uevent bug and some cleanups

---

libblkid/src/superblocks/befs.c

Fix segfault caused by underflow while parsing a corrupted metadata.
Found by OSS-Fuzz by cryptsetup project fuzzers (issue 411003898).

libblkid: befs: fix underflow

---

include/mount-api-utils.h

If SYS_statmount/SYS_listmount is not provided by the libc, util-linux will fall back to __NR_statmount/__NR_listmount from the kernel UAPI headers.
However it is not guaranteed that these symbols are actually visible in mount-api-utils.
Include linux/unistd.h which provides syscall numbers. While this header is specific to Linux, the code is already using linux/mount.h.

include/mount-api-utils: include linux/unistd.h

---

configure.ac
meson.build

Doesn't build on macOS.
Fixes: 6e1301d59 ("text-utils: add bits command")

bits: only build when cpu_set_t is available

---

lib/strutils.c

strutils.c: ignore escape characters while parsing options.

---

.github/workflows/cibuild.yml

OpenWRT has SDKs targetting MIPS 32bit/64bit, bit and little endian. No other CI job currently builds util-linux on MIPS. Add a job for 32bit little endian and 64bit big endian, This should provide adequate coverage.

ci: build on MIPS

---

include/mangle.h
lib/mangle.c
libmount/src/hook_mount.c

Follow-up: 8a69fa852dd5f41f8456756d18bfac6d8208219f https://github.com/util-linux/util-linux/pull/3541

libmount: add function to remove escaped chars

---

bash-completion/chrt
schedutils/chrt.1.adoc
schedutils/chrt.c
schedutils/sched_attr.h
tests/expected/schedutils/chrt-ext
tests/ts/schedutils/chrt

SCHED_EXT was added in kernel 6.12, which lets processes be scheduled by a BPF-defined scheduler. This PR adds SCHED_EXT support to chrt, updates the tests, the man page, and bash completion.

Add SCHED_EXT support to chrt

---

libblkid/src/config.c

As the whole econf_file structure is freed by econf_free(file) at the end of blkid_read_config(), econf_file structure cannot be defined as static and initialized only once. The econf_free() is not robust enough and keeps a pointer to the garbage after the first call of blkid_read_config(). And if /etc/blkid.conf does not exist, it is called second time.
Link: https://bugzilla.opensuse.org/show_bug.cgi?id=1242705

libblkid: Fix crash while parsing config with libeconf

---

misc-utils/lsblk-properties.c

The udev database typically inherits the ID_PART_TABLE_TYPE property from the entire disk device to its partitions. However, in some cases, this property may be missing. Fortunately, blkid/udev also provides ID_PART_ENTRY_SCHEME for all partitions.
Fixes: https://github.com/util-linux/util-linux/issues/3570

lsblk: use ID_PART_ENTRY_SCHEME as fallback for PTTYPE

---

login-utils/setpwnam.c

Fix heap-buffer-overread in setpwnam.c triggered by 256-byte username

---

bash-completion/fincore
misc-utils/fincore.1.adoc
misc-utils/fincore.c

When cachestat() is not available, mmap() and fincore() are used to get cache statistics.
This fallback returns less data than cachestat, and potentially hides read errors by reporting that the file is all mapped in memory:
$ fincore /usr/bin/java
fincore: failed to do cachestat: /usr/bin/java: Operation not permitted
RES PAGES   SIZE FILE
208K    13 198,1K /usr/bin/java
$ echo $?
0
$ sudo fincore /usr/bin/java
RES PAGES   SIZE FILE
0B     0 198,1K /usr/bin/java
Add a --cachestat argument which forces cachestat usage and fails if it's not available:
$ fincore -C /usr/bin/java
fincore: failed to do cachestat: /usr/bin/java: Operation not permitted
$ echo $?
1
Also, on huge files the fallback is very slow and memory consuming, so this flag can be user to avoid doing it by mistake.

add option to force cachestat() usage

---

disk-utils/cfdisk.c
disk-utils/fdisk.c
disk-utils/partx.c
include/strutils.h
include/timeutils.h
lib/strutils.c
lib/timeutils.c
libfdisk/src/gpt.c
libfdisk/src/script.c
login-utils/last.c
misc-utils/cal.c
sys-utils/dmesg.c
sys-utils/eject.c
sys-utils/hwclock.c
sys-utils/losetup.c
sys-utils/lscpu-topology.c
sys-utils/rtcwake.c
sys-utils/tunelp.c
term-utils/setterm.c
text-utils/column.c

This is a backport of add ul_ prefix patches #3569 to v2.41: Patches 1, 2 and 4 are simply applied, patch 3 treewide: (add ul_ to parse_switch() function name) was created again.

Backport add ul_ prefix to v2.41

---

tests/ts/kill/decode

glibc uses 34 as the value of SIGRTMIN:
https://sourceware.org/git/?p=glibc.git;a=blob;f=signal/allocrtsig.c;h=8ed8e37dd6c41f94be6eef042ce9db1af1153228;hb=HEAD#l27 """
static int current_rtmin = __SIGRTMIN + RESERVED_SIGRT; """
musl uses 35 as the value of SIGRTMIN:
https://git.musl-libc.org/cgit/musl/tree/src/signal/sigrtmin.c
Adjust the test case to cope with musl. Otherwise, it fails with the following difference:
-Ignored: HUP QUIT TRAP PIPE ALRM
+Ignored: HUP QUIT TRAP PIPE ALRM 34

ts/kill/decode: fix for musl

---

sys-utils/mount.8.adoc

Cleanout the mount options, and import the options from the upstream documentation found at https://docs.kernel.org/filesystems/ntfs3.html
Fixes: 847264af6 docs: update mount type to 'ntfs3'

docs: update mount options for 'ntfs3'

---

schedutils/chrt.1.adoc
schedutils/chrt.c

Currently, chrt requires a priority argument even for scheduling policies like SCHED_OTHER and SCHED_BATCH, which ignore it.
This change relaxes that requirement. Now, priority is only expected for SCHED_FIFO and SCHED_RR. For other policies, a default value of 0 is set internally and no argument is required on the command line.
This simplifies usage when modifying runtime parameters like --sched-runtime for non-realtime tasks.
For example, to change the EEVDF tunable base_slice, one currently needs to run:
chrt -v -o -T 1000000 -p 0 $PID
Passing '0' after -p is not intutive and not required as priority is not applicable to SCHED_OTHER tasks. Now with this patch, one can do: chrt -v -o -T 1000000 -p $PID
Passing '0' still works ensuring ABI doesn't break.

chrt: Make priority optional for policies that don't use it

---

.gitignore

These are auto-generated and clutter git status.
It's even worse with jj, which will auto-add them.

gitignore: Ignore tests/diff/ and test/output/

---

misc-utils/lsblk.c

Use `"md"` as a fallback for the device type if the sysfs file `md/level` is read but is empty.
Fixes: #3632

lsblk: use md as fallback TYPE when md/level empty

---

bash-completion/enosys

The function `_enosys_module` referenced by the completion setting on [the last line of `bash-completion/enosys`](https://github.com/util-linux/util-linux/blob/06419fe95b06c7aa8670081a68dbe43a53bff303/bash-completion/enosys#L50) is not defined in the current master.  As reported in Ref. [1], this causes the following error on an attempt at argument completion for the `enosys` command:
```
bash: _enosys_module: command not found
```
- [1] [linuxbrew error : r/Fedora](https://www.reddit.com/r/Fedora/comments/1llmu0w/comment/n00y98k/)
Also, [the function `_waitpid_module` defined in `bash-completion/enosys`](https://github.com/util-linux/util-linux/blob/06419fe95b06c7aa8670081a68dbe43a53bff303/bash-completion/enosys#L1) overwrites [another completion function of the same name defined in …

bash-completion: fix function name of enosys completion

---

sys-utils/setpriv.c

setpriv(1) is Linux-only, and on Linux, getgroups() returns at least one group. However, it's better to use more portable and generic code patterns and assume that getgroups() can return zero.
Fixes: https://github.com/util-linux/util-linux/issues/3654

setpriv: Improve getgroups() Portability

---

libblkid/src/superblocks/ext.c

Currently the false positive rate for ext super block is a little too high, we've hit this several time with random data in encrypted disk from cloud provider. e.g.
```
% xxd -a ./test.ext4.img                                             
00000000: 0000 0000 0000 0000 0000 0000 0000 0000  ................
*
00000430: 0000 0000 0000 0000 53ef 0000 0000 0000  ........S.......
00000440: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000450: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000460: 0800 0000 0000 0000 0000 0000 0000 0000  ................
00000470: 0000 0000 0000 0000 0000 0000 0000 0000  ................
*
% blkid ./test.ext4.img                                              
./test.ext4.img: BLOCK_SIZE="1024" TYPE="jbd"
```
The false positive rate is …

libblkid: (ext) reduce false positive

---

tests/helpers/test_sigstate.c

After upgrading bash to 5.3 to contain commit [1], if SIGINT was trapped in asynchronous subshell, bash called set_signal_async_ignored to make sure processes that are created by this asynchronous subshell to ignore SIGINT.
And it caused test case `kill/decode' failed, the signal INT was existed in both of Blocked and Ignored
$ ./tests/run.sh --use-system-commands --parsable --show-diff   kill/decode
...
diff-{{{
|--- /usr/lib/util-linux/ptest/tests/expected/kill/decode        2011-04-05 23:00:00.000000000 +0000
|+++ /usr/lib/util-linux/ptest/tests/output/kill/decode  2025-07-28 12:09:46.279000000 +0000
@@ -16,5 +16,5 @@
Pending (thread): INT ILL
Pending (process): USR1
Blocked: INT ILL ABRT FPE USR1 SEGV TERM
-Ignored: HUP QUIT TRAP PIPE ALRM
+Ignored: HUP INT QUIT TRAP PIPE ALRM
Caught: …

tests/helpers/test_sigstate.c: explicitly reset SIGINT to default action after trapping

---

meson.build

curses is special in that it's able to find ncurses in a lot more locations that ncurses, which only looks at pkg-config and cmake. This is somewhat useful with exotic OSes like macOS.

meson: use curses dep for ncurses

---

sys-utils/setpriv-landlock.c

The LANDLOCK_ACCESS_FS_IOCTL_DEV access right controls whether the process may use IOCTL on opened device files.  It is available since Linux 6.10.
Compatibility remark:
With this change, using the --landlock-access="fs" shortcut now requires Linux 6.10+, where it previously required Linux 6.2+.

setpriv: Add support for LANDLOCK_ACCESS_FS_IOCTL_DEV

---

sys-utils/fstab.5.adoc
sys-utils/swapon.8.adoc

The fstab(5) man page already describes some basic aspects of "swap," but it makes sense to be more specific in the swapon man page and describe everything in one place, serving as a normative reference for what is expected on Linux in fstab for swap.
Fixes: https://github.com/util-linux/util-linux/issues/3667

swapon: (man page) add details about fstab configuration

---

sys-utils/fallocate.1.adoc
sys-utils/fallocate.c

[**from mailing list**]
The Linux kernel is planning to support FALLOC_FL_WRITE_ZEROES in fallocate(2). Add FALLOC_FL_ZERO_RANGE support to fallocate utility by introducing a new option -w|--write-zeroes.

fallocate: add FALLOC_FL_WRITE_ZEROES support

---

misc-utils/lsclocks.c

MAX_CLOCKS is only available in the kernel UAPI headers and not libc headers. Switch back to a hardcoded value. This value is a stable ABI anyways and matches the other fallback definitions.
Fixes: d3c49ee062f7 ("lsclocks: use MAX_CLOCKS, improve indention")

lsclocks: stop using MAX_ClOCKS

---

misc-utils/kill.c

Align the wrapped help text indentation in `kill --help` and fix a small
grammar issue in a comment. No functional changes.
1) **Help/usage**
- In the `-l, --list` description, increase the leading spaces on the
wrapped continuation line (“or convert a signal mask to names”) by one,
so wrapped lines align with the common util-linux help style (see
Documentation/howto-usage-function.txt).
2) **Comments**
- In `parse_arguments()`, insert **“that”** so the sentence reads:
“-a is the only option **that** can be used with other options.”
- Other util-linux tools (e.g., `fdisk`, `logger`, `last`) indent wrapped
help lines consistently; this line in `kill` was off by one space.
- The comment fix improves readability.
- **No functional impact.**
- The help text change touches a **translatable …

kill: usage: fix wrapped indent; comments: add 'that'

---

Documentation/TODO
misc-utils/getopt.1.adoc
misc-utils/getopt.c

This feature addition will add the '-U' and '--unknown' options It'll allow getopt to ignore unknown options and leave them untouched. Additionally, it will surpress any error messages generated by getopt(3).
Addresses: #701

getopt: add feature to ignore unknown options

---

bash-completion/umount

If the user defined path can not be found in the mount table fallback to simple filename expansion.
Addresses: #1333

bash-completion: add fallback to filename expansion for umount

---

sys-utils/ipcrm.1.adoc

Short options -x, -y, and -z do not exist.
The man page was not revised after the local code was changed to follow Open Group requirements for ipcrm.

man: Fixed incorrect ipcrm options

---

sys-utils/zramctl.c

The `max_comp_streams` attribute of zram devices has been deprecated and all writes were silently ignored by the kernel since 2016. It was finally removed in 6.15, causing zramctl to fail on ENOENT, when it should just ignore the error.

zramctl: ignore ENOENT when setting max_comp_streams

---

bash-completion/lscpu
sys-utils/lscpu.c

While adding support for the CPU microcode version summary, I forgot to add the output column.

lscpu: add microcode output column

---

tests/ts/lsfd/column-source-btrfs

This change fixes a potential bug in the test case.
The originala code used the %d of stat command to extract the device minor number for a file based on a wrong assumption. Use %Ld instead.

tests: (lsfd/column-source-btrfs) extract a minor number in a more reliable way

---

sys-utils/nsenter.1.adoc
sys-utils/unshare.1.adoc

The NS-related commands in util-linux complement each other. Users should know them.

nsenter,unshare: (man) add the NS-related commands to SEE ALSO

---

include/Makemodule.am
include/netaddrq.h
include/netlink.h
lib/Makemodule.am
lib/meson.build
lib/netaddrq.c
lib/netlink.c
term-utils/agetty.8.adoc
term-utils/agetty.c

The current \4 and \6 issue file escapes implementation is inferior. It uses get getifaddrs() to get a list of IP addresses. This function does not provide enough information to discriminate between stable IP addresses and ephemeral addresses. As a result, especially \6 often gives unreliable results. This is a limitation of getifaddrs().
This change set implement netlink base IP address processing in agetty, and creates a library for generic use. It solves the problem and provides a generic framework for the future use.
TODO:
treewide:
There are more places using netlink. It would be nice to use the library in all these places.
agetty:
Two pass processing of issue files. First pass just collects IP protocols and list of interfaces (in future interface patterns). Now it always processes …

agetty: Implement netlink based IP processing

---

sys-utils/lsns.c

In 7d5036fdafe0 ("lsns: show namespaces only kept alive by open file descriptors"), I added code that calls stat(2) on /proc/self/ns/user and made lsns exit after reporting an error if the call failed. I assumed /proc/self/ns/user would be available on all platforms.
As Axel Karjalainen reported (link below), that assumption was wrong: on some platforms, the file is absent. Exiting for this reason is undesirable.
The stat(2) call is used to obtain the dev_t of the backing device of nsfs. However, /proc/self/ns/user is not the only source; calling stat(2) on other namespace files under /proc/self/ns yields the same dev_t. This change iterates over entries under /proc/self/ns and uses the first one whose stat(2) succeeds.
Reported-by: Axel Karjalainen <axel@axka.fi>
Link: …

lsns: don't abort if /proc/self/ns/user is absent; probe other ns entries

---

misc-utils/kill.c

It helps using kill -l/-L in a script.
$ ./kill -L
1 HUP      2 INT      3 QUIT     4 ILL      5 TRAP
6 ABRT     6 IOT      7 BUS      8 FPE      9 KILL
...
$ ./kill -L | cat
1 HUP
2 INT
3 QUIT
...
Should I add a new option for controlling the behavior?

[RFC] kill (-l/-L): print one signal per line when stdout is not a TTY
